### ISSUE TITLE
Does RepeatedField need a len field?

### ISSUE THREAD

**Issue by cristicbz** [stepancheg/rust-protobuf#100]
I'm a bit confused by the implementation of RepeatedField. It seems to me that for all means and purposes it could be a newtype:
```rust
struct RepeatedField<T>(Vec<T>);

impl<T> Deref for RepeatedField<T> {
    type Target = Vec<T>;
    fn deref(&self) -> &Vec<T> { &self.0 }
}

impl<T> DerefMut for RepeatedField<T> {
    fn deref_mut(&mut self) -> &mut Vec<T> { &mut self.0 }
}
```
with Deref and DerefMut implementations for Vec<T> rather than [T] (so as to forward method calls like .push, .extend etc to the inner vec).

I'm sure I'm missing some clever trick with the len field, could anyone explain why it's implemented the way it is?

**Comment by stepancheg** [comment]
To reuse previously allocated memory.

I've explained it there: #84.

**Comment by cristicbz** [comment]
Thank you! Sorry I didn't see the previous issue
