### ISSUE TITLE
update crates.io

### ISSUE THREAD

**Issue by TeXitoi** [stepancheg/rust-protobuf#102]
Now that rust-protobuf is stable compliant, it can be great to have a stable compliant version on crates.io, as this version should compile forever.

**Comment by icorderi** [comment]
+1
@stepancheg you mind releasing v0.0.10 or v0.1.0 to crates.io?

By the way, found this little badge useful for the readme.
[![](http://meritbadge.herokuapp.com/protobuf)](https://crates.io/crates/protobuf)
Displays the latest version published and links it to the crates.io site.

**Comment by stepancheg** [comment]
Pushed latest version (0.0.10) to creates.

I have doubts about crate that could compile forever. Beause rust-protobuf is not just library, but also a generated code, and generated code may be incompatible with library runtime. Runtime is likely to be changed after upcoming google protobuf 3 implemented in rust-protobuf.

BTW, if you have any ideas about API of rust-protobuf, please share. It would be nice make at least public API it stable after rust 1.0.

**Comment by stepancheg** [comment]
@icorderi how to make that badge?

**Comment by borntyping** [comment]
The badge is from http://shields.io/, which has a few badges for Rust crates.

![](https://img.shields.io/crates/v/protobuf.svg) ![](https://img.shields.io/crates/l/protobuf.svg)

```
![](https://img.shields.io/crates/v/protobuf.svg)
![](https://img.shields.io/crates/l/protobuf.svg)
```

**Comment by stepancheg** [comment]
@borntyping Added those badges. Thanks!

Unfortunately, styles of badges from crates.io and from travis-ci are different.

**Comment by borntyping** [comment]
[Shields.io](http://shields.io/) also has badges for Travis, so they will all look the same :)

![](https://img.shields.io/travis/stepancheg/rust-protobuf.svg)

`![](https://img.shields.io/travis/stepancheg/rust-protobuf.svg)`

**Comment by stepancheg** [comment]
Changed travis-ci to shields. Thanks again!
