### ISSUE TITLE
Error compiling with rust 1.0

### ISSUE THREAD

**Issue by phifty** [stepancheg/rust-protobuf#109]
.../rust-protobuf-7a0a851bef232540/master/src/lib/stream.rs:2:5: 2:18 error: unresolved import `std::num::Int`. There is no `Int` in `std::num`
.../rust-protobuf-7a0a851bef232540/master/src/lib/stream.rs:2 use std::num::Int;
                                                                                                ^~~~~~~~~~~~~
.../rust-protobuf-7a0a851bef232540/master/src/lib/rt.rs:4:5: 4:32 error: unresolved import `std::iter::AdditiveIterator`. There is no `AdditiveIterator` in `std::iter`
.../rust-protobuf-7a0a851bef232540/master/src/lib/rt.rs:4 use std::iter::AdditiveIterator;

**Comment by borntyping** [comment]
It looks like you might be using an older version of the code. The latest release and commit don't include those lines.

**Comment by stepancheg** [comment]
Please use latest protobuf, and reopen the issue if something is still wrong.
