### ISSUE TITLE
Cannot include generated code

### ISSUE THREAD

**Issue by xitep** [stepancheg/rust-protobuf#117]
Hi,

following [cargo's documentation](http://doc.crates.io/build-script.html#case-study:-code-generation) I've tried to generate my protobufs at build time (through a `build.rs` script) and include them in my `main.rs` using:

```
...
mod model {
    include!(concat!(env!("OUT_DIR"), "/model.rs"));
}
...
```

However, the (rustc) compilation then fails with:

```
.../target/debug/build/pubmonitor-42b07ea6e237e2f6/out/model.rs:3:3: 3:4 error: an inner attribute is not permitted in this context
.../target/debug/build/pubmonitor-42b07ea6e237e2f6/out/model.rs:3 #![allow(dead_code)]
                                                                    ^
.../target/debug/build/pubmonitor-42b07ea6e237e2f6/out/model.rs:3:3: 3:4 help: place inner attribute at the top of the module or block
...
```

It seems that module level attributes (e.g. `#![allow(dead_code)]` here) are not allowed in included content. Would there be a way to avoid these in the generated code by turning them into item-level attributes where needed?

Many thanks,
P.

**Comment by stepancheg** [comment]
Why can't you just copy model.rs into source directory, and then include generated file as `mod model;` as regular source file?

**Comment by xitep** [comment]
Well, that's what I'm doing right now. But it feels rather like a a workaround to me.

**Comment by WillDignazio** [comment]
I've gotten around this by using a build.rs script that generates the source before the build process. It's a little clunky, but not far off from what other large projects do.

**Comment by stepancheg** [comment]
I think rust-protobuf does it properly. But if you need to include generated code in another file, I might suggest stripping module attributes with sed scripts.

**Comment by xitep** [comment]
ok with me, i think that's feasible.

**Comment by mpartel** [comment]
FWIW another dirty workaround is to modify the generated file in your `build.rs` to add a `mod foo {` ... `}` around it. Then it can be included from a file under `src` and doesn't need to be copied there. I think this is a bit better than removing the attributes, which results in build warnings.

**Comment by SirVer** [comment]
Here is [an example](https://github.com/googlecartographer/point_cloud_viewer/blob/bb73289523a3cee8091e9b6547b7b989d0fc61c7/build.rs#L16) of @mpartel idea to wrap the generated proto in `mod proto { ... }` inside the `build.rs` script and how it is then [included in `lib.rs`](https://github.com/googlecartographer/point_cloud_viewer/blob/bb73289523a3cee8091e9b6547b7b989d0fc61c7/src/lib.rs#L45). We do all of this to avoid checking in the `proto.rs` file into source control, instead regenerating it whenever it changes.

@stepancheg It would be really nice if this could be supported more natively. [Prost](https://github.com/danburkert/prost) does this really well with [prost-build](https://github.com/danburkert/prost/tree/master/prost-build).

**Comment by aep** [comment]
@SirVer Prost looks unmaintained. Should we somehow standardize that workaround in a crate?

**Comment by stepancheg** [comment]
@SirVer @aep I think this thing can be implemented as part of rust-protobuf codegen.

If you have specific proposal, e. g.

* option (`wrap_in_module`)
* option to push macros to declarations from the top level

please share.

**Comment by stepancheg** [comment]
@aep option to do what exactly?

Not sure why the default is surprising. Could you explain please?

**Comment by aep** [comment]
the wrap_in_module option sounds good to me :)

well it's quite standard to put generated files into OUT_DIR, and the solution is non-obvious.
so it might help to include that in README.md

**Comment by SirVer** [comment]
@aep Rust Tower seems to be betting on Prost, so I guess development will pick up eventually again. https://medium.com/@carllerche/announcing-tower-a-library-for-writing-robust-network-services-with-rust-67273f052c40

**Comment by clintfred** [comment]
I spent a good chunk of the day figuring this out since docs.rs no longer allows files to be written outside of `$OUT_DIR`. I eventually went with @SirVer's workaround. https://github.com/googlecartographer/point_cloud_viewer/blob/440d875f12e32dff6107233f24b5a02cf28776dc/point_viewer_proto_rust/build.rs#L33

@stepancheg I would ask that you reconsider you stance of writing files to the `src/` directory as the official solution as writing to `src/` will block any crates using rust-protobuf from having documentation on docs.rs. 
Or maybe there is a more official solution now and I failed to find it? If that's the case, please point me in the right direction.
