### ISSUE TITLE
Impossible to re-use protobuf instances with repeated fields

### ISSUE THREAD

**Issue by xitep** [stepancheg/rust-protobuf#120]
hello,

i've hit a nasty issue on re-using a protobuf instance (for performance reasons) which i tried to demonstrated here:

  https://github.com/xitep/rust-protobuf-problem/blob/master/src/main.rs#L23

it seems that `::protobuf::RepeatedField::push_default()` is the culprit here, as it correctly puts the new item into the next "free" slot in the underlying vector, but always returns a reference to the "last" slot, which might not always correspond to the slot the newly "pushed" item was placed to. `read_repeated_message_into` then incorrectly populates the wrong message.

unfortunately, i don't feel confident enough to fix this myself :(

**Comment by stepancheg** [comment]
Thanks for the catch and detailed bugreport! Fixed, and pushed version 1.0.1 to crates.io.

**Comment by stepancheg** [comment]
Sorry, did not upload yet, something is broken in cargo.

**Comment by stepancheg** [comment]
Published.

**Comment by xitep** [comment]
Thank you very much for the quick fix!
