### ISSUE TITLE
warning when use clippy

### ISSUE THREAD

**Issue by sbant** [stepancheg/rust-protobuf#133]
I use clippy in my project ( crates.io/crates/clippy )

And get these 3 warnings in generated .rs file:

src\message\proto\ts_ui.rs:108:5: 113:6 warning: explicit lifetimes given in parameter types where they could be elided, #[warn(needless_lifetimes)] on by default
src\message\proto\ts_ui.rs:108     pub fn mut_file_name<'a>(&'a mut self) -> &'a mut ::std::string::String {

src\message\proto\ts_ui.rs:153:47: 153:78 warning: redundant closure found. Consider using `::std::string::String::new` in its place, #[warn(redundant_closure)] on by default
src\message\proto\ts_ui.rs:153         self.class_name.take().unwrap_or_else(|| ::std::string::String::new())

src\message\proto\ts_ui.rs:247:96: 247:130 warning: `"unexpected wire type".to_owned()` is faster, #[warn(str_to_string)] on by default
src\message\proto\ts_ui.rs:247                         return ::std::result::Result::Err(::protobuf::ProtobufError::WireError("unexpected wire type".to_string()));

**Comment by ngaut** [comment]
Hi, @Stebalien : 
I still got lots of warnings.

src/proto/kvrpcpb.rs:2255:51: 2255:77 warning: redundant closure found, #[warn(redundant_closure)] on by default
src/proto/kvrpcpb.rs:2255         self.cmd_commit_req.take().unwrap_or_else(|| CmdCommitRequest::new())
                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/proto/kvrpcpb.rs:2255:51: 2255:77 help: remove closure as shown:
src/proto/kvrpcpb.rs:             self.cmd_commit_req.take().unwrap_or_else(CmdCommitRequest::new)
src/proto/kvrpcpb.rs:2255:51: 2255:77 help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#redundant_closure
src/proto/kvrpcpb.rs:2258:5: 2260:6 warning: explicit lifetimes given in parameter types where they could be elided, #[warn(needless_lifetimes)] on by default
src/proto/kvrpcpb.rs:2258     pub fn get_cmd_commit_req<'a>(&'a self) -> &'a CmdCommitRequest {
src/proto/kvrpcpb.rs:2259         self.cmd_commit_req.as_ref().unwrap_or_else(|| CmdCommitRequest::default_instance())
src/proto/kvrpcpb.rs:2260     }
src/proto/kvrpcpb.rs:2258:5: 2260:6 help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#needless_lifetimes
src/proto/kvrpcpb.rs:2515:27: 2515:29 warning: this lifetime isn't used in the function definition, #[warn(unused_lifetimes)] on by default
src/proto/kvrpcpb.rs:2515     pub fn get_field_type<'a>(&self) -> MessageType {

Please take a look, Feel free to ping me if you need proto files. Thanks!

**Comment by Stebalien** [comment]
@ngaut I think you meant to @ someone else.

**Comment by ngaut** [comment]
sorry for typo, @stepancheg Please take a look.

**Comment by stepancheg** [comment]
I turned off all clippy warnings in generated code.
