### ISSUE TITLE
Mapping generated types to int and vice versa?

### ISSUE THREAD

**Issue by wrell** [stepancheg/rust-protobuf#134]
I'm trying to implement a client for a server which uses protobuf. The protocol requires a `packet_id` byte, followed by the packet length and protobuf data. I need to somehow map the `packet_id` field to the generated corresponding types in my message handling code, as well as be able to transform the types to their corresponding id value when sending data. How would I go about doing this using this library?

**Comment by stepancheg** [comment]
Protobuf library itself cannot do it. But you can do it youself somewhat like that:

```
let mut is: CodedInputStream = ...
loop {
  match (is.read_raw_byte()) {
    10 => {
        let msg: MyMessageForType10 = is.read_message().unwrap();
        handle_message_10(msg);
    }
    ...
  }
}
```
