### ISSUE TITLE
Did you write first descriptor.rs and plugin.rs by your hand?

### ISSUE THREAD

**Issue by hicqu** [stepancheg/rust-protobuf#136]
Hi, Stepancheg. I'm very intresting on your project and reading source code now. I see the head in descriptor.rs, "this file is generated, don't edit this". But generating this file needs to compile lib/codegen.rs, which depends on descriptor.rs. So, did you write the first version of these two file by your hand, or there is another way to generate them? I think figuring out that is helpful for understanding source code, so could you reply me? Thank you very much.

**Comment by stepancheg** [comment]
Hi,

Yes, basically, first version of rust-protobuf has hand-written very small subset of descriptor.rs, which was later properly regenerated.

Sorry for late reply.
