### ISSUE TITLE
Double-quotes not escaped in debug output for bytes

### ISSUE THREAD

**Issue by robn** [stepancheg/rust-protobuf#139]
Given this message definition:

```protobuf
message foo {
    required bytes bar = 1;
}
```

inserting a quote char into the field:

```rust
fn main() {
    let mut t = test::foo::new();
    let mut v = vec!();
    v.extend(b"abc\"def".iter().cloned());
    t.set_bar(v);
    println!("{:?}", t);
}
```

yields:

```
bar: "abc"def"
```

I know its not a big deal given its intended as debugging output, but it did make writing an external pretty-printer especially difficult.

(even better would be to output `bytes` fields as something that looks like a slice literal eg `[0x61,0x62,0x63,0x22,0x64,0x65,0x66]`)

**Comment by stepancheg** [comment]
Fixed.

`{:?}` output is compatible with protobuf text format (for example, you can print message to text in Rust, and parse it from text in Java). So bytes should not be printed as `[0x61,0x62,0x63,0x22,0x64,0x65,0x66]`.

However, I think current behavior, that `Debug` outputs protobuf text format is probably incorrect. `Debug` could be similar to default rust `Debug` implementation, and protobuf text format could be accessible using `Display` trait.

**Comment by robn** [comment]
Thanks for the quick fix!

Your suggestion for `Display` vs `Debug` sounds good, and would make debugging on my current project easier, but no urgency from me.
