### ISSUE TITLE
Decode bytes to message

### ISSUE THREAD

**Issue by dmgcodevil** [stepancheg/rust-protobuf#144]
Hi, I've generated rust code using the aproach documented on main page.
  
```
let payload = msg_payload_part.as_str().unwrap();
 let bytes = decode_hex(&payload);
let parsed = parse_from_bytes::<Status>(&bytes).unwrap();
```

But I'm gettign this error:

the trait `protobuf::core::Message` is not implemented for the type `Status`

I took a look at the source code for Status message and found this:

```
impl ::protobuf::MessageStatic for Status {
...
}
```

So, what's the problem, why code doesn't compile ?

Thanks

**Comment by stepancheg** [comment]
Could you please post full (or, preferably, minimal) proto file, generated file, and full error?

**Comment by dmgcodevil** [comment]
I found error, it was my goof, thanks
