### ISSUE TITLE
Panics when reading a stream of objects, probably when pos overflows uint32

### ISSUE THREAD

**Issue by fulmicoton** [stepancheg/rust-protobuf#152]
I am reading a stream of protobuf object using the "parse_length_delimited_from" function.
Everything works fine for a while, and panics with the following message.

`thread '<main>' panicked at 'assertion failed: self.pos <= self.current_limit', /home/paul/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/protobuf-1.0.18/src/lib/stream.rs:242`

I then started to print out the pos , and the last position before the panic happens is 4294912861

**Comment by fulmicoton** [comment]
After reading a bit of the code, it seems like the library is by design limited by u32 integers.

**Comment by stepancheg** [comment]
Do you read multiple messages from the same stream?

For that case, library should explicitly check for overflows, and provide smth like `reset_counters` function (which C++ protobuf has).

**Comment by fulmicoton** [comment]
> Do you read multiple messages from the same stream?

Yes.

> For that case, library should explicitly check for overflows, and provide smth like reset_counters function (which C++ protobuf has).

I am not sure I understand what is done currently nor what should actually be done.
pos could return a `Wrapper<u64>`

**Comment by fulmicoton** [comment]
I think this is a non-issue, and what i was experiencing was #208 .
