### ISSUE TITLE
Expose enum for `one_of` fields

### ISSUE THREAD

**Issue by luser** [stepancheg/rust-protobuf#153]
I see that rust-protobuf maps protobuf `one_of` fields to a Rust enum internally, which makes sense. However, it doesn't expose the enum publicly from the `Message` type, so you can't write nice `match`-using code for it, and have to resort to chained `if`-statements.

It'd be nice to be able to write something like:

``` protobuf
message A {
  one_of things {
    string s = 1;
    int32 i = 2;
  }
}
```

``` rust
fn foo(a : A) {
  match a.get_things() {
    A_oneof_things::s(s) => {},
    A_oneof_things::i(i) => {},
  } 
}
```

**Comment by thijsc** [comment]
I needed this to and ended up making the value field public in my generated code. Would of course be nice if this was officially supported :-).

**Comment by DrRibosome** [comment]
Ran into the same issue wanting to simply switch on the generated enum - has there been any progress or workaround for this other than simply editing the generated code and adding a "pub"?

**Comment by kkimdev** [comment]
Ran into the same issue.  Can we make the field just public?

**Comment by thijsc** [comment]
That would be a pretty good solution.

Actually I think there should probably just be an accessor function that returns the enum instead of the current accessor for the variants. It would be an anti-pattern no to `match` on the field.

**Comment by stepancheg** [comment]
Well, this request is popular.

However, I'm not sure what API should look like. I have two concerns:

1. Efficiency.

All field allocations *except oneof* in rust-protobuf can be reused: when you call `clear` on the message, fields are marked as unset, but keep allocated memory. So streaming message processing could be much faster.

2. backward compatibility.

Once it becomes public, it won't be possible to change the API (for example, to make it more efficient).

I agree that we should probably just make field public. However, at least initially I think it would be better to have an option to expose the field similarly to [how they do it in gogoprotobuf](https://github.com/gogo/protobuf/blob/master/extensions.md), e. g.

```
option (rust.expose_oneof_enum) = true;
```

And hide oneof enum by default.

So if that's OK, pull request is welcome, or I do it myself some time later.

**Comment by stepancheg** [comment]
OK, now (in master) rust-protobuf have an [option](https://github.com/stepancheg/rust-protobuf/blob/master/src/test/v2/test_oneof_expose_pb.proto) to make oneof field public.

Not sure if option should be on by default.

**Comment by thijsc** [comment]
I'd actually argue that the option should be the only default way to access the field. An enum maps perfectly onto a oneof. Exposing it like that is much more foolproof.

**Comment by stepancheg** [comment]
> An enum maps perfectly onto a oneof.

It is not that simple. Another option for oneof field is to generate it as `oo: SingularField<Oo>` instead of `oo: Option<Oo>`. Former version would be more efficient when message is cleared and reused to parse data again, because of avoided malloc/free.

**Comment by thijsc** [comment]
You mean that mapping it only as an option would make it harder to reuse allocations? I think conceptually it makes a lot of sense to access it as an enum.

**Comment by stepancheg** [comment]
I mean when option is not enabled by default, behavior is not "stable", and type of field could be changed later. Or enabled by default some time later if this option would popular.

**Comment by thijsc** [comment]
I think we look at this from exactly the opposite direction :-). In my mind there maybe even't shouldn't be getters for the separate states of the field. The Rust way would be to have the type system be as foolproof as possible, that would mean matching here I think.

**Comment by thijsc** [comment]
For our use case the solution in master is not great. We need to add this Rust-specific to the proto file to enable behaviour that in my mind should be the default. Would you be open to a pull that adds a getter for the oneof field by default?

**Comment by stepancheg** [comment]
>  need to add this Rust-specific option to the proto file to enable behaviour that in my mind should be the default.

There are three options:

1. Before invoking protoc you can copy `.proto` file to temporary, patch it, and then invoke `protoc`. This is a recommended way by protobuf author AFAIR.

2. Patch `protoc-rust` library to specify codegen options programmatically. I'm going to do that myself anyway, but if you wish to do it yourself, PR is welcome.

3. Make it public by default (see comments below).

> Would you be open to a pull that adds a getter for the oneof field by default?

There are concern about backward compatibility issues (for example, I want to rename these oneof types to follow rust naming conventions). Becuase of that I'm not completely ready for such changes.

But probably rust-protobuf should stop maintaining strict backward compatibility. I don't know.

**Comment by thijsc** [comment]
Have you come to any new insights on enabling this by default? We've been manually making our field public for a while now, thought I'd see if I could make the jump. Had some trouble with the option:

```
file.proto:4:8: Option "(rustproto.expose_oneof_all)" unknown.
```

Is this still supposed to work?

**Comment by stepancheg** [comment]
@thijsc 

> Is this still supposed to work?

You need to include `rustproto.proto` to make it work. Sorry for late answer.

In new (unreleased) version of rust-protobuf these options could be specified programmatically when invoking e. g. `protoc_rust::run(Args { ..., Customize { expose_oneof: Some(true) ... })`.

But anyway, FYI, oneofs are [public from next release of rust-protobuf](https://github.com/stepancheg/rust-protobuf/commit/8bd911e2ea0d4461580105209ae11d9d3ec21fd0).

**Comment by thijsc** [comment]
Great. As far as I'n concerned we can close this issue then, public enum is fine.
