### ISSUE TITLE
Publish generated rustdoc

### ISSUE THREAD

**Issue by luser** [stepancheg/rust-protobuf#156]
It would be great if you could set up rustdoc generation in your CI. The API is just complex enough that I wound up generating it locally and also referencing the source quite a bit.

I followed the directions in this repo which don't require handing out a "push to any of my repos" token to Travis, but does require you to have a separate docs repo:
https://github.com/kmcallister/travis-doc-upload/blob/master/README.md

**Comment by wkoomson** [comment]
Is there any sort of documentation? as someone who is new to both Rust and Protobuf I have no intuitve sense of how to use this, or what the api is beyond generating the .rs from proto. I tried generating by running `cargo doc` on the sources, but the genereated documentation didn't offer much help. If I can get a sense of what it is, I'd love to help expand the documentation

**Comment by stepancheg** [comment]
Now we have docs.rs. I think it should be enough. dacb236b51a7494d20975a2a0145c6b72f6b654b
