### ISSUE TITLE
Idea: re-use protobuf's unittest schemas

### ISSUE THREAD

**Issue by dflemstr** [stepancheg/rust-protobuf#163]
There are schemas available in the core protobuf repository that cover most of the corner cases in the protobuf compiler.  They could be used for integration testing this library.

Here's one such schema file: https://github.com/google/protobuf/blob/master/src/google/protobuf/unittest.proto

**Comment by stepancheg** [comment]
Included most of schema files from google: 07f390b5d181f154a83432b6c40311c1560c25c9.

**Comment by stepancheg** [comment]
Now all protobuf schema files are included in protobuf codegen unittest: rust-protobuf generates and compiles code from these schemas.
