### ISSUE TITLE
Incorrect varint length calculation for negative ints 

### ISSUE THREAD

**Issue by dvvc** [stepancheg/rust-protobuf#168]
When calculating the size of a varint for signed integers, the number is casted to unsigned. When the number is negative, this causes `std::T::MAX + 1` [to be added to it](http://rustbyexample.com/cast.html). However, a negative varint should have the same length as its absolute value.

The problem can be reproduced like this:
``` 
message Foo {
        required sint32 bar = 1;
}
```
And then,
```rust
let mut x = test::Foo::new();
x.set_bar(-1);
println!("BYTES: {:?}",x.write_to_bytes().unwrap());  // Outputs [8, 1] (Size: 2)
println!("COMPUTED SIZE: {:?}", x.compute_size()); // Outputs 11!
```
The solution is to use the number's absolute value when calculating the varint size, instead of casting it to an unsigned.

**Comment by dvvc** [comment]
Submitted #169 as a possible solution.

**Comment by dvvc** [comment]
I just realized that this only applies to sint* values, not int*. What is really happening is the sint data is being serialized correctly, but the size of the message is calculated as if it was an int (which is less efficient when encoding negative numbers).

That also means my patch is not good, because it breaks ints (as the travis result shows :) I'm looking into a fix for that.

**Comment by stepancheg** [comment]
Fixed. Thank you for the bugreport!
