### ISSUE TITLE
ListFields?

### ISSUE THREAD

**Issue by photex** [stepancheg/rust-protobuf#170]
Howdy!

I was looking for an analog to [ListFields](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Reflection.ListFields.details).
From what I can tell with rust-protobuf I have to iterate over every field descriptor and check if a message has that field set using the `FieldDescriptor::has_field` method.

Am I just missing something?

**Comment by stepancheg** [comment]
If I understand you correctly, you are asking about protobuf reflection.

It is implemented, it is actually used for formatting message to string by rust-protobuf itself, have a look at [the implementation in text_format.rs](https://github.com/stepancheg/rust-protobuf/blob/95dcc07544fb83fd725c0d0af0b09e2d872fd39d/src/lib/text_format.rs#L163).

Probably it is not very convenient to use, suggestions are welcome!

Also note, that at the moment reflection is implemented only for reading, but not for modification.

**Comment by photex** [comment]
Yep, I was speaking about reflection. I looked at the C++ protobuf implementation and that method is doing almost exactly was I'm doing in my app so I think I'm all set. :)
The key for me is to be able to know exactly what is set vs default and so far 'has_field' does the trick. I hope that is the intended usage! :)

**Comment by stepancheg** [comment]
Note that protobuf 3 has no field presence bit. So rust-protobuf will remove `has_` methods for files generated from protos with `syntax = "proto3"` (it is not implemented yet).

**Comment by photex** [comment]
https://github.com/google/protobuf/blob/master/src/google/protobuf/generated_message_reflection.cc#L1051

https://github.com/google/protobuf/blob/master/src/google/protobuf/generated_message_reflection.cc#L2013

Leads me to think they intend to keep the ability to support `has_`-like methods in the reflection api even without the bits.
Not being able to check if fields were set would break so much code out there (though, perhaps not any rust projects).

**Comment by photex** [comment]
Although, my design so far is based on another system that is in production, perhaps I need to reevaluate the approach and avoid reflection.

**Comment by hicqu** [comment]
Now, maybe we can use oneof?
@photex @stepancheg
