### ISSUE TITLE
Add support for futures-rs

### ISSUE THREAD

**Issue by oberien** [stepancheg/rust-protobuf#172]
Using this library in a server environment working with [futures-rs](https://github.com/alexcrichton/futures-rs) would be amazing.

**Comment by stepancheg** [comment]
What do you mean by working with futures-rs for protobuf?

I'm currently working on gRPC implementation in rust: https://github.com/stepancheg/grpc-rust.

**Comment by oberien** [comment]
Currently `Coded{Input,Output}Stream` are based on blocking IO. Therefore I need to read data asynchronously into a buffer before converting it into the according message. It would be nice to be able to use `Coded{Input,Output}Stream` directly with futures without needing to manually reading data into a buffer.

**Comment by stepancheg** [comment]
That would make protobuf parser and serializer enormously complex and hard to implement. Neither C++ nor Java protobuf implementation do it. So I think rust-protobuf shouldn't try to do it either. Until at least rust implements async/wait.

If your messages are large, you can split them into a sequence of small messages. gRPC protocol supports [streaming](http://www.grpc.io/docs/guides/concepts.html#server-streaming-rpc) of messages, and it is implemented in grpc-rust.
