### ISSUE TITLE
Allow adding elements to repeated fields without needing RepeatedField

### ISSUE THREAD

**Issue by kamalmarhubi** [stepancheg/rust-protobuf#177]
Right now the generated code for a repeated field only provides `mut_field_name` as a way to modify the repeated field. Since an incredibly common use case is to add an element, this should be streamlined.

Eg, for a simple message like

```proto
message Foo {
    bool initialized = 1;
}
message FooBar {
    repeated Foo foo = 1;
}
```

To add a foo, you currently need to write something like

```rust
// msg: &mut FooBar is in scope
let foo = Foo::new();
foo.set_initialized(true);
msg.mut_foo().push(foo);
```

With an API more like that in C++, this could be rewritten as

```rust
// msg: &mut FooBar is in scope
let foo = msg::add_foo();
foo.set_initialized(true);
```

The [C++ generated code](https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#repeatedmessage) has `Foo* add_foo()` and `Foo* mutable_foo(int index)` methods for message-typed fields, and similar by-value operations for primitives.

In Rust, I image the interface would be that a field like

```proto
repeated Foo foo = 1;
```

results in a method

```rust
fn add_foo(&mut self) -> &mut Foo;
```

**Comment by stepancheg** [comment]
Currently, it can be done like this:

```
foo_bar.mut_foo().push_default().set_initialized(true);
```

Isn't it sufficient?

I'm against adding `add_foo` function, because it significantly increases generated code side increasing compilation time, IDE analyze time and so on.

**Comment by stepancheg** [comment]
Closing for now, please reopen if you think it is not enough.
