### ISSUE TITLE
Allow method chaining for setters

### ISSUE THREAD

**Issue by kamalmarhubi** [stepancheg/rust-protobuf#178]
Given a message like

```proto
message Foo {
    double bar = 1;
    bool baz = 2;
}
```

right now we have to write

```rust
let mut foo = Foo::new();
foo.set_bar(100.0);
foo.set_baz(true);
```

while it would be nicer to write

```rust
let mut foo = Foo::new();
foo.set_bar(100.0).set_baz(true);
```

Coupled with #177, this would allow adding an element in the example message

```proto
message Foo {
    bool initialized = 1;
}
message FooBar {
    repeated Foo foo = 1;
}
```

to go from

```rust
// msg: &mut FooBar is in scope
let foo = Foo::new();
foo.set_initialized(true);
msg.mut_foo().push(foo);
```

to the much shorter

```rust
// msg: &mut FooBar is in scope
msg.add_foo().set_initialized(true);
```

The API change would be to make all `set_foo` methods return `&mut self`.

**Comment by stepancheg** [comment]
I personally think chained setters are wrong. However, because this request is popular, I think rust-protobuf should probably have an option to generate chained setters.

Also, note that single-liners are possible for your last use case:

```
msg.mut_foo().push_default().set_initialized(true);
```

**Comment by cristicbz** [comment]
My ancient PR #101 tried to add this back in April 2015, but @stepancheg  had strong opinions on chaining back then too :P .

**Comment by wmedrano** [comment]
Is adding`msg.with_foo(true).with_bar(10.0)` , where `with_*` consumes self alright?

**Comment by stepancheg** [comment]
I personally think that chained setters is not a very good think, it's probably OK to have a codegen option to generate chained setters.

**Comment by thomaseizinger** [comment]
Does this mean that you would accept a PR that adds an option to enable `with_XY` methods that consume `self`?

**Comment by stepancheg** [comment]
It it will be option which is off by default, and if pr is with test, then definitely yes. 

I think that chained setters should probably be called with_xx.

**Comment by thomaseizinger** [comment]
Okay, good to hear! I will try to implement that then :)

**Comment by thomaseizinger** [comment]
Unfortunately, I will have to withdraw my offer for implementing that, sorry.

**Comment by melchurchwell** [comment]
dfdcff

**Comment by stepancheg** [comment]
Closing due to old age.
