### ISSUE TITLE
RPC support

### ISSUE THREAD

**Issue by pronebird** [stepancheg/rust-protobuf#183]
Would be great to add Service/RPC generator

**Comment by stepancheg** [comment]
It is useless without RPC implementation, and there's incomplete gRPC implementation [here](https://github.com/stepancheg/grpc-rust).

**Comment by pronebird** [comment]
Would be useful to add a Trait for service at least so one could implement methods and wire it up with RPC channel. This is what I currently write manually, but I think it would be great first step!
