### ISSUE TITLE
Could make fields in struct are pub?

### ISSUE THREAD

**Issue by hicqu** [stepancheg/rust-protobuf#184]
Hi, here is an generated code example: 
```
struct Message {
    field: ::protobuf::SingleField<usize>,
    ......
}
```
could we make field pub for accessing that in other modules? Sometimes I don't want a default value returned by `message.get_field()`, I just want to get a reference by `message.field.as_ref()`.
do you think that's a good idea?

**Comment by stepancheg** [comment]
Actually, in master fields are `pub` if `syntax=proto3` is used (and field type is `u64` instead of SingularField<u64>`).

**Comment by hicqu** [comment]
Got it. Thank you! 👍
