### ISSUE TITLE
unnecessary buffer in CodedOutputStream

### ISSUE THREAD

**Issue by siddontang** [stepancheg/rust-protobuf#186]
Hi @stepancheg 

I note that CodedOutputStream uses a buffer to cache write first, this may be good for some Write like TcpStream or File, but I think it is not necessary for Vector or other Write which already supports memory buffer. 

Maybe we can remove the buffer and  only use Write here, if user wants to encode the protobuf to a TcpStream or File, he can use BufWrite outside manually.

**Comment by stepancheg** [comment]
Yes, that's good idea. Similar thing is already implemented for `CodedInputStream`, `CodedOutputStream` should be implemented the same way.

**Comment by siddontang** [comment]
Hi @stepancheg 

I do a benchmark here https://gist.github.com/siddontang/ef39b619b69376533eb5393b2d435feb

The result looks very strange to me:

```
test tests::bench_buffer          ... bench:          45 ns/iter (+/- 8)
test tests::bench_buffer_bytes    ... bench:          47 ns/iter (+/- 14)
test tests::bench_no_buffer       ... bench:           0 ns/iter (+/- 0)
test tests::bench_no_buffer_bytes ... bench:           0 ns/iter (+/- 0)
```

Maybe you can bench it in your computer. If the result is correct, I think we should re-consider the trade-off between the  8K and the dynamic Write call.

**Comment by overvenus** [comment]
Hello @siddontang,

`0ns` is caused by:

> benchmarks compiled with optimizations activated can be dramatically changed by the optimizer so that the benchmark is no longer benchmarking what one expects.

We should call `test::black_box`.

> `test::black_box` function, which is an opaque "black box" to the optimizer and so forces it to consider any argument as used.

The result on my dated machine:

```
test tests::bench_buffer          ... bench:         111 ns/iter (+/- 2)
test tests::bench_buffer_bytes    ... bench:         120 ns/iter (+/- 1)
test tests::bench_no_buffer       ... bench:          50 ns/iter (+/- 0)
test tests::bench_no_buffer_bytes ... bench:          54 ns/iter (+/- 0)
``` 

-------------------------

Updated benchmark.

```rust
    #[bench]
    fn bench_no_buffer(b: &mut Bencher) {
        b.iter(|| {
            let n = test::black_box(OUTPUT_STREAM_BUFFER_SIZE);
            let mut v = Vec::with_capacity(n);
            let mut os = NoBufferCodedOutputStream::new(&mut v);
            no_buffer_write_byte(&mut os);
        });
    }

    #[bench]
    fn bench_no_buffer_bytes(b: &mut Bencher) {
        b.iter(|| {
            let n = test::black_box(OUTPUT_STREAM_BUFFER_SIZE);
            let mut v = Vec::with_capacity(n);
            let mut os = NoBufferCodedOutputStream::new(&mut v);
            no_buffer_write_bytes(&mut os);
        });
    }
```

**Comment by stepancheg** [comment]
`CodedOutputStream` created with `::vec` constructor no longer does unnecessary buffering: 5773985563e7ceb5efca1ffb3ea3421f79e83356.

[This comment](https://github.com/stepancheg/rust-protobuf/pull/194#issuecomment-274768135) has some explanations.

**Comment by danburkert** [comment]
@stepancheg I think this is still a valid issue.  `CodedOutputStream` is still doing internal buffering to the `Vec`.

**Comment by stepancheg** [comment]
>  CodedOutputStream is still doing internal buffering to the Vec.

No, it doesn't. Please look at the sources closely.
