### ISSUE TITLE
How to debug "unexpected wire type WireTypeFixed32"

### ISSUE THREAD

**Issue by whiplash** [stepancheg/rust-protobuf#191]
Hi,
I'm trying to read a kafka topic which contains values that have been serialised using protobuf.

I successfully managed to generate rust mods and all... and come out with

```
let x: &[u8] = m.value; // this comes from kafka-rust api... basically for each message you have m.key and m.value
let parsed = parse_from_bytes::<Thingie>(x).unwrap();
```

This compiles just fine (and I'm not really handling the `Result` I know...)

A runtime I get `WireError("unexpected wire type WireTypeFixed32")'`

How could I check what's going on?

**Comment by stepancheg** [comment]
Well, I can help if you attach serialized data and `.proto` file.

However, rust-protobuf could provide better diagnostic message, in particular, it could tell a position of error and message being parsed.

**Comment by whiplash** [comment]
Ok. For now I can just let you see the complete error message

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("unexpected wire type WireTypeFixed32")', ../src/libcore/result.rs:837
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by whiplash** [comment]
Solved! I was using the wrong proto. Sorry about this!
