### ISSUE TITLE
import "google/protobuf/empty.proto"; ?

### ISSUE THREAD

**Issue by kkimdev** [stepancheg/rust-protobuf#197]
I was trying to use `google.protobuf.Empty`

```
import "google/protobuf/empty.proto";

message Msg {
    google.protobuf.Empty empty = 1
}
```

But then I noticed the generated .rs contains `empty: ::protobuf::SingularPtrField<super::empty::Empty>,` .  Is this correct? and how should I resolve `super::` scope ?

**Comment by stepancheg** [comment]
Support of well-known-types added in 653f8548f1817688c8816686728ce312d3f99168. Thank you for the bugreport.

(By the way, you could simply compile `empty.proto` yourself, sorry I didn't respond before).
