### ISSUE TITLE
struct keyword

### ISSUE THREAD

**Issue by crackcomm** [stepancheg/rust-protobuf#202]
How would you use or generate a code for [struct](https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto) to omit an error:

```
error: expected identifier, found keyword `struct`
 --> src/lib.rs:2:9
  |
2 | pub mod struct;
  |         ^^^^^^
```

**Comment by jamesluke** [comment]
I ran into this myself trying to produce gRPC bindings for Google Datastore.  As it stands, any <name>.proto file where <name> is a rust keyword will produce problems.  I'm not sure if this fixes all instances where mangling is required to avoid keywords, but altering `proto_path_to_rust_mod()` to mangle keywords (e.g., struct -> _struct, type -> _type) cures the problem in my case.  

```rust
  let without_suffix_mangled =
    if rust::is_rust_keyword(without_suffix) {
      format!("_{}", without_suffix)
    } else {
      without_suffix.to_owned()
    };
  without_suffix_mangled.chars().enumerate().map(|(i, c)| {
```

I would make a pull request, but I highly doubt this is idiomatic rust code, nor do I know if it is enough to solve the problem completely.  I'll leave it to stepancheg or some other industrious individual to fix it properly.

**Comment by stepancheg** [comment]
Committed almost the same code you have provided. Thanks!
