### ISSUE TITLE
help: need support old rustc version 

### ISSUE THREAD

**Issue by siddontang** [stepancheg/rust-protobuf#203]
Hi @stepancheg

Now protobuf uses `?` instead of `try!`, but we can't compile it with the rust version nightly 2016-08-06, and now we can't upgrade rust because of the core dump https://github.com/rust-lang/rust/issues/37105

Can you add `#![feature(question_mark)]` so that we can use the latest protobuf in TiKV, or we can send you a PR. 

Btw, the grpc has the same problem now.

**Comment by stepancheg** [comment]
If `#![feature(question_mark)]` compatible with stable rust? (I thought `feature` works only on nightlies). If it is compatible, please send a PR.

**Comment by siddontang** [comment]
I will close this issue because we determine to update the rust version.
