### ISSUE TITLE
Read a certain number of bits (not bytes) ?

### ISSUE THREAD

**Issue by gaultier** [stepancheg/rust-protobuf#204]
Hello, I have been using this crate and it has been very enjoyable.
I have however stumbled upon a case where I would need to read only 6 bits, not a full byte, of a `CodedInputStream`. 
It seems it is feasible by accessing the `source` field, as it is done in the method `read_raw_varint64` but this field is private. Is there another way of doing this? 

Thank you very much for your answer!

**Comment by stepancheg** [comment]
You cannot read only 6 bits, because `CodedInputStream` position is in bytes, not in bits.

`read_raw_varint64` could be made public, if you really need it.

**Comment by gaultier** [comment]
That's what I thought as well.
I ended up making a basic implementation of a bitstream for this specific case, and using the CodedInputStream in the other cases.
Thank you for your answer and your work on the library.
