### ISSUE TITLE
borrowing_merge_from_bytes

### ISSUE THREAD

**Issue by scottlamb** [stepancheg/rust-protobuf#205]
I propose the ability to parse/merge a `&'a [u8]` into a `MyMessage<'a>` that represents `string` and `bytes` fields as `Cow<'a, &str>` and `Cow<'a, [u8]>`, respectively, to borrow from the original slice on initial parse but allow allocation if the value is subsequently changed. This would avoid some copying and heap allocation.

I was just looking for this feature when looking at parsing messages stored in a key/value database ([rocksdb](https://crates.io/crates/rocksdb) or [lmdb](https://crates.io/crates/lmdb)).

The `Cow` representation could be generated or not on a field-by-field basis with a protobuf annotation, similar to the `[ctype=STRING_PIECE]` in the Google protobuf code. (This is probably better than doing it for all fields, which I think would involve a little more memory overhead and extra branches. or toggling it on a message-by-message basis, or having a duplicate message struct for this purpose.)

The parsing could be done through a new `borrowing_merge_from_bytes` method; `merge_from` would keep its current behavior of always copying/allocating.

**Comment by siddontang** [comment]
We need this feature heavily too. :-)

**Comment by stepancheg** [comment]
I agreed, I think this feature is important. I cannot currently implement it myself, but I hope to get to it in the future.

I think rust-protobuf should have codegeneration option to enable cow fields instead of regular String fields (I'm currently not sure Cow should be enabled by default). Or rust-protobuf should probably just use `[ctype=STRING_PIECE]` option.

**Comment by stepancheg** [comment]
There's also an option to use refcounted data structure like `Bytes` [from bytes crate](https://github.com/carllerche/bytes/blob/master/src/bytes.rs#L103). It would be somewhat slower, but API would be much simpler and better suitable for e. g. async processing.

**Comment by stepancheg** [comment]
Created a separate issue to implement support of `Bytes`: #213.

**Comment by stepancheg** [comment]
OK, `Bytes` with slicing is implemented. Please reopen the issue, if it is still needed.

**Comment by scottlamb** [comment]
For me, yes, it's still desired. (And I might send a pull request...some day...lots of other things to fix in my software.)

The reading from db case is a good example; rocksdb and lmdb are wrappers around C APIs, so they definitely don't use the bytes crate. All that's available is a `&'a [u8]`; I want to borrow from that and ensure I'm no longer using it when the lifetime is no longer valid.

**Comment by scottlamb** [comment]
I don't think I have permissions to reopen the issue, though.

**Comment by stepancheg** [comment]
> All that's available is a &'a [u8]

Well, at least you can copy it to `Bytes` and parse it then.

Converting all fields to `Cow` would require each message to be parameterized by lifetime, I think that's not very ergonomic (BTW, this is what [quick-protobuf](https://github.com/tafia/quick-protobuf) does).

So, to support cow-types, rust-protobuf needs to either:

* make all messages parameterized by lifetime
* generate additional messages parameterized by lifetime
* make codegen option to generate messages with lifetimes

I don't know what would be the best.

**Comment by scottlamb** [comment]
I'd like to avoid that first malloc+copy. In my application, I only need the proto briefly, so being able to clone it or whatever without further copying isn't something I care about.

Thanks for the pointer to quick-protobuf; I'll have to check it out.

Yeah, I was suggesting field-by-field codegen options; the lifetime annotation on the message struct would be necessary if it contains any such fields.

**Comment by stepancheg** [comment]
Closing due to old age.
