### ISSUE TITLE
assertion failure in buf_read_iter.rs

### ISSUE THREAD

**Issue by chefsalim** [stepancheg/rust-protobuf#207]
I don't have a simple repro case for this unfortunately. However, with version 1.2.1 I am seeing the following assertion failure when deserializing a message with parse_from_bytes.

thread 'main' panicked at 'assertion failed: amt < self.buf.len() - self.pos', /cargo-cache/registry/src/github.com-1ecc6299db9ec823/protobuf-1.2.1/src/lib/buf_read_iter.rs:96

Rolling back to version 1.1.0 resolves this issue and everything in the project works as expected. Also, the assertion failure only happens with one particular message (others work fine).

**Comment by fulmicoton** [comment]
duplicated of #208. it should be solved now.
