### ISSUE TITLE
Programmatically compile *.proto files to *.rs

### ISSUE THREAD

**Issue by sevagh** [stepancheg/rust-protobuf#210]
Hello,

I'm a little bit lost with `FileDescriptorSet`, `FileDescriptorProto`, and `CodeGeneratorRequest`.

Using code from this repo I was able to use `parse_from_reader::<FileDescriptorSet>` to convert a `*.fdset` file to `*.rs`.

When trying to skip the `*.fdset` phase and go straight from `*.proto` to `*.rs`, I can't quite understand the relationship between a `FileDescriptorProto` and `FileDescriptorSet` object.

I'm trying to construct a `CodeGeneratorRequest`, is this the correct way to proceed?

**Comment by sevagh** [comment]
The `FileDescriptorSet` object has an internal `RepeatedField<FileDescriptorProto>`: `fn set_file(&mut self, v: RepeatedField<FileDescriptorProto>)`, which is also what a `CodeGeneratorRequest` needs but I can't quite figure out the relationship between a `CodeGeneratorRequest` and `FileDescriptorSet`.

**Comment by stepancheg** [comment]
If I understand you correctly, you want avoid using `protoc` to generate `.rs` files?

Note, rust-protobuf does not have own `.proto` parser. So you need to obtain a list of `FileDescriptorProto` somehow, e. g. by invoking `protoc --descriptor_set_out` which outputs `FileDescriptorSet` message.

Given `FileDescriptorSet` object, you can extract a list of `FileDescriptorProto` and just invoke `codegen::gen`.

`CodeGeneratorRequest` is a message used between `protoc` program and compiler plugin, i. e. `protoc-gen-rust`. You don't need it unless you are writing another compiler plugin.

> I can't quite figure out the relationship between a CodeGeneratorRequest and FileDescriptorSet.

AFAIU these are independent messages.

**Comment by sevagh** [comment]
Thanks.
