### ISSUE TITLE
bytes::Bytes

### ISSUE THREAD

**Issue by stepancheg** [stepancheg/rust-protobuf#213]
An option to generate `bytes` and `string` fields as `bytes::Bytes`.

- [x] proto 2: change `SingularField<Bytes>` to `Option<Bytes>`
- [x] proto 3
- [x] map field

**Comment by stepancheg** [comment]
Waiting for release of `bytes` with `Default` for `Bytes`: https://github.com/carllerche/bytes/commit/37f6cabd96a6200b0b3cb1d743be9c0cf75d1085

**Comment by siddontang** [comment]
Can it be used in production now? @stepancheg

**Comment by stepancheg** [comment]
Not yet.
* it not released
* only proto2 is implemented
* API is not stabilized
* and it is not clear at the moment, if it really helps

**Comment by siddontang** [comment]
Thanks @stepancheg 
In our test, the decoding performance can be increased at lease 2x, so this feature is very useful in production.

**Comment by stepancheg** [comment]
Current benchmark results are:

```
test parse_repeated_huge_bytes     ... bench:      15,442 ns/iter (+/- 1,738)
test parse_repeated_huge_regular   ... bench:     163,835 ns/iter (+/- 54,641)
test parse_repeated_large_bytes    ... bench:      15,975 ns/iter (+/- 5,220)
test parse_repeated_large_regular  ... bench:      28,427 ns/iter (+/- 4,856)
test parse_repeated_medium_bytes   ... bench:      15,346 ns/iter (+/- 2,758)
test parse_repeated_medium_regular ... bench:      16,341 ns/iter (+/- 2,288)
test parse_repeated_small_bytes    ... bench:      14,926 ns/iter (+/- 2,763)
test parse_repeated_small_regular  ... bench:      14,895 ns/iter (+/- 2,718)
```
