### ISSUE TITLE
rust-protobuf-build does not recursively import?

### ISSUE THREAD

**Issue by beamspease** [stepancheg/rust-protobuf#215]
I upgraded the rust-protobuf version used by rust-protobuf-build because cargo was getting stuck in a loop:
https://github.com/beamspease/rust-protobuf-build

However, I keep getting "enum not found by name" and similar messages for things which are imported, as if it isn't correctly recursively importing those files. I'm not sure if it's an issue with rust-protobuf (the panic is happening in codegen::gen) or rust-protobuf-build.

**Comment by stepancheg** [comment]
Could you at please attach `.proto` files here which do not work?

**Comment by stepancheg** [comment]
Please reopen the issue, it problem still exists.

**Comment by beamspease** [comment]
Switched to protoc_rust and the problem doesn't exist anymore. :)
