### ISSUE TITLE
generated code too large when size matters

### ISSUE THREAD

**Issue by king6cong** [stepancheg/rust-protobuf#219]
hi, we use rust-protobuf extensively in our project, but I recently found the generated rust files too large even after compiled. The following is our statistics:

```
2431 lines of *.proto files
89451 lines of generated *.rs files
97M of compiled rlib in debug mode, and 23M in release mode
```

our project will be shipped as SDK in iOS/Android apps, so size matters. 

https://github.com/tafia/quick-protobuf seems to generate less code, but I tried and encountered several errors which I haven't got the time to look into. rust-protobuf is more mature and our code is working on it.

I think we need to look into the size matter and see what can be done :)

**Comment by stepancheg** [comment]
The obvious solution would be avoiding generation of `get_`, `set_`, `has_`, `mut_`, `clear_` functions, and making fields public instead (this is what quick-protobuf does). That will reduce size of generated code a bit.

However, reflective accessor functions need to be preserved though (if that's an issue, let's discuss).

I think I'll impement options some time later.

I think there should be two options to avoid generation of accessors:
* either via extension option (see [rustproto.proto](https://github.com/stepancheg/rust-protobuf/blob/master/proto/rustproto.proto))
* or programmatically if code is generated with [protoc-rust](https://github.com/stepancheg/rust-protobuf/tree/master/protoc-rust)

**Comment by miedzinski** [comment]
+1 for public fields!

**Comment by king6cong** [comment]
Looking forward for this 👍

**Comment by stepancheg** [comment]
Do you use protobuf with syntax 2 or syntax 3?

**Comment by king6cong** [comment]
@stepancheg syntax 2 is used :)

**Comment by stepancheg** [comment]
The problem with syntax 2 is default values. For example, with field

```
optional int32 int32_field = 3               [default =  3];
```

Should it generate getter? And should it generate getter when there is no default value in the next field?

**Comment by king6cong** [comment]
If there is no getter, I guess we can use fields directly with something like this:

enum OptionWithDefault<V, D> {
   Some(V),
   Default(D),
}

**Comment by stepancheg** [comment]
So when message is created, field is initialized with `OptionWithDefault::Default(3)`.

That's an interesting idea.

I see one drawback: with such implementaion it is not possible for user to clear field resetting it to default value.

**Comment by king6cong** [comment]
struct OptionWithDefault<T> {
    value: Option<T>,
    default: T,
}

Maybe this will fit the resetting use case?

**Comment by stepancheg** [comment]
This creates runtime overhead (unnecessary memory consumption) unfortunately.

**Comment by stepancheg** [comment]
rust-protobuf now has two options: `generate_accessors` and `generate_getter`.

`generate_accessors` option when set to `false` disables generation of all accessor functions like `mut_xxx`, `set_xxx` etc. `get_xxx` is kept when `syntax = "proto2"` to obtain field default value.

`generate_getter` set to `false` disables generation of getters even when `syntax = "proto2"`.

Currently, these options are off by default, but probably could be turned on later.

I'm closing issue now. Please comment if it needs to be reopened.
