### ISSUE TITLE
Unmarshal a slice of bytes into a type defined in a .proto file

### ISSUE THREAD

**Issue by adrianbrink** [stepancheg/rust-protobuf#222]
https://github.com/tendermint/abci/blob/master/types/messages.go#L171

In this example I take a slice of bytes that I received from a socket and unmarshal them into a concrete type defined in a .proto file. 

Does rust-protobuf support the same mechanism? If it doesn't my next question is; how do I convert a slice of bytes into an actual type?

**Comment by stepancheg** [comment]
I'm not sure I understand what you request. If you simply need to parse a byte slice as message, you can simply do:

```
let m: MyMessage = protobuf::parse_from_bytes(bytes).expect("parse");
```
