### ISSUE TITLE
Obtain concrete type of an enum

### ISSUE THREAD

**Issue by adrianbrink** [stepancheg/rust-protobuf#223]
I have this compiled protobuf code.
```
#[derive(PartialEq,Clone,Default)]
pub struct Request {
    // message oneof groups
    value: ::std::option::Option<Request_oneof_value>,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

// see codegen.rs for the explanation why impl Sync explicitly
unsafe impl ::std::marker::Sync for Request {}

#[derive(Clone,PartialEq)]
pub enum Request_oneof_value {
    echo(RequestEcho),
    flush(RequestFlush),
    info(RequestInfo),
    set_option(RequestSetOption),
    deliver_tx(RequestDeliverTx),
    check_tx(RequestCheckTx),
    commit(RequestCommit),
    query(RequestQuery),
    init_chain(RequestInitChain),
    begin_block(RequestBeginBlock),
    end_block(RequestEndBlock),
}
```

In my client code I am reading a buffer into the generic `Request` struct. 

How can I obtain the concrete type that my `Request`.

Ideally I would like something like this:
```
    match message.value.unwrap() {
        types::Request_oneof_value::begin_block => {
            println!("begin_block");
        },
        types::Request_oneof_value::check_tx => {
            println!("check_tx");
        },
        types::Request_oneof_value::commit => {
            println!("commit");
        },
        types::Request_oneof_value::deliver_tx => {
            println!("deliver_tx");
        },
        types::Request_oneof_value::echo => {
            println!("echo");
        },
        types::Request_oneof_value::end_block => {
            println!("end_block");
        },
        types::Request_oneof_value::flush => {
            println!("flush");
        },
        types::Request_oneof_value::info => {
            println!("info");
        },
        types::Request_oneof_value::init_chain => {
            println!("init_chain");
        },
        types::Request_oneof_value::query => {
            println!("query");
        },
        types::Request_oneof_value::set_option => {
            println!("set_option");
        }
    }
```

**Comment by stepancheg** [comment]
You need to specify experimental `expose_oneof` option.

(Which should probably be default).

**Comment by adrianbrink** [comment]
How do I do that?

**Comment by stepancheg** [comment]
Look at [example here](https://github.com/stepancheg/rust-protobuf/blob/6c5302c4f605d71d241efce23e13b5458e1433a0/protobuf-test/src/common/v2/test_oneof_expose_pb.proto#L5).

**Comment by adrianbrink** [comment]
How come I have to modify the .proto file? Is there a way to do it without modifying it?

I have this [proto](https://github.com/tendermint/rust-abci/blob/feature/socket_support/types.proto) file and do the decoding [here](https://github.com/tendermint/rust-abci/blob/feature/socket_support/src/socket_server.rs#L37).

My problem though is that the `message` seems to be an empty object (even though it results in `Ok()`) and I am wondering why and how to get to the specific type of `Request`.

**Comment by stepancheg** [comment]
> Is there a way to do it without modifying it?

Not at the moment. But it should be.

However, you could modify your `.proto` in temp directory before invoking `protoc` (explicitly or from `build.rs`).

> My problem though is that the message seems to be an empty object

Message is allowed to be empty, including zero length. How many bytes do you pass to `parse_from_bytes`?

BTW, what you call `varint`, it is not varint in protobuf terms.

**Comment by adrianbrink** [comment]
Thank you.

What is it in protobuf terms?

I am parsing 9 bytes to it.

**Comment by stepancheg** [comment]
Protobuf varint is defined [here](https://developers.google.com/protocol-buffers/docs/encoding#varints).

BTW, is there a description of protocol you are trying to implement?

**Comment by adrianbrink** [comment]
https://github.com/tendermint/abci#socket

**Comment by stepancheg** [comment]
OK, according to [this doc](https://github.com/tendermint/abci), you seem to parse it correctly.

**Comment by stepancheg** [comment]
OK, I got it.

```
let mut message_bytes: Vec<u8> = Vec::with_capacity(message_length as usize);
stream.read_exact(&mut message_bytes);
```

This reads zero bytes, because this is how `read_exact` works. You need to initialize vec like this:

```
let mut message_bytes: Vec<u8> = vec![0; message_length as usize];
```

**Comment by adrianbrink** [comment]
Damn, nice. Thank you very much. It now works and I am getting the correct results.

**Comment by stepancheg** [comment]
You are welcome.

**Comment by eberkund** [comment]
Does this apply to `protoc_rust_grpc` also?

**Comment by stepancheg** [comment]
@eberkund if I understand your question properly, then yes. grpc-rust uses rust-protobuf for codegen.

**Comment by eberkund** [comment]
Sorry, I should have been more clear.

If I want to use the newly exposed "oneof enum" will the recent commit to this repo also affect GRPC?

I tried this but I am still getting private oneof fields.

```toml
[build-dependencies]
# protoc-rust = "1.5"
# protoc-rust-grpc = "0.3"
protoc-rust-grpc ={ git = "https://github.com/stepancheg/grpc-rust", branch = "master" }
protoc-rust = { git = "https://github.com/stepancheg/rust-protobuf", branch = "master" }
```
