### ISSUE TITLE
Ensure an entire protobuffer has arrived?

### ISSUE THREAD

**Issue by valarauca** [stepancheg/rust-protobuf#226]
Passing literally a single byte into the `read_from_bytes::<T>` seems to unconditionally return `Ok(T)`. 

Is there a work around for this to ensure the _entire_ protocol buffer has arrived?

**Comment by stepancheg** [comment]
There's no such thing as "entire protocol buffer", because protocol buffers message must be delimited from outside, it is not self-delimited. 

BTW, it couldn't return Ok for single byte, because protobuf message is either zero length or at least two bytes length.
