### ISSUE TITLE
Write protobuf type to network socket

### ISSUE THREAD

**Issue by adrianbrink** [stepancheg/rust-protobuf#227]
Hi,

[I am running into another problem using the protobufs.](https://github.com/tendermint/rust-abci/blob/feature/socket_support/src/socket_server.rs#L32)

I want to write a `Response` type to a network socket. `Response` is an enum that can have different concrete types.

Do I need to cast it to the concrete type before turning it into `&[u8]`, because it seems to giving me different bytes depending on the choice.

Also, I am implementing the same [encoding](https://github.com/tendermint/go-wire/blob/master/byteslice.go#L9) as in `read_abci_message`, where a message starts with a u8 indicating the size of length of the message, followed by the actual length, followed by the actual message. 

Any help would be appreciated.

**Comment by stepancheg** [comment]
And what is the problem? You can use `Message::write_to_bytes` to serialize to `[u8]`.

**Comment by adrianbrink** [comment]
I am doing that, but for some reason it isn't working.

My question though is whether it is correct to call `write_to_bytes` on the abstract Enum.

**Comment by stepancheg** [comment]
What `Enum` are you talking about?

**Comment by adrianbrink** [comment]
I have an enum that represents multiple different concrete types (https://github.com/tendermint/abci/blob/master/types/types.proto). 

And currently I am calling `write_to_bytes()` on the enum and not on one of its sub-types. I am wondering whether I am supposed to figure out the concrete type before calling `write_to_bytes()`.

**Comment by stepancheg** [comment]
You must be talking about `oneof`. You simply write the message, and protobuf will do the rest.

Oneof is described in [protobuf language guide](https://developers.google.com/protocol-buffers/docs/proto#using-oneof).
