### ISSUE TITLE
Implement std::io traits for streams

### ISSUE THREAD

**Issue by miedzinski** [stepancheg/rust-protobuf#229]
It'd be nice to have both `std::io::Read` and `std::io::BufRead` for `CodedInputStream` and `std::io::Write` for `CodedOutputStream`.

I'm relying on `CodedInputStream` heavily in my library because besides reading protobuf messages, I need to parse varints and all other sorts of data. It is working quite nicely, but I need to extend its functionality with trait that has implementation for `std::io::Read`. That could be solved easily with wrapping stream into another struct (or maybe there is another way?), but OTOH there is no reason that these impls couldn't be provided. Of course I can't implement that trait for `CodedInputStream` due to coherence rules.

EDIT
Another option would be to implement those for `BufReadIter` and expose it from `CodedInputStream`.

**Comment by stepancheg** [comment]
I'm not 100% sure, but I think implementing `Read` and `Write` (and probably `BufRead`) directly by `Coded*Stream` would be a good thing.

`BufReadIter` is an implementation detail, it should not be exposed.

**Comment by stepancheg** [comment]
Pull request is welcome.
