### ISSUE TITLE
Move codegen into separate crate

### ISSUE THREAD

**Issue by stepancheg** [stepancheg/rust-protobuf#234]

**Comment by jbowens** [comment]
I'd love to see no_std support from the crate that's imported by generated code at runtime. Separating codegen into a separate crate would be really helpful for that, so that codegen can freely depend on std.

**Comment by stepancheg** [comment]
codegen is now in separate crate (PR is about to land).

I'm going to create a separate issue for `#[no_std]`, although I have no idea how `#[no_std]` works. Code should use only imports from `core`? Is `Vec` struct available? Is `HashMap` available? Should read and write be only to bytes, without using `Read` and `Write` traits? If you know how to do it, please tell me.
