### ISSUE TITLE
Initialize Vectors and Strings with `with_capacity(0)`

### ISSUE THREAD

**Issue by valarauca** [stepancheg/rust-protobuf#235]
Currently on `take` calls, which look like

```rust
   pub fn take_my_field(&mut self) -> ::std::string::String {
       ::std::mem::replace(&mut self.my_field, ::std::string::String::new())
   }
```

If these could do 

```rust
   pub fn take_my_field(&mut self) -> ::std::string::String {
       ::std::mem::replace(&mut self.my_field, ::std::string::String::with_capacity(0))
   }
```

This avoids making an allocation, it differs that operation until data is written to that collection. (The same is true for vec.

---

I'll happy submit a patch for this if you can point to which file to modify.

**Comment by stepancheg** [comment]
`Vec::new()` is the same as `String::with_capacity(0)` (and `String::new()` is the same as `String::with_capacity(0)`). Neither of these calls allocate.
