### ISSUE TITLE
Use `Bytes` without using `proto2`

### ISSUE THREAD

**Issue by valarauca** [stepancheg/rust-protobuf#238]
So either accidentally or intentionally this crate works with `proto3`. I was attempting to hack in `Bytes` support but things got a little weird because its requiring _internal_ google protobufs. 

Could you jot down a quick guide on how to integrate the `Bytes` crate?

**Comment by stepancheg** [comment]
> requiring internal google protobufs.

Not sure I understand. I don't work for Google, and rust-protobuf doesn't need internal protobuf.

> Could you jot down a quick guide on how to integrate the Bytes crate?

Instruction is [there](https://github.com/stepancheg/rust-protobuf#copy-on-write). Isn't anything clear in it?

**Comment by valarauca** [comment]
Okay this is what confused me

The link you give points too [rustproto](https://github.com/stepancheg/rust-protobuf/blob/master/proto/rustproto.proto) which `syntax=proto2;` and uses the `optional`keyword  which is illegal in `syntax=proto3;`. Also it points to a [google proto](https://github.com/stepancheg/rust-protobuf/blob/master/proto/google/protobuf/descriptor.proto) which is also incompatible with `syntax=proto3;`.

**Comment by stepancheg** [comment]
It is OK to include file with syntax=proto2 from file with syntax=proto3.

**Comment by stepancheg** [comment]
I hope I answered the question.
