### ISSUE TITLE
Consider removing asserts in frequently called functions for improving performance

### ISSUE THREAD

**Issue by cwen0** [stepancheg/rust-protobuf#239]
Replace `assert!()`[1] with `debug_assert!()` in `encode_varint32()`and
`encode_varint64()` should improve the performance[2] in suitions like
encoding small messages very frequently.

[1] https://github.com/stepancheg/rust-protobuf/blob/4a2e71bae08d4a95326d8010a7365228f6015716/protobuf/src/varint.rs#L5
[2]  https://github.com/danburkert/prost/pull/21/commits/da477703c2e13a51592dbe265ee34707c1a00eca

**Comment by stepancheg** [comment]
Function calls `get_unchecked_mut` so range check must not be removed.

However, function could probably be marked as `#[inline(always)]` to effectively remove this range check.

**Comment by cwen0** [comment]
Thank you for your prompt reply. I will try it out.

**Comment by stepancheg** [comment]
Closing the issue. If you have some concrete proposals what assertions to remove, please reopen or send a PR.
