### ISSUE TITLE
Protobuf types should be serializable 

### ISSUE THREAD

**Issue by timperrett** [stepancheg/rust-protobuf#242]
Thanks for the great work on this crate! 

I've been using it to work with some gRPC interfaces which leverage proto3. The generation works, but i think there's a problem in that [the protobuf Any type](https://developers.google.com/protocol-buffers/docs/proto3#any) needs one to serialize values into it in a specific way (so far so good). However, as none of the proto-structures (e.g. RepeatedField) have `#derive([Serialize, Deserialize])` annotated, one cannot actually serialize the structures. Would it make sense to add these so that uses can leverage the serialized types without having to re-implement manually for every protobuf type?

Looks like the change could be fairly straight forward if its just added here?
https://github.com/stepancheg/rust-protobuf/blob/6d28afbd05b12b842d50c95be9031315905fd7f0/protobuf/src/codegen/message.rs#L370

**Comment by stepancheg** [comment]
You are talking about serde's deriv Serialize/Deserialize?

I'm not sure it should be default dependency, but rust-protobuf could have a codegen option (e. g. in [protoc_rust::Args](https://github.com/stepancheg/rust-protobuf/blob/df787b8967bbd1946f2a729eaf81e58a3fb56727/protoc-rust/src/lib.rs#L16-L23) or in [rustproto.proto](https://github.com/stepancheg/rust-protobuf/blob/master/proto/rustproto.proto) which enables generation of such annotations).

About the library itself, I think it could have a ["serde" feature](https://github.com/stepancheg/rust-protobuf/blob/df787b8967bbd1946f2a729eaf81e58a3fb56727/protobuf/Cargo.toml#L17-L18) to enable dependency on serde.

So doing to properly (without introducing unconditional dependency on serde) is somewhat harder than adding derive.

If you want to do it, patch is welcome. I wanted to do it myself, but I don't have time.

**Comment by timperrett** [comment]
@stepancheg i have a local copy where i'll apply the derive annotations directly simply to checkout if this is going to solve my problem. If it does, i'll see about contributing something :-) 

Thanks for the prompt response! I'll look into the feature proposal and the protoc_rust args.

Cheers

**Comment by chinedufn** [comment]
@timperrett how did things work out for you here? Looking to deserialize structs that have rust-protobuf enum fields and would love any advice that you might have.

@stepancheg rust noob here but I'd be willing to PR serde support if you could point me in the right direction?

Mainly:

1. Can you point me to one of the unit tests that I could model a serde derive test against? Or more broadly... how should I go about testing this?

2. When you say

> somewhat harder than adding derive.

do you mean that we'd need to add a conditional - or is there a lot more than that?

Thank you for your help!!

**Comment by stepancheg** [comment]
@chinedufn 

> but I'd be willing to PR serde support if you could point me in the right direction?

> Can you point me to one of the unit tests that I could model a serde derive test against? Or more broadly... how should I go about testing this?

Protobuf tests live in [protobuf-test crate](https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-test).

If you want to implement it, you probably want to:
* create separate .proto files (somewhere like protobuf-test/src/common/v2/test_serde_pb.proto)
* create a test next to the file

Tests are executed with `cargo test` in `protobuf-test` directory. `cargo test` command regenerated `.rs` files from `.proto`

> When you say "somewhat harder than adding derive." do you mean that we'd need to add a conditional based on whether or not with-serde was used - or is there a lot more than that?

* yes, `with-serde` option
* fields should probably be properly renamed with `#[serde(rename)]` to how they are named in protobuf (e. g. field named `struct` is called `struct_field` in generated code, and probably should be renamed back in serde)
* special fields (cached size and unknown fields) should be excluded from serde

So if you are willing to implement it, I'd be glad to assist and review partial/incomplete version of the patch. Feel free to send a PR!

Also, please note, that proper conversion of protobuf data to JSON should be eventually implemented natively (to strictly match Google protobuf JSON specification), not with serde.

**Comment by chinedufn** [comment]
Thank you so much for the guidance on this! I can't dive in this week but I'll make some time to take a look! Thanks!

**Comment by chinedufn** [comment]
Hey @stepancheg I'm taking a look at this right now!

Here's my plan:

1. Follow your very helpful notes above and try to get things working for enums
2. PR that
3. Fix all of your feedback

I feel like reducing the scope of this first stab to enums will make it that much easier for me to get my first Rust PR out - but let me know if that is unacceptable for any reason!
