### ISSUE TITLE
Very basic question: How to encode for sending?

### ISSUE THREAD

**Issue by anderspitman** [stepancheg/rust-protobuf#270]
Sorry I know this is the most basic functionality, but this is my first time using protocol buffers and I'm also fairly new to Rust. I have my proto file being compiled correctly, and I'm able to import the generated Rust module, instantiate messages, and populate values. What method should I call to convert it to text/binary/whatever to send over the wire (a websocket, if that matters) for decoding by my javascript (protobuf.js) application?

Sorry if this is documented some and I missed it. Digging through the generated Rust file didn't yield anything obvious to me either.

Thanks!
//anders

**Comment by stepancheg** [comment]
Well answer depend on what exactly you need to do.

For example, if you want to convert a message to bytes, you can simply call a function like `message.write_to_bytes()`.

This function is [defined in `trait Messate`](https://github.com/stepancheg/rust-protobuf/blob/c287432d047ccb0c3107b6463a7c991b7664b50c/protobuf/src/core.rs#L112), so you didn't find it in generated code.

If you need a text representation of message, you can call `protobuf::text_format::fmt(message, f)`.

Sorry for late response!

**Comment by nevi-me** [comment]
Hi @stepancheg, I'm struggling with the inverse of this question. I'm trying to create a message from bytes. I have a `Vec<u8>` but I'm not finding the correct function to use on my message. I've also tried `CodedInputStream`, but am not winning.

What function can I call to create a protobuf message from bytes?

**Comment by stepancheg** [comment]
@nevi-me there's a `protobuf::parse_from_bytes` function which parses bytes into a message.

I should probably write a FAQ. Fell free to ask questions if you have ones.

**Comment by nevi-me** [comment]
If you offer guidance on where we can place the FAQ, I can submit some PRs for some of the questions that I've seen on the issues. Granted I'm still reading up on the API, so some of my answers might not be the most eloquent/efficient ways of doing things.

For example, I eventually went with:

```rust
let mut org = common::Organisation::new();
org.merge_from_bytes(bytes.as_ref());
```

By creating a new message, and merging the raw bytes of the message I want.

To close out my question, once I have a `ProtobufResult`, what do I do with it to convert it into my `common::Organisation` message?

Thanks, really appreciate your help.

**Comment by stepancheg** [comment]
> If you offer guidance on where we can place the FAQ

I think `FAQ.md` in the root of the repository would be the right place.

>  can submit some PRs for some of the questions that I've seen on the issues

I'll appreciate that.

> To close out my question, once I have a ProtobufResult, what do I do with it to convert it into my common::Organisation message?

The same thing you usually do with `Result`: call `.unwrap()` to panic on error or handle error gracefully:

```
match org.merge_from_bytes(...) {
  Ok(..) => println!("hooray! parsed message is already in org variable"),
  Err(e) => { println!("I've got an error {:?}, e); return; }
}
```

Note that `merge_from_bytes` doesn't check that all `required` fields are set when syntax is `proto2`. Nobody seem to use `required` fields, but anyway.
