### ISSUE TITLE
Implement pure-rust proto parser and code generator

### ISSUE THREAD

**Issue by stepancheg** [stepancheg/rust-protobuf#271]
Probably based on [.proto parser from quick-protobuf](https://github.com/tafia/quick-protobuf/blob/master/codegen/src/parser.rs)

WIP is [here](https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-codegen-pure)

**Comment by tafia** [comment]
This is new!

Happy, if you want, to move it into a dedicated project that both quick-protobuf and rust-protobuf could use.

**Comment by stepancheg** [comment]
@tafia separate project with just parser would be great, and I'd like to use it!

Note I don't want to kill current parser using `protoc`, but provide pure rust version as an alternative.

**Comment by tafia** [comment]
We're on the same page.
I'll do it asap

**Comment by stepancheg** [comment]
No hurry, I'm not sure I'll find time for this issue during week. But thanks!

**Comment by tafia** [comment]
So I finally found some time to extract the parser part of quick-protobuf into its own [repository](https://github.com/tafia/protobuf-parser).

I have remove all struct/enum implementation so any protobuf library can implement their own logic.

It still needs some work (documentation, readme probably more tests) but I wanted to know if this is what you had in mind. If it is ok I'll migrate quick-protobuf to it.

I am happy to put you as maintainer if you want.

**Comment by danburkert** [comment]
Any plans to parse docstrings or handle import resolution a la `protoc`?

**Comment by stepancheg** [comment]
@danburkert yes, it's definitely should be supported.

**Comment by stepancheg** [comment]
@danburkert 

Standard protobuf import statements should be supported (as far as I see, protobuf-parser proper parses imports).

What do you mean by "parse docstrings"?

**Comment by stepancheg** [comment]
FYI [this commit](https://github.com/stepancheg/rust-protobuf/commit/10b395c5f583e1567abf4f598f2f94c013dd5025#diff-a41c53193c8351a36ac88a17e9bf01c2) adds first test of pure rust codegen using @tafia (thank you!) protobuf parser.

The plan is to port all of `protobuf-test` tests to `protobuf-codegen-pure-test` tests, so both codegens should run identical set of tests on identical `.proto` input files.

If anyone wants to volunteer, you are welcome.

**Comment by tafia** [comment]
I have made a [new PR](https://github.com/tafia/protobuf-parser/pull/1) to clean proto-parser and start documenting it. Some fields are not directly linked to the .proto file but were used in quick-protobuf implementation.

> The plan is to port all of protobuf-test tests to protobuf-codegen-pure-test tests, so both codegens should run identical set of tests on identical .proto input files.

It might be good to port all test parsing to proto-parser.

**Comment by tafia** [comment]
@danburkert 

> Any plans to parse docstrings or handle import resolution a la protoc

### docstrings

If you think about comment then they are parsed but ignored for the moment (they don't appear in parsed structs). I don't know if it is something important, we can definitely add it if needed

### import resolution

If by this you mean recursively parsing imports then no, this has not been ported to protobuf-parser for the moment.

The implementation in quick-protobuf is not as clean as I'd like it to be and is probably too linked to implementation details (boxes, nested modules etc ...).

On the other hand I would be happy to merge any PR to enable it.

**Comment by stepancheg** [comment]
@tafia I've added a couple of comments about the library to the PR.

Anyway, I'm grateful for that change: fields needed only for quick-protobuf are confusing. Thanks!

Would you mind publishing the library to crates.io?

**Comment by stepancheg** [comment]
@tafia 

> It might be good to port all test parsing to proto-parser.

Tests do not specifically test parser, they assume parser works correctly and test code generation and serialization/deserialization. So rust-protobuf tests implicitly test parser, but cannot be ported to protobuf-parser crate.

**Comment by stepancheg** [comment]
@tafia 

> If by this you mean recursively parsing imports then no, this has not been ported to protobuf-parser for the moment.

I have to say that if this logic could be merged into protobuf-parser (along with name to fully qualified name resolution), I'd to be happy to reuse it. Because otheriwise I'd have to implement it in rust-protobuf.

**Comment by stepancheg** [comment]
FYI, current implementation now works with relatively simple `.proto` files.

**Comment by stepancheg** [comment]
OK, at the moment all rust-protobuf tests work with parser/codegen codegen implemented in Rust.

So I'm closing the issue. If something doesn't work, please open another issue.
