### ISSUE TITLE
A few questions about best practices

### ISSUE THREAD

**Issue by anderspitman** [stepancheg/rust-protobuf#282]
Sorry if this is the wrong place to ask this. I've got things up and running with proto3 using protobuf JS in the browser and rust-protobuf for my server. It feels a bit clunky so I want to see if there are any suggestions for how I might improve my design. Basically I'm building a simple game where all the logic runs in rust, and protobuf is used over a websocket to communicate with the UI which runs in a browser (designed to run on the same machine to minimize latency). In the Server->Client direction it's mostly just streaming state updates which are always the same type, so no problem. However, in the Client->Server direction there are different types of messages that can be sent. Some are just a simple command with no payload, others have various payloads. I'm currently handling like this:

.proto
```
message UiMessage {
    oneof {
        CommandType1 command_type_1 = 1;
        CommandType2 command_type_2 = 2;
    }
}

message CommandType1 {
    // no payload
}

message CommandType2 {
    int32 payload = 1;
}
```

rust
```rust
if let Ok(ui_message) = parse_from_bytes::<UiMessage>(&raw_message) {
    if ui_message.has_command_type_1() {
        //...
    }
    else if ui_message.has_command_type_2() {
        let payload = ui_message.get_command_type_2().get_payload();
        //...
    }
}
```
There are a couple things that I don't like about this:

1. Having to use if-else rather than being able to match on the message type. Does rust-protobuf have a way to do this?
2. Naming the subcommands the same as their types seems weird, and makes me think I might be using the wrong approach to accomplish my task.

Any suggestions?

**Comment by stepancheg** [comment]
> Having to use if-else rather than being able to match on the message type. Does rust-protobuf have a way to do this?

rust-protobuf has an `expose_oneof` codegen option. It's off by default, but should be public in the next release.

Currently you need to include `rustproto.proto` and specify options in your `.proto` file, but in later versions this could be turned on programmatically (which won't be necessary, because oneof should be on by default).

> Naming the subcommands the same as their types seems weird, and makes me think I might be using the wrong approach to accomplish my task.

I think this is standard way to do it protobuf.


Sorry for late reply, I overlooked it.

Hope I helped.
