### ISSUE TITLE
1.6.0 breaks semver, should be 2.0.0

### ISSUE THREAD

**Issue by ahill-mlft** [stepancheg/rust-protobuf#289]
The [backward compatibility issues in the changelog](https://github.com/stepancheg/rust-protobuf/blob/master/CHANGELOG.md#backward-compatibility-issues), especially the removal of public APIs, are pretty clear signals the major version should have been bumped. For example, the removal of the `MessageStatic` trait breaks the [Prometheus](https://crates.io/crates/prometheus) crate currently on crates.io.

**Comment by ahill-mlft** [comment]
There is! You can [yank version 1.6.0](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-yank), then republish it as 2.0.0.

**Comment by stepancheg** [comment]
That will break crates which depend on 1.6, not sure it’s right thing now.

As a temporary solution I can suggest to explicitly depend on ~1.5 in your crates now. 

Sorry again.

**Comment by bachp** [comment]
One solution would be to re-publish 1.5 as 1.7
And then re-release 1.6 as 2.0

**Comment by pamolloy** [comment]
@stepancheg @bachp's solution is a good one. Please follow that recommendation.

Like any bug when writing software, bumping a semver incorrectly happens, but it is important to fix it just like any other bug.

**Comment by stepancheg** [comment]
OK, republished version 1.7.1 from 1.5 branch. Not sure it's the best idea, but OK.

**Comment by stepancheg** [comment]
Republished 1.6 branch as 2.0.0.
