### ISSUE TITLE
Reflection on nested messages

### ISSUE THREAD

**Issue by ccakes** [stepancheg/rust-protobuf#290]
I'm using rust-protobuf and have a situation with nested messages, I'm trying to dig through them to turn the data into something to push to a timeseries DB but I can't figure out a good way to do it.

The messages are coming from vendor equipment so I don't have control over the format. There are also hundreds of message types with varying depths so I'm trying to do this as dynamically as possible. I've created a sample project [here](https://github.com/ccakes/rust-proto-recurse) which demonstrates the issue.

Reflecting a non-nested message works fine but if I want to go deeper, I run into the error below. If I box it, the call to [`f.get_reflect()`](https://github.com/ccakes/rust-proto-recurse/blob/master/src/main.rs#L11) fails because the `Message` trait isn't implemented for `Box<Message>`

```
error[E0277]: the trait bound `protobuf::Message: std::marker::Sized` is not satisfied
  --> src/main.rs:31:43
   |
31 |         ProtobufValueRef::Message(m) => { reflect_msg(m); }
   |                                           ^^^^^^^^^^^ `protobuf::Message` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `protobuf::Message`
note: required by `reflect_msg`
  --> src/main.rs:8:1
   |
8  | fn reflect_msg<M: Message>(m: &M) {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm relatively new to Rust so I may just be approaching this incorrectly, but any help would be appreciated.

**Comment by stepancheg** [comment]
This is the fix of compilation of your project:

```
diff --git a/src/main.rs b/src/main.rs
index e9dfa0c..b1e9547 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -5,7 +5,7 @@ use protobuf::reflect::{ReflectFieldRef, ProtobufValueRef};
 mod proto;
 use proto::qos_stats::*;

-fn reflect_msg<M: Message>(m: &M) {
+fn reflect_msg(m: &Message) {
     let d = m.descriptor();
     for f in d.fields() {
         match f.get_reflect(m) {
@@ -20,6 +20,7 @@ fn reflect_msg<M: Message>(m: &M) {
                     print_kv( &format!("{}-{}", f.name(), c), val.as_ref() );
                 }
             }
+            _ => unimplemented!()
         };
     }
 }
```

Not sure that reflection will work (and if it doesn't please report an issue), but at least it compiles.

**Comment by ccakes** [comment]
Thanks - that did it. The reflection works great as well. Thanks for the help!
