### ISSUE TITLE
CI: Test minimum supported stable Rust version

### ISSUE THREAD

**Issue by b-r-u** [stepancheg/rust-protobuf#296]
To avoid accidentally bumping the minimum supported stable Rust version, `.travis.yml` should also include a build for a fixed Rust version.
The minimum version used to be Rust 1.23.0 but is now 1.26 for the current master because of some missing ampersand characters in match bindings.

**Comment by stepancheg** [comment]
Good idea for stable protobuf branches.

**Comment by stepancheg** [comment]
CI in 1.7 and 2.0 branches now checked against rust 1.23.0, and published versions 1.7.3 and 2.0.2.

**Comment by b-r-u** [comment]
Thanks! This was really quick :)
