### ISSUE TITLE
Compile issue using non-explicit versions

### ISSUE THREAD

**Issue by SeanAvery** [stepancheg/rust-protobuf#298]
I am running into the following issue with version `1.6.0`

installing by the explicit version is working correctly:
```
... 
[dependencies]
protobuf = "1.6.0"
```
However, most libraries have the dependency as:
`protobuf = { version = "~1.6", features = ["with-bytes"] }` 

which breaks the compile.

I get the following error many times in `descriptor.rs`

```
error[E0495]: cannot infer an appropriate lifetime for borrow expression due to conflicting requirements
```

any non-explicity dependency such as `protobuf = "1.6.*"` or `protobuf = "~1.6"` also breaks with the same error.

**Comment by stepancheg** [comment]
Aren’t you using too old rust compiler?

And btw version 1.6 was republished as 2.0 (see details in change log) which should be used unless you are using grpc-rust which didn’t upgrade protobuf yet. 

Latest 2.0 version is also better compatible with older rust. 

Sending from iPad.

**Comment by SeanAvery** [comment]
yes, latest nightly `1.26.1` works! Thanks for your help.

**Comment by stepancheg** [comment]
@SeanAvery to be clear, `1.26.1` is the latest stable compiler. Latest nightly is `1.28.0`.

**Comment by ashthespy** [comment]
@stepancheg What is the minimum Rust version supported by the `2.0.*` version? 
We are running into the same issue with Rust `1.21.0`

**Comment by stepancheg** [comment]
@ashthespy 2.* version minimum supported rust version is [1.23](https://github.com/stepancheg/rust-protobuf/blob/6c74afc426fc02bf036ead75bc8f327ad50cf075/.travis.yml#L7).

I didn't look how hard would it be to make it compatible with 1.21.
