### ISSUE TITLE
Can't use protobuf-codegen-pure crate

### ISSUE THREAD

**Issue by jamesray1** [stepancheg/rust-protobuf#307]
https://github.com/libp2p/rust-libp2p/issues/183#issuecomment-397576664

**Comment by Vurich** [comment]
The issue is that it generates code using `::protobuf::reflect::accessor`, which is a private module.

**Comment by stepancheg** [comment]
Could you please provide an example which doesn't work? `.proto` file and command used? Ideally a small crate example.

I tried this https://github.com/jamesray1/rust-libp2p/tree/master/floodsub, it works with this patch:

```
diff --git a/floodsub/Cargo.toml b/floodsub/Cargo.toml
index 0d187c7..392eedb 100644
--- a/floodsub/Cargo.toml
+++ b/floodsub/Cargo.toml
@@ -17,3 +17,6 @@ protobuf = "2"
 smallvec = "0.6.0"
 tokio-io = "0.1"
 varint = { path = "../varint-rs" }
+
+[build-dependencies]
+protobuf-codegen-pure = "2"
diff --git a/floodsub/build.rs b/floodsub/build.rs
index dc63fab..53cfd25 100644
--- a/floodsub/build.rs
+++ b/floodsub/build.rs
@@ -1,9 +1,12 @@
 extern crate protobuf_codegen_pure;
 
+fn main() {
 protobuf_codegen_pure::run(protobuf_codegen_pure::Args {
     out_dir: "src",
-    input: "rpc.proto",
+    input: &["rpc.proto"],
+    includes: &[""],
     customize: protobuf_codegen_pure::Customize {
       ..Default::default()
     },
-}).expect("protoc");
\ No newline at end of file
+}).expect("protoc");
+}
```

**Comment by Vurich** [comment]
Looks like it works, there was just a leftover file generated by the previous version.

**Comment by jamesray1** [comment]
If fails on Windows:

error: failed to run custom build command for `ring v0.12.1 (https://github.com/briansmith/ring?rev=3a14ef619559f7d4b69e2286d49c833409eef34a#3a14ef61)`

Full output: https://gist.github.com/jamesray1/923e16382a7df268c775dfe86f549d88. File an issue with @briansmith?

**Comment by stepancheg** [comment]
Protobuf doesn’t depend on ring. Are you trying to use grpc?

**Comment by jamesray1** [comment]
Not that I'm aware of.

I'm on Windows 10, Visual Studio, RLS is installed, and the terminal is bash: `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`.

**Comment by stepancheg** [comment]
What project are trying to compile? I assume it’s rust-libp2p which likely depends on ring. So it’s not rust-protobuf issue, and you should probably post comments there.
