### ISSUE TITLE
 Incorrect varint length calculation for negative floats 

### ISSUE THREAD

**Issue by johnfercher** [stepancheg/rust-protobuf#309]
I'm having a problem similtar to #168, but when I use f32 (instead of int32) and set a negative value.

**proto**
```protobuf
message Foo {
        required float bar = 1;
}
``` 
**Rust**
```rust
let bytes = foo.write_to_bytes().unwrap();
match str::from_utf8(&bytes){
     Ok(v) => self.socket.send(v, 0).unwrap(),
     Err(e) => println!("{:?}", e)
}
``` 

**Error**
```
utf8error { valid_up_to: 11, error_len: some(1) }
```

**Comment by johnfercher** [comment]
Any updates about this issue? How can I help to solve it?

**Comment by stepancheg** [comment]
Sorry, I missed this issue.

This behaviour is correct: protobuf binary is generally not a valid UTF-8 sequence.

Why do you want to convert bytes to string?

**Comment by johnfercher** [comment]
You are right, I don't need to convert to string. My bad. Thanks xD
