### ISSUE TITLE
Support well known types in protobuf-codegen-pure

### ISSUE THREAD

**Issue by marcelbuesing** [stepancheg/rust-protobuf#312]
As far as I can tell "well known types" do not work with `protobuf-codegen-pure` because the types are not translated to the generated protobuf lib well known type.I assume the fn `type_name_to_rust_relative` from `protobuf-codgen/src/rust_types_values.rs` can be reused for this. Furthermore I assume the `import google/protobuf/...proto` has to be dealt with.

**Comment by JayKickliter** [comment]
I just ran into this problem. The only well-known type I want to use is `Timestamp`. I tried using `protobuf-codegen` instead of `protobuf-codegen-pure`, but that lead to complaints about `enum` namespacing.

**Comment by adamcrume** [comment]
I just ran into this myself with google.protobuf.Any.

**Comment by schoenenberg** [comment]
Is anyone working on this?

**Comment by clintfred** [comment]
Timestamp discussed on #469
