### ISSUE TITLE
Support raw bytes for protobuf string fields

### ISSUE THREAD

**Issue by wtetzner** [stepancheg/rust-protobuf#315]
Currently, we can use the Bytes type, but it's wrapped with Chars, which ensures valid UTF-8.

However, as far as I can tell, protobuf doesn't require strings to be valid UTF-8, they are just bytes. Can we get an option in protobuf-codegen-pure to generate code that treats protobuf strings as plain old bytes?

**Comment by stepancheg** [comment]
According to [protobuf spec](https://developers.google.com/protocol-buffers/docs/proto), "A string must always contain UTF-8 encoded or 7-bit ASCII text."

Implementing this option is possible, but that would be against spec, and don't see why is it needed.

However, if you really want to treat strings as bytes, you can preprocess `.proto` files before calling codegen. E. g. `sed 's/string/bytes/`.

**Comment by wtetzner** [comment]
Ah, I stand corrected. :)
