### ISSUE TITLE
protoc-rust doesn't always put optional in an Option

### ISSUE THREAD

**Issue by losvedir** [stepancheg/rust-protobuf#316]
I'm trying to parse the transit agency realtime spec, [GTFS Realtime .proto file](https://developers.google.com/transit/gtfs-realtime/gtfs-realtime.proto), and used `protoc-rust`. Some of the fields I expected to be `Option` were instead `SingularPtrField`.

For example, the `FeedEntity` in the spec looks like this:

```
message FeedEntity {
  required string id = 1;
  optional bool is_deleted = 2 [default = false];

  // Data about the entity itself. Exactly one of the following fields must be
  // present (unless the entity is being deleted).
  optional TripUpdate trip_update = 3;
  optional VehiclePosition vehicle = 4;
  optional Alert alert = 5;

  extensions 1000 to 1999;
}
```

The generated struct looks like this:

```rs
#[derive(PartialEq,Clone,Default)]
pub struct FeedEntity {
    // message fields
    id: ::protobuf::SingularField<::std::string::String>,
    is_deleted: ::std::option::Option<bool>,
    trip_update: ::protobuf::SingularPtrField<TripUpdate>,
    vehicle: ::protobuf::SingularPtrField<VehiclePosition>,
    alert: ::protobuf::SingularPtrField<Alert>,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}
```

So while, `is_deleted` is inside of an `Option`, `trip_update`, `vehicle` and `alert` are not. I would expect them to be; I had thought a `repeated` would go in a `Vec`, and an `optional` would go in an `Option`. Is that not the case?

My `build.rs` file looks like this:

``` rs
extern crate protoc_rust;
use protoc_rust::Customize;

fn main() {
    protoc_rust::run(protoc_rust::Args {
        out_dir: "src/protos",
        input: &["protos/gtfs-realtime.proto"],
        includes: &["protos"],
        customize: Customize {
          ..Default::default()
        },
    }).expect("protoc");
}
```

My `protoc` version is `3.6.0`.

**Comment by stepancheg** [comment]
`SingularPtrField` is essentially the same thing as `Option`.

It is created to solve two things:
* faster parsing when message is cleared and memory is reused
* recursive messages

FYI, there's a task for implementing an option to store messages in `Option<Box<M>>`: https://github.com/stepancheg/rust-protobuf/issues/300

**Comment by losvedir** [comment]
Oh, I see, I misunderstood. Thanks!
