### ISSUE TITLE
Add accessors for `oneof` variant enum

### ISSUE THREAD

**Issue by Ameobea** [stepancheg/rust-protobuf#320]
Codegen currently produces accessors for all of the variants of `oneof` fields but not for the enum itself.  It is often desirable to match on the enum itself and see which variant is included.

For example, a message like this:

```
message Foo {
  oneof payload {
    Bar bar = 1;
    Baz baz = 2;
  }
}
```

would produce a Rust struct with `has_payload` and `get_payload` methods.  `get_payload` would return `Option<Foo_oneof_payload>`.

**Comment by Ameobea** [comment]
@stepancheg is this something you'd be willing to accept as a PR?  If so, I'd be happy to take a stab at implementing it.

**Comment by stepancheg** [comment]
@Ameobea in latest protobuf (in 2.0 IIRC) oneof fields (e. g. `payload` field of `Foo` struct) is public by default. Why `get_payload`/`set_payload` functions are necessary?

Sorry for the late response!

**Comment by stepancheg** [comment]
Closing due to old age.
