### ISSUE TITLE
more/most of protobuf-codegen-pure should be public

### ISSUE THREAD

**Issue by bwo** [stepancheg/rust-protobuf#322]
it contains a parser for and model of protobuf files, but these aren't accessible; this seems unfortunate if you want to do anything *other* than generate rust output as if for a protoc plugin.

**Comment by bwo** [comment]
Oh, that other project is probably sufficient actually.

The use case is that we generate a bunch of subsidiary code based on protobuf definitions; it would be possible to do it as part of a protobuf plugin (in which case we'd only need to read in the parsed representations they provide), but I wanted to try just parsing the files directly.

**Comment by stepancheg** [comment]
BTW, for your task you probably only need [`parse_and_typecheck`](https://github.com/stepancheg/rust-protobuf/blob/76e59fe769362371fc8b93eaf81f1d8f8e56b33d/protobuf-codegen-pure/src/lib.rs#L201) function, which is technically public, but hidden. Maybe it is worth to stabilize this function only without exposing other `protobuf-codegen-pure` internals.
