### ISSUE TITLE
Unnecessary EOF check

### ISSUE THREAD

**Issue by sadaszewski** [stepancheg/rust-protobuf#328]
I believe this check to be unnecessary when reading from a length-delimited file and always causing the code to fail. At least this is what happens when I read from a slice of memmap-ed file. I.e. I have a zero padded file with a simple message \x02 \x08 \x08 and I get Custom { kind: InvalidData, error: WireError(UnexpectedEof) }. I will test with regular files tomorrow.

pub fn check_eof(&mut self) -> ProtobufResult<()> {
        let eof = self.eof()?;
        if !eof {
            return Err(ProtobufError::WireError(WireError::UnexpectedEof));
        }
        Ok(())
    }

**Comment by stepancheg** [comment]
I guess you are using `parse_length_delimited_from_reader` operation?

If so, I think that operation should be removed completely to avoid misunderstanding.

* Calling this operation in a loop is expensive (because each invocation of this operation allocates a heap buffer inside `CodedInputStream`).
* Calling it ones to read till EOF is probably useless

**Comment by sadaszewski** [comment]
TBH I am not even reading "from a file". I do the stuff below. The idea is to allocate a big chunk but at the beginning have only header written there: `message GrowingMmapHeader { required uint64 used_size = 1; }`. Efficiency aside I don't think this should be failing, am I doing this wrong?


```rust 
impl GrowingMmap {
    pub fn new(filename : &str) -> Result<GrowingMmap, io::Error> {
        let f = OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .open(filename)?;
        let meta = f.metadata()?;
        println!("meta.len: {:?}", meta.len());
        let len = meta.len();
        let reserved_size =
            if len == 0 {
                let default_reserved_size = 1024 * 1024;
                f.set_len(default_reserved_size)?;
                default_reserved_size
            } else {
                len
            };
        let mut mm = unsafe { MmapOptions::new().map_mut(&f)? };
        let used_size =
            if len == 0 {
                let mut hdr = GrowingMmapHeader::new();
                hdr.set_used_size(8);
                {
                    let mut cos = CodedOutputStream::bytes(&mut mm[..]);
                    hdr.write_length_delimited_to(&mut cos)?;
                    cos.flush()?;
                }
                println!("first bytes in mm: {:?}", &mm[0..16]);
                0
            } else {
                println!("first bytes in mm: {:?}", &mm[0..16]);
                let hdr = parse_length_delimited_from_bytes::<GrowingMmapHeader>(&mm[0..3])?;
                //let mut cis = CodedInputStream::from_bytes(&mm[..]);
                //let mut hdr = GrowingMmapHeader::new();
                //hdr.merge_from(&mut cis)?;
                hdr.get_used_size()
            };
        Ok(GrowingMmap {
            filename: String::from(filename),
            mm,
            reserved_size,
            used_size
        })
    }
}```

**Comment by stepancheg** [comment]
The same story with `parse_length_delimited_from_bytes`, should be also removed for the same reasons.

I'm not sure I understand what you data should look like.

Is it

```
GrowingMmapHeader length
GrowingMmapHeader
remaining data
```

?

if so, you should probably do:

```
let mut is = CodedInputStream::from_bytes(&mm);
let hdr = is.read_message(); // read length-delimited message
let remaining_data_offset = is.pos();
```

**Comment by sadaszewski** [comment]
Ok, great. This seems to work! Many thanks.
