### ISSUE TITLE
`#[allow(clippy)]` should be `#[allow(clippy::all)]` now.

### ISSUE THREAD

**Issue by Hoverbear** [stepancheg/rust-protobuf#331]
Clippy itself now recommends using this instead:

```
warning: lint name `clippy` is deprecated and may not have an effect in the future. Also `cfg_attr(cargo-clippy)` won't be necessary anymore
 --> src/eraftpb.rs:6:10
  |
6 | #![allow(clippy)]
  |          ^^^^^^ help: change it to: `clippy::all`
  |
  = note: #[warn(renamed_and_removed_lints)] on by default
```

**Comment by aldanor** [comment]
Any thoughts on this? Not critical but a bit annoying...

**Comment by Hoverbear** [comment]
@aldanor See #332. There are some problems since nightly and stable clippy aren't behaving.

**Comment by Ten0** [comment]
Running on latest stable, simply replacing `#![allow(clippy)]` by `#![allow(clippy::all)]` works.

**Comment by Ten0** [comment]
I'm still hitting warnings due to this, it's annoying.
Is there still anything that prevents us from fixing this ?

**Comment by stepancheg** [comment]
Should be fixed now.
