### ISSUE TITLE
"No such file or directory", libcore/result.rs

### ISSUE THREAD

**Issue by stfl** [stepancheg/rust-protobuf#334]
I am trying to generate from my .proto definition and I get following error

```
error: failed to run custom build command for `medulink-daemon v0.1.0 (file:///home/sll/work/some/path)`
process didn't exit successfully: `/home/sll/work/some/path/target/debug/build/medulink-daemon-797b0f579059a7c3/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'protoc: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I am on Fedora 27 and I have protobuf-compiler installed at `/usr/bin/protoc`

**Comment by ccakes** [comment]
Looks like the error you get when the the target proto file doesn't exist. Double check the path you're passing to `protoc_rust::run()`

**Comment by stfl** [comment]
Thanks for the reply. The src/protos target directory was missing and the build script can't create it apperently.
