### ISSUE TITLE
Determine incoming message type

### ISSUE THREAD

**Issue by stfl** [stepancheg/rust-protobuf#335]
I am writing a daemon that accepts various messages from a remote client. I defined these messages in a `.proto` file and generated the code.

I've been trying to figure out how to determine the message type for incoming messages.
I had a look at `.as_any()` and reflection but I can't figure out how to implement a sth like a match statement with legs for different message types.

Any example code?
Thanks

**Comment by stfl** [comment]
does it have to be done like this?
https://stackoverflow.com/questions/30564404/how-to-determine-message-type-in-protobuf-so-that-i-can-use-that-type-parsefrom

**Comment by ccakes** [comment]
That's the easiest way that I'm aware of, especially if you control the sender + receiver.

**Comment by stepancheg** [comment]
Protobuf binary protocol does not embed message types. You need to write message type explicitly along with a message and do some form of switch on the reader side.

I think the easiest way to do that is to wrap all messages into another larger messages:

```
message Request {
  oneof m {
    SomeMessage m1 = 1;
    AnotherMessage m2 = 2;
    ...
  }
}
```

If you have no requirements of which protocol to use, you might want to use grpc which automates a lot of things.

**Comment by stfl** [comment]
Ok Thats good to know I can stop looking.
