### ISSUE TITLE
Private fields of a generated struct needs to be public

### ISSUE THREAD

**Issue by jamesray1** [stepancheg/rust-protobuf#336]
I was trying to make an adjustment to the rust-libp2p codebase which uses rust-protobuf, however got a few compiler errors, one of which is due to a private field of a public struct in a generated rpc_proto.rs file: ``[rustc] field `name` of struct `rpc_proto::TopicDescriptor` is private``. The problem is that this field needs to be public in order to use it for the topic ID in rust-libp2p. FMI see https://github.com/libp2p/rust-libp2p/issues/473#issuecomment-421889795.

**Comment by tomaka** [comment]
You should be able to use `.get_name()` instead of `.name`

**Comment by jamesray1** [comment]
Thanks, that indeed works!
