### ISSUE TITLE
Provide hooks to customize generated code

### ISSUE THREAD

**Issue by stepancheg** [stepancheg/rust-protobuf#338]
Currently, [`Customize`](https://github.com/stepancheg/rust-protobuf/blob/master/protobuf-codegen/src/customize.rs#L11) struct can be passed to codegen to customize generated code.

But [Customize] only provides basic options.

It is not possible to implement all possible options desired by users, e. g. generation of
* hash code
* serde annotations
* clippy warnings

It can be done two ways:

## Callback

```
trait CodegenCallback {
  fn code_insert_before_message(&self, message: &str) -> Option<String>;
  fn code_insert_before_field(&self, message: &str, field: &str) -> Option<String>;
  fn code_insert_before_enum(&self, e: &str) -> Option<String>;
  // etc
}
```

That will be flexible enough and easy to use.

## Insert markers in generated code

E. g. Google protobuf inserts markers like this in generated code:

```
    // @@protoc_insertion_point(class_scope:Bar)
    private static final Aaa.Bar DEFAULT_INSTANCE;
```

`@@protoc_insertion_point` can be replaced with arbitrary code after codegen completed.

This way it is more flexible, but harder to use.

**Comment by jamesray1** [comment]
At the moment I just want to derive `Eq` for a generated `*Descriptor` struct which has `Eq` implemented for all of its fields. If you have any tips about a faster way to do that or more details on how to implement the callback, e.g. what else needs to be modified so that a user can call one of the `CodegenCallback` methods. 

```rust
trait CodegenCallback {
    fn code_insert_before_message(&self, message: &str) -> Option<String>;
    fn code_insert_before_field(&self, message: &str, field: &str)
        -> Option<String>;
    fn code_insert_before_enum(&self, e: &str) -> Option<String>;
    // May not be necessary if inserting before a message or field
    // will insert with any other generated derived traits.
    // ? should you leave it to the user to check whether the trait being
    // added will not produce any errors?
    fn code_insert_after_other_derived_traits(&self, trait: &str,
        struct_or_enum: Option<Struct>) -> Option<String>;
    fn code_insert_before_method(&self, trait: &str) -> Option<String>;
    // This should insert in alphabetical order.
    fn code_insert_crate_level_attr(&self, attr: &str) -> Option<String>;
    // E.g. to implement a trait.
    fn code_insert_impl(&self) -> Option<String>;
}
```

**Comment by stepancheg** [comment]
Done in rust-protobuf=3.
