### ISSUE TITLE
Remove unsafe from generated code

### ISSUE THREAD

**Issue by rolftimmermans** [stepancheg/rust-protobuf#340]
I want to adopt `#![forbid(unsafe_code)]` in my application.

Unfortunately the use of `protobuf` makes this impossible. The following code is being generated

```rust
    fn default_instance() -> &'static Request_Resize {
        static mut instance: ::protobuf::lazy::Lazy<Request_Resize> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Request_Resize,
        };
        unsafe {
            instance.get(Request_Resize::new)
        }
    }
```

Can this be changed? Any pointers to how to approach it would be appreciated and I can try to submit a PR.

**Comment by rolftimmermans** [comment]
`#[allow(unsafe_code)]` is already there, and that leads to:

```
error[E0453]: allow(unsafe_code) overruled by outer forbid(unsafe_code)
  --> src/client/optimizer.rs:17:10
   |
17 | #![allow(unsafe_code)]
   |          ^^^^^^^^^^^ overruled by previous forbid
   | 
  ::: src/lib.rs:2:11
   |
2  | #![forbid(unsafe_code)]
   |           ----------- `forbid` level set here
```

**Comment by stepancheg** [comment]
I didn't know that.

Then seems like

* `Lazy::get` can take `&self` instead of `&mut self`
* then static field doesn't need to be `mut`
* then `unsafe` won't be needed to call `Lazy::get`

Don't have time to investigate it right now, and you are welcome to try.
