### ISSUE TITLE
Cut a 2.1.x release which includes the From<Option<T>> for SingularPtrField<T>.

### ISSUE THREAD

**Issue by thedodd** [stepancheg/rust-protobuf#351]
Would be awesome to have a 2.x release which includes the `impl<T> From<Option<T>> for SingularPtrField<T>` code.

**Comment by stepancheg** [comment]
I think that's a good idea. I'll do that. Thanks!

**Comment by stepancheg** [comment]
I think it should be 2.2 release, because of API changes (backwards compatible, but still).

**Comment by thedodd** [comment]
Yea, I can agree with `2.2`. Seems logical. Thanks for the quick response. 

I’ve been using these projects for a long time now. Thanks for all of the awesome work.

**Comment by stepancheg** [comment]
Published `2.2.0`. Thank you for the feedback!
