### ISSUE TITLE
Missing `extern crate protobuf;` in generated files

### ISSUE THREAD

**Issue by Southclaws** [stepancheg/rust-protobuf#353]
I'm trying to get some rust generated for a proto project but the generated files are littered with references to `::protobuf` but there's no `extern` for it so it just throws a ton of errors.

Is there something I've missed? I just followed the example for the `build.rs` method.

**Comment by aldanor** [comment]
Add edition="2018" to your cargo.toml?

**Comment by stepancheg** [comment]
`extern protobuf` should be in `lib.rs` or your crate.

`rust-protobuf` does not generate whole crate, only files to be imported in your crate.

**Comment by stepancheg** [comment]
(Edition 2018 may also help, although it is not required)

**Comment by Southclaws** [comment]
`extern` in the parent module worked, thanks! (little new to Rust so I thought externs had to be immediately local to the dependant!)
