### ISSUE TITLE
Code generator panics when bytes::Bytes are enabled

### ISSUE THREAD

**Issue by dremon** [stepancheg/rust-protobuf#362]
Using the following code generation snippet (from build.rs):

```    
protobuf_codegen_pure::run(protobuf_codegen_pure::Args {
        out_dir: &out_dir.to_string_lossy(),
        input: &slices,
        includes: &[&proto_dir.to_string_lossy()],
        customize: protobuf_codegen_pure::Customize {
            carllerche_bytes_for_bytes: Some(true),
            ..Default::default()
        },
    })
    .expect("protoc");
```

Cargo.toml contains under [dependencies] section:
`protobuf = { version = "2.2", features = ["with-bytes"] }`

This code panics with:

> thread 'main' panicked at 'unexpected field type: ::bytes::Bytes', /home/build/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-codegen-2.2.0/src/field.rs:858

Is there anything missing?

**Comment by stepancheg** [comment]
`oneof` with `bytes` was not implemented. Fixed and published v2.2.1. Thank you for the bugreport!
