### ISSUE TITLE
Args structure should use Paths instead of &strs

### ISSUE THREAD

**Issue by dremon** [stepancheg/rust-protobuf#366]
Currently the protobuf_codegen_pure::Args and protobuf_codegen::Args uses &str for file references which is 1) technically incorrect and 2) not very convenient because user-side conversions are needed.

As far as I see the implementation converts to Path internally anyway. So I'd propose to change the file-related Args fields to generic `<P: AsRef<Path>>` so the existing code won't be broken.

**Comment by dtolnay** [comment]
`Vec<PathBuf>` would work the best in my case.

With the current `&[&str]` based API, I ended up with the following unpleasant conversion function in my build.rs:

```rust
fn paths_to_strs_for_protoc(paths: &[PathBuf]) -> Vec<&str> {
    paths
        .iter()
        .map(|p| p.as_os_str().to_str().unwrap())
        .collect()
}
```

**Comment by dtolnay** [comment]
A way to support paths better without giving up the concise support for string literals like `"protos/a.proto", "protos/b.proto"` would be to turn Args into a builder, similar to what the standard library provides for std::process::Command, and similar to the `cc` crate's Args builder too.

```rust
protoc_rust::Args::new()
    .out_dir("...")
    .input_file("protos/a.proto")
    .input_file("protos/b.proto")
    .run()?;
```

The methods here would all be able to accept `<P: AsRef<Path>>` to work with string literals as well as programmatically constructed PathBufs.
