### ISSUE TITLE
question: protoc Args ergonomics

### ISSUE THREAD

**Issue by azban** [stepancheg/rust-protobuf#380]
relevant code: https://github.com/stepancheg/rust-protobuf/blob/aa54d71d023861d2661f487bf5db5a38157b8003/protoc/src/lib.rs#L15-L40

use case: i want to automatically generate a list of input files based on all files in a given directory. 

current implementation:
```rust
let input_files: Vec<String> = fs::read_dir(Path::new("protos"))
    .expect("could not read protos directory")
    .map(|dir_entry| {
        dir_entry.expect("unable to get entry")
            .path()
            .display()
            .to_string()
    })
    .collect();
let input_files: Vec<&str> = input_files.iter()
    .map(|x| x.as_ref())
    .collect();
protoc_rust::run(protoc_rust::Args {
    out_dir: PROTO_OUTPUT_DIR,
    input: input_files.as_slice(),
    includes: &["protos"],
    customize: Customize {
        expose_oneof: Some(true),
        serde_derive: Some(true),
        ..Default::default()
    },
}).expect("protoc");
```

this seems sort of awkward, and took me a while to figure out the proper way to get `Vec<String>` converted into `&[&str]` (maybe because i'm a rust noob) ([relevant stackoverflow](https://stackoverflow.com/questions/41179659/convert-vecstring-into-a-slice-of-str-in-rust?rq=1)). is there a reason not to use `Vec<String>`? it seems in this case, ergonomics may outweigh performance optimizations.

unsure if it's worth making a backward incompatible change though.

**Comment by dtolnay** [comment]
`Vec<PathBuf>` would work the best in my case. Related issue: #366.

Neither `&str` nor `String` as the element type is good because when building these paths programmatically through the standard library APIs in `std::path` they will end up requiring a nasty conversion like `path.as_os_str().to_str().unwrap()` to get something accepted by protoc_rust::Args. I ended up with the following conversion function in my build.rs:

```rust
fn paths_to_strs_for_protoc(paths: &[PathBuf]) -> Vec<&str> {
    paths
        .iter()
        .map(|p| p.as_os_str().to_str().unwrap())
        .collect()
}
```

**Comment by stepancheg** [comment]
> is there a reason not to use Vec<String>? it seems in this case, ergonomics may outweigh performance optimizations.

The question here is only about ergonomics.

My motivation was this: for simple use cases it is super convenient to write it as simple as this:

```
protoc_rust::run(protoc_rust::Args {
    out_dir: "out",
    input: &["protos/a.proto", "protos/b.proto"],
    includes: &["protos"],
})
```

(This is also the reason why parameters are `str` and not `Path` or `OsStr`)

And for complex cases creating a temporary array is not that hard.

Maybe I'm wrong.

> unsure if it's worth making a backward incompatible change though.

Backward incompatibility is not an issue: version 2 stays as is forever, but lots of things already changed in not yet released version 3, so proposals to change things in version 3 are welcome. (Sometimes I respond slowly, sorry about that).

**Comment by dtolnay** [comment]
@stepancheg good call on keeping the simple cases super convenient. To that end, how would you feel about the API in https://github.com/stepancheg/rust-protobuf/issues/366#issuecomment-479726571? :

```rust
protoc_rust::Args::new()
    .out_dir("out")
    .input("protos/a.proto")
    .input("protos/b.proto")
    .include("protos")
    .run()?;
```

This matches the API we have arrived at for the `cc` crate which similarly needs to deal with constant strings at the same time as programmatic filesystem paths:

- https://docs.rs/cc/1.0.35/cc/index.html#examples

as well as more loosely the std::process::Command builder:

- https://doc.rust-lang.org/std/process/struct.Command.html

**Comment by stepancheg** [comment]
@dtolnay personally I don't like builder pattern, but if users want it, I'm OK with it.
