### ISSUE TITLE
Compile error: no `merge_from_str` in `text_format`

### ISSUE THREAD

**Issue by bcoopers** [stepancheg/rust-protobuf#382]
I'm using version 2.2.5 from Cargo, if I do any of the following:

```
use protobuf::text_format::print_to_string;
use protobuf::text_format::print_to;
use protobuf::text_format::fmt;
use protobuf::text_format::quote_escape_bytes;
```

they all work fine, however if I do:

`use protobuf::text_format::merge_from_str;`

I get compile error:

> error[E0432]: unresolved import `protobuf::text_format::merge_from_str`         
>   --> src/main.rs:10:5                                                          
>    |                                                                            
> 10 | use protobuf::text_format::merge_from_str;                                 
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `merge_from_str` in `text_format`

**Comment by bcoopers** [comment]
I went and viewed my internal crates.io cache of the source code and it looks like it's still using the version from May when text_format was a single.rs file rather than a directory

https://github.com/stepancheg/rust-protobuf/commit/9e86dcd2b697740df6993545a18a408b4caeec3f#diff-8c833373a7f87fdcea0bb6eba3fbfcfe

Any way we can request the current functionality be released on crates.io?

**Comment by stepancheg** [comment]
Text format is implemented using reflection.

Reflection for mutability is **not** implemented in the stable 2.x branches.

And porting this change to stable branch is either impossible or very hard without breaking backward compatibility.

So the easiest way to fix it is to release version 3.

The major drawback against releasing version 3 is the fact that version 2 was released just 7 months ago.

And also I have some uncertainties about APIs in version 3. E. g. I would really reduce generated code size (see https://github.com/stepancheg/rust-protobuf/issues/339) as a feature of version 3, but I don't yet know how to do it.
