### ISSUE TITLE
Expose API to .proto parser

### ISSUE THREAD

**Issue by stepancheg** [stepancheg/rust-protobuf#386]
`protobuf-codegen-pure` is able to parse `.proto` files. This information, however, is not available as Rust API, which could be useful for grpc codegen.

**Comment by ashthespy** [comment]
Do you still have plans to implement this? We are trying to reduce build times by rebuilding only when the proto files have changed. Currently this is done my checking the checksum of the `.proto` files against the last hash. However, this means a manual rebuild is required when upgrading `protobuf_codegen` versions. 

An alternative suggested is https://github.com/librespot-org/librespot/pull/293 - the `*.proto` files are parsed and the Rust counterpart is generated in memory each build, but written to file only if there is a change from the current  `*.rs` files.  Currently this is by using `protobuf_codegen::gen` along with `protobuf_codegen_pure::parse_and_typecheck` as done internally by `protobuf_codegen_pure`. An external API for this would make it easier for such a scenario! 

PS: If you see a more efficient way of achieving the same end goal, am all ears!

**Comment by ashthespy** [comment]
Just in case you missed this! 
@stepancheg any suggestions?

**Comment by stepancheg** [comment]
`protobuf-codegen` in version 3 exposes some APIs.
