### ISSUE TITLE
MIT or BSD-2 license?

### ISSUE THREAD

**Issue by pacman82** [stepancheg/rust-protobuf#393]
protobuf Cargo.toml specifies MIT License, top level directory contains BSD License. Is this as intended?

**Comment by stepancheg** [comment]
No, it is an accident. I don't care much which license is it. Need to be fixed though.

**Comment by pacman82** [comment]
Should I open a PR which changes the top level license to MIT/APACHE-2 as stated in the metadata?

**Comment by stepancheg** [comment]
I'd appreciate that! From my understanding all these licenses are more or less the same, so please change top-level license or Cargo metadata whichever is better or easier.
