### ISSUE TITLE
data is totally messed up.

### ISSUE THREAD

**Issue by NikosEfthias** [stepancheg/rust-protobuf#396]
i have following code 

```rust 
    let mut msg = vec![];
    let mut str = protobuf::CodedOutputStream::vec(&mut msg);
    let mut rmsg = user_manager::user::user_data::new();
    rmsg.set_id("1234".into());
    rmsg.set_nick("test".into());
    str.write_message(1, &rmsg).unwrap();
    str.flush().unwrap();
    println!("{:?}", msg);
    let test: register_msg = protobuf::parse_from_bytes(&msg[..]).unwrap();
    println!("serialized: {:?}\noriginal: {:?}", test, rmsg);
```
```proto
message user_data{
	string id           = 1; //required
	string nick         = 2;
	string theme        = 3;
	string admin_id     = 4;
	string lang         = 5;
	double credit       = 6; //required
	double bonus_credit = 7; //required
};
```
what i get printed is as following
![image](https://user-images.githubusercontent.com/9097437/54007973-fb0a8980-417d-11e9-8ec7-b75a8ae28968.png)
It just doesnt make any sense. Field number one is not even nick why does it write the entire thing under the nick i have no clue. Seems like the entire thing is messed up but i cannot understand if im doing something wrong or this is a bug in the library.

**Comment by mbrubeck** [comment]
If you change `write_message(1, &rmsg)` to `write_message_no_tag(&rmsg)` then you will get the correct output.  Otherwise you are writing both the tag and the message, and you will need to read them separately.

**Comment by mbrubeck** [comment]
Or simply use `let mut msg = rmsg.write_to_bytes().unwrap();`

**Comment by NikosEfthias** [comment]
Thanks the issue is resolved by using write_to_bytes
