### ISSUE TITLE
Use protobufs comments to generate rustdoc comments

### ISSUE THREAD

**Issue by apognu** [stepancheg/rust-protobuf#402]
Sometimes, generated types are part of a public API that needs to be documented. Right now, comments are simply ignored, and therefore, crate documentation displays nothing for the generated code.

It would be great if we could generate module, struct and field docstrings along with the model itself.

This has been mentioned [in comments](https://github.com/stepancheg/rust-protobuf/issues/271#issuecomment-376884478), but have not found a related issue, so here it is.

In that comment, you asked if was deemed something important; from my standpoint, being able to properly document potentially public interfaces is important. (**EDIT:** just noticed it was the owner of `protobuf-parser` that wrote that comment).

**Comment by stepancheg** [comment]
#421 is partial implementation, reopening.
