### ISSUE TITLE
Better default for protoc_rust::Args::out_dir

### ISSUE THREAD

**Issue by dtolnay** [stepancheg/rust-protobuf#403]
https://github.com/stepancheg/rust-protobuf/blob/a1333bf024b39a4f1898a873a0074cde9a5f3d00/protoc-rust/src/lib.rs#L20-L23

<br>

The current default value for `out_dir` via `Args::default()` is the empty string. I have not found this to be a good default. I would expect for the default to be either:

```rust
PathBuf::from(env::var_os("OUT_DIR")?)
```

or:

```rust
PathBuf::from(env::var_os("OUT_DIR")?).join("protos")
```

in the case that $OUT_DIR is set, which Cargo always sets for build scripts.

**Comment by dtolnay** [comment]
This will likely require replacing `out_dir: &'a str` with the semantically more correct `out_dir: PathBuf`. I would consider this a beneficial change (in combination with #366).

**Comment by stepancheg** [comment]
`Args` builder is merged.

I think implicit getenv could be dangerous, but a shortcut could be useful, e. g.

```
Args::new()
    .out_dir_cargo("subdir") // $OUT_DIR/subdir
```

(Better operation name suggestions welcome)

**Comment by stepancheg** [comment]
API is very different in rust-protobuf=3.
