### ISSUE TITLE
write_to_bytes is infallible but returns a Result

### ISSUE THREAD

**Issue by sunshowers** [stepancheg/rust-protobuf#404]
https://github.com/stepancheg/rust-protobuf/blob/81152b3b93c880991f2e332c2c218cbe668251b2/protobuf/src/core.rs#L114

This is infallible because the `Bytes` code path in `CodedOutputStream` can never fail. Could the unreachable error case become a panic and the return type be updated to indicate that?

**Comment by stepancheg** [comment]
It can return an error when writing a `proto2` message with not all require fields initialized.

We can add a comment stating that is will never fail when using proto3 or when using proto2 without required fields. PR is welcome.

**Comment by thomaseizinger** [comment]
Would it be possible to implement a dedicated trait for proto3 messages that has an infallible version of this function?

**Comment by stepancheg** [comment]
This is not trivial. proto3 message may include proto2 messages for example.

Maybe it can implement the trait if no dependencies are proto3.

**Comment by thomaseizinger** [comment]
> This is not trivial. proto3 message may include proto2 messages for example.
> 
> Maybe it can implement the trait if no dependencies are proto3.

Thanks for the quick response! That is indeed not trivial then.
