### ISSUE TITLE
Help with codegen

### ISSUE THREAD

**Issue by coryng** [stepancheg/rust-protobuf#405]
How could I use the codegen plugin with "protoc --rust_out=..." that turns on the generator_accessors and generate_getter options?

Appreciate your help.
C

**Comment by stepancheg** [comment]
Two ways.

**Either** include into your proto file something like:

```
import "rustproto.proto";

option (rustproto.carllerche_bytes_for_bytes_all) = true;
option (rustproto.carllerche_bytes_for_string_all) = true;
```

**Or** pass arguments using command line `protoc` argument:

```
protoc --rust_out='carllerche_bytes_for_bytes=true carllerche_bytes_for_string=true':. ./a.proto
```

You are welcome.
