### ISSUE TITLE
Reflection to get mutable message

### ISSUE THREAD

**Issue by coryng** [stepancheg/rust-protobuf#407]
Hello,

In "protobuf::reflect::FieldDescriptor", the function "pub fn mut_message<'a>(&self, _m: &'a mut Message) -> &'a mut Message" is not yet implemented.  Could you please let us know if you have any plan to implement it? if not, is there any work-around?
I'd like to use reflection to set all fields in a Message to its default value (traverse the message and use get_singular_field_or_default() on FieldDescriptor).

Thank you very much,
C

**Comment by stepancheg** [comment]
It is implemented in master. But it is not possible (or very hard) to backport it to the stable version without breaking backwards compatibility.

It will be released in the next major version (3).

I think next major version will be released in a couple months.

JFYI, before releasing next major version I'd like to fix this: https://github.com/stepancheg/rust-protobuf/issues/339 But I don't know how to fix it.

> I'd like to use reflection to set all fields in a Message to its default value

Why? Maybe you simply want to use `syntax = "proto3"` where fields have no flag, and initialized to zero.

**Comment by coryng** [comment]
Thanks for your help.  I'm using Master branch, but I still see "unimplemented!()" (protobuf\src\reflect\field.rs line 170).

**Comment by stepancheg** [comment]
Looking...

**Comment by stepancheg** [comment]
My bad.

You can now do `get_message()`, clone it, modify it, and then call `set_singular_field()`. Obviously, it would be somewhat expensive.

Looking how hard would it be to implement `mut_message`.

**Comment by stepancheg** [comment]
Implemented in 3d532ddf6afd0bf9b18f9cb5a6bd314e982b2915.
