### ISSUE TITLE
could not find `types` in `super`

### ISSUE THREAD

**Issue by SOF3** [stepancheg/rust-protobuf#409]
I have build.rs like this:
```rust
extern crate protobuf_codegen_pure;

use protobuf_codegen_pure::{Args, Customize};

fn main() {
    protobuf_codegen_pure::run(Args {
        out_dir: "src/protocol",
        input: &["proto/buf.proto"],
        includes: &["proto"],
        customize: Customize::default(),
    }).unwrap();
}
```

I defined some messages in proto/buf.proto and proto/types.proto (the latter imported from buf.proto). It generates code like this in src/protocol/buf.rs:

```rust
#[derive(PartialEq,Clone,Default)]
pub struct CubeTypeDef {
    // message fields
    cubes: ::protobuf::RepeatedField<super::types::CubeDef>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}
```

The corresponding protobuf code:
```proto
message CubeTypeDef {
    repeated CubeDef cubes = 1;
}
```

I included `protobuf = "2.5"` in my Cargo.toml. But when I compiled it, `super::types` cannot be resolved. Did I miss anything?

I am running on Windows.

**Comment by SOF3** [comment]
Actually, it doesn't even work when I compile the examples in this repo.

**Comment by SOF3** [comment]
Happens on Travis-CI too. Here is a reproducible build: https://travis-ci.com/SOF3/cube-engine/jobs/197125317

**Comment by fan-tom** [comment]
The same on MacOS

**Comment by nnmm** [comment]
Could be related to https://github.com/stepancheg/rust-protobuf/issues/260

**Comment by stepancheg** [comment]
Closing due to old age. Please reopen if the issue still exists.
