### ISSUE TITLE
Incorporate OOM fix in next release (v2.6.0)

### ISSUE THREAD

**Issue by smoelius** [stepancheg/rust-protobuf#411]
Please incorporate commit https://github.com/stepancheg/rust-protobuf/commit/66a22c88d7efb762a7e2390f2bfdb275c199434c from master in the next release (v2.6.0).

In particular, please incorporate the following OOM fix:
https://github.com/stepancheg/rust-protobuf/commit/66a22c88d7efb762a7e2390f2bfdb275c199434c#diff-03da03412d4490720c45da0a6f43d56cR36
https://github.com/stepancheg/rust-protobuf/blob/66a22c88d7efb762a7e2390f2bfdb275c199434c/protobuf/src/stream.rs#L36-L38
https://github.com/stepancheg/rust-protobuf/commit/66a22c88d7efb762a7e2390f2bfdb275c199434c#diff-03da03412d4490720c45da0a6f43d56cR640
https://github.com/stepancheg/rust-protobuf/blob/66a22c88d7efb762a7e2390f2bfdb275c199434c/protobuf/src/stream.rs#L640-L656
We hit this OOM error while fuzzing a project that uses the current release, v2.5.0.  Patching v2.5.0 with the above commit made the error go away.  It would be convenient if the commit were incorporated in an official release.

Thank you.

**Comment by stepancheg** [comment]
Cherry-picked into v2.6 branch as f32ac1cdf5435189ba0df6f9831386b246eec5e9.

**Comment by stepancheg** [comment]
Published version 2.6.0.

**Comment by dvdplm** [comment]
Would you consider back porting this fix to 1.x?

**Comment by stepancheg** [comment]
Merged into v1.7 branch as a839f7b049ca91e6842df8c320215e5378a7d9a5. [Testing](https://travis-ci.org/stepancheg/rust-protobuf/builds/534559725)...

**Comment by stepancheg** [comment]
Published 1.7.5 with the same fix.

**Comment by stepancheg** [comment]
FYI ef888e06b8d5324449dfdd6d2d818cad872670cc fixes the same issue when using both feature `with-bytes` and `carllerche_bytes_for_xxx` codegen option.

Need to backport it 2.6 and 1.7 too.

**Comment by smoelius** [comment]
Thanks, @stepancheg !

**Comment by stepancheg** [comment]
Published 2.6.2 with a fix for `bytes::Bytes` fields.
