### ISSUE TITLE
Basic serde_derive support usage question

### ISSUE THREAD

**Issue by jugabee** [stepancheg/rust-protobuf#412]
I'm new to Rust and I've been struggling with getting serde_derive support working.  I think it boils down to the fact that my compiled proto file can't find the serde dependency.  The compiler states: "cannot find derive macro `Deserialize` in this scope" or "The attribute serde is currently unknown to the compiler".  It isn't clear to me how to add something like *use serde_derive::{Deserialize, Serialize};* to the compiled protos during the build process.

I've enabled the serde option as described in the readme. I'm also using the master branch for rust-protobuf, here is my cargo file: 

```
...
edition = "2018"

[dependencies]
protobuf = { git = "https://github.com/stepancheg/rust-protobuf.git", branch = "master" }
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"

[build-dependencies]
protoc-rust = { git = "https://github.com/stepancheg/rust-protobuf.git", branch = "master" }
```
My build.rs file looks like this:

```
use protoc_rust::Customize;

fn main() {
    protoc_rust::Args::new()
        .out_dir("src/")
        .inputs(&["proto/message.proto"])
        .include("proto")
        .customize(Customize {
            serde_derive: Some(true),
            ..Default::default()
        })
        .run()
        .expect("protoc");
}
```
 And finally my main.rs file:

```
use protobuf::Message;
use serde_derive::{Deserialize, Serialize};
use serde_json;

mod message;

fn main() {
    let m = message::RequestContext::new();
    println!("{:?}", serde_json::to_string(&m).unwrap());
}
```

Sorry if I missing something obvious. Any help or examples would be very appreciated!

**Comment by Ten0** [comment]
The generated code places guards:
```
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
```
for the `Serialize`/`Deserialize` derives.

This feature has to be enabled for it to work.

That being said, I don't know how exactly to enable that feature for the current crate.

**Comment by jugabee** [comment]
Thanks for your suggestions @Ten0.  I went ahead and tried switching to protobuf-codegen and also adding the [features] lines to Cargo.toml.  I'm still running into the same errors.  Were you able to get this working by enabling the feature for your whole crate?

**Comment by Ten0** [comment]
Yes, given that you didn't have `protobuf-codegen` as a dependency before (and no matter whether you add it or not), adding these 3 lines in your crate's package.json should fix it.

Did you check the generated code ? Can you confirm that the issue is indeed that these guards are present ?

**Comment by jugabee** [comment]
Here's the top of my generated protos after adding the feature to Cargo.toml -- I didn't notice any guards present throughout the file: 

```
// This file is generated by rust-protobuf 3.0.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]

#[derive(PartialEq,Clone,Default)]
#[derive(Serialize, Deserialize)]
pub struct RequestContext {
    // message fields
    pub event_type: ::std::string::String,
    pub domain_name: ::std::string::String,
    pub stage: ::std::string::String,
    pub connection_id: ::std::string::String,
    // special fields
    #[serde(skip)]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[serde(skip)]
    pub cached_size: ::protobuf::CachedSize,
}
```

**Comment by davidgraeff** [comment]
Use
```rust
#[macro_use]
extern crate serde_derive;
```

This is a rust-2015 pattern to make macros available to the entire crate. The idiomatic way in 2018 is indeed to `use`-include macros instead like you did it:

```rust
use serde_derive::{Deserialize, Serialize};
```

**Comment by jugabee** [comment]
@davidgraeff Thanks! That seems to have resolved the issue for me.
