### ISSUE TITLE
ParseErrorWithLoc is private

### ISSUE THREAD

**Issue by scottlamb** [stepancheg/rust-protobuf#422]
In current master (76c8892 to be precise), `protobuf::text_format::parse_from_str` returns `protobuf::text_format::parse::ParseErrorWithLoc` on error. AFAIK, I can't do anything with this for two reasons:

   * it's in a private mod. (`protobuf::text_format::parse::parse_from_str` doesn't warn about returning a private type because it's in that mod, too. The `pub use self::parse::parse_from_str;` in `protobuf::text_format` doesn't warn about this because...? I'm not sure. Maybe that's an oversight in rustc itself.) I think this is a total dealbreaker for my code knowing anything other than "there was an error".
   * it doesn't implement `std::error::Error`. This one isn't a dealbreaker, but it'd be more convenient if it did implement this so I could just use `?` in my function that returns a `failure::Error` and have it be automatically converted.

**Comment by stepancheg** [comment]
> it's in a private mod

The function is [reexported](https://github.com/stepancheg/rust-protobuf/blob/e1bf745c4137d0b4b67a2d90ed8c85d01a0f9347/protobuf/src/text_format/mod.rs#L38).

> it doesn't implement std::error::Error

Patch welcome.
