### ISSUE TITLE
Provide type conversion between protobuf well known types and rust types

### ISSUE THREAD

**Issue by alekseysidorov** [stepancheg/rust-protobuf#425]
All of types in wrappers.rs can be mapped with Rust types without any loss. Thus we can implement `From` between them.

For example:
```rust
impl From<String> for StringValue { ... }
// And back
impl From<StringValue> for <String> { ... }
```
And also, it seems that this change will not break backward compatibility.

**Comment by stepancheg** [comment]
Sounds good. Patch welcome!

**Comment by alekseysidorov** [comment]
Ok, I will send it later.
