### ISSUE TITLE
Alternative enum implementation

### ISSUE THREAD

**Issue by zdevwu** [stepancheg/rust-protobuf#434]
First of all, thanks for this great repository @stepancheg!

I find my self wanting to implement the enum slightly differently for some reasons:
1. simplified `match`.
2. unknown value from future proto definition expansion is kept.

something like:
```rust
pub enum EnumType {
    UNKNOWN = 0,
    VALUE1 = 1,
    VALUE2 = 2,
    Undefined(i32),
}

impl ::protobuf::ProtobufEnum for EnumType {
    ....
    fn from_i32(value: i32) -> EnumType {
        match value {
            0 => EnumType::UNKNOWN,
            1 => EnumType::VALUE1,
            2 => EnumType::VALUE2,
            i => EnumType::Undefined(i),
        }
    }
    ....
}
```
So in the place where I want to `match` the emun value, instead of matching for `option` as well as the enum, I can just do:
```rust
fn do_some_thing() {
    match property.enum_type_value {
        EnumType::UNKNOWN => {},
        EnumType::VALUE1 => {},
        EnumType::VALUE2 => {},
        EnumType::Undefined(i) => {
            println!(format!("undefined enum type value {}", i));
        },
    }
}
```
compares to:
```rust
fn do_some_thing() {
    match property.enum_type_value {
        Some(value) => {
            match value {
                EnumType::UNKNOWN => {},
                EnumType::VALUE1 => {},
                EnumType::VALUE2 => {},
            }
        },
        None => {
            println!("undefined enum type value, and it is lost");
        },
    }
}
```

I'm new to rust, so the code gen macro is a bit overwhelming to me, I could not figure out where I can try this change unfortunately. I think this implementation certainly simplifies the usage of enum utilising of the more powerful rust enum compares to other languages, and makes the generated code more future prove following the same concept how protobuf definition can be expanded.

Thanks!

**Comment by stepancheg** [comment]
In master enums are stored in `ProtobufEnumOrUnknown<E: ProtobufEnum>` ([code](https://github.com/stepancheg/rust-protobuf/blob/e9f13aa4c42a38a76aa81fa7be19b55ffc233426/protobuf/src/enums.rs#L43)).

This seems to work better than your proposed implementation (because it guarantees that known value does not fall into `Unknown` variant).

But I have no idea how to port it to the stable branch.

**Comment by zdevwu** [comment]
```protobuf
pub enum EnumType {
    Unknown = 0, // this is different from Undefined(i32) bellow
    VALUE1 = 1,
    VALUE2 = 2,
    Undefined(i32),
}
```
Or maybe this is better for your understanding:
```protobuf
pub enum EnumType {
    ZeroValue = 0, // this is different from Unknown(i32) bellow
    VALUE1 = 1,
    VALUE2 = 2,
    Unknown(i32),
}
```
```rust
impl ::protobuf::ProtobufEnum for EnumType {
    ....
    fn from_i32(value: i32) -> EnumType {
        match value {
            0 => EnumType::ZeroValue, // this is pre-defined in protobuf
            1 => EnumType::VALUE1,
            2 => EnumType::VALUE2,
            i => EnumType::Unknown(i), // this store the not-defined value
        }
    }
    ....
}
```
The *known* value or should I say *predefined* value in the protobuf definition will never fall into unkown or undefined. Use the proposed implementation the `ProtobufEnumOrUnknown` is then not needed.

**Comment by stepancheg** [comment]
It is not possible to guarantee that known value does not fall into the unknown. E. g. in some user code using the same enums. E. g.

```
let v: EnumType = EnumType::Unknown(2); // legit statement

...

match v {
    EnumType::ZeroValue => println!("action zero"),
    EnumType::VALUE1 => println!("action one"),
    EnumType::VALUE2 => println!("action two"),
    EnumValue::Unknown(..) => panic!("uh oh unknown"),
}
```

This code panics at "unknown" while it should execute "action two", because it is the same enum value. I don't know any way to prevent this behavior.

In addition to that, `EnumValue::Unknown(..)` needs to be a case in each `match` expression which might be inconvenient.

**Comment by zdevwu** [comment]
I see your point. However, even if it is legit, it would seem strange to see someone initilize the `EnumType:Unknown`, it is more that the *unknown* is deserialized by the generated code and needs to be handled.

And speaking of throughly handling the protobuf enum values. If someone doesn't use the `ProtobufEnumOrUnknown`, the unknown value from future probotbuf version will not be detected in the **current** code. That is the main reason for my proposal. It is not perfect either, say for example what should be the reserved field name if user happens to define a enum field name *Unknown* for value 0, and your legit statement as well of couse. But I think it is easier to just have one match instead of nested matches for all the possible cases.

**Comment by stepancheg** [comment]
Another problem with the proposed approach is that it is also backwards-incompatible. E. g. match statements will break:

```
enum Foo {
  BAR = 0;
  BAZ = 1;
}
```

```
match foo {
    Foo::BAR => {},
    Foo::BAZ => {},
}
```

> the unknown value from future protobuf version will not be detected in the current code

Unfortunately, that's true.

**Comment by stepancheg** [comment]
A lot of changed in generated code.

rust-protobuf=3 is on the way, if you have suggestions, please open another issue. Closing this due to old age.
