### ISSUE TITLE
how can i create a Message Instance by message full name?

### ISSUE THREAD

**Issue by egmkang** [stepancheg/rust-protobuf#445]
```cpp
google::protobuf::Descriptor* desc =
    google::protobuf::DescriptorPool::generated_pool()
        ->FindMessageTypeByName("mypkg.MyType");
google::protobuf::Message* message =
    google::protobuf::MessageFactory::generated_factory()
        ->GetPrototype(desc)->New();

```

how can i create a Message instance by `mpkg.MyType`?
thanks a lot

**Comment by stepancheg** [comment]
It's not possible. In particular, because there are no global constructors in Rust. It's not possible to create a global registry of all messages at runtime.

However, what we could do is to provide API to find a message in the module. So users could explicitly enumerate the modules.

**Comment by egmkang** [comment]
@stepancheg 
thanks to reply.

i write a build tools to generate this global factory,  which can solve my problem, but not a common solution.

 https://crates.io/crates/protobuf_message_factory

**Comment by stepancheg** [comment]
Well, yes, a global factory cannot be implemented universally, but my suggestion stays:

Inside rust-protobuf implement something like:

```
struct FileDescriptor { ... }

impl FileDescriptor {
  fn get_messages(&self) -> &[MessageDescriptor] { ... }
}
```

This should help with that factory of yours: you will only need enumerate a list of files, not all messages.

This feature should be implemented anyway.

Help is welcome, but it is a quite complicated task (to design API and keep it backwards compatible).

**Comment by stepancheg** [comment]
Latest rust-protobuf in master supports `FileDescriptor` reflection. Version 3 with all of it will be released soon.

Feedback is welcome.
