### ISSUE TITLE
JSON parsing fails when json_name is not the camel-cased field name

### ISSUE THREAD

**Issue by samschlegel** [stepancheg/rust-protobuf#447]
This happens due to this assertion: https://github.com/stepancheg/rust-protobuf/blob/34a4ba1cdaccf2612747573d490d731b9fc3600e/protobuf/src/reflect/message.rs#L124

In the Java and Go implementations this restriction doesn't exist. Is there a reason it does here?

**Comment by stepancheg** [comment]
> Is there a reason it does here?

Sanity check. Can you please provide a case when this assertion fires?

Because if it fires, it means, rust-protobuf does not map field names correctly, and it could be an issue for pure-rust codegen.

**Comment by stepancheg** [comment]
Ah, I see, JSON name can be specified in the annotation. It must be a recent thing.

https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by samschlegel** [comment]
I fixed it for protoc-rust in #448, but it looks like it also caught the pure-rust codegen not handling this.

**Comment by stepancheg** [comment]
So, yes, pure-rust codegen should be fixed too. Can you do it please or provide some workaround to mute tests and TODO?

**Comment by samschlegel** [comment]
Can do later today 👍
