### ISSUE TITLE
How to nest structs with rust-protobuf?

### ISSUE THREAD

**Issue by sjama** [stepancheg/rust-protobuf#451]
Given the proto file

```
message Customer {
  string id = 1;
  string name = 2;
  Address address = 3;
}

message Address {
  string street = 1;
  string city = 2;
}

```
I can use the generated code to construct individual structs for the customer and address messages.

```
let mut customer: pb::Customer = pb::Customer::new();
customer.id = "1".to_string();
customer.name = "John Smith".to_string();

let mut address: pb::Address = pb::Address::new();
address.street = "123 Hale Street".to_string();
address.city = "London".to_string();

```
But I don't know how to construct a full customer object that includes the address.
This is because the address field in customer struct has the type `"protobuf::SingularPtrField"` in the generated code, which I don't know what to do with.

**Comment by stepancheg** [comment]
```
customer.set_address(address);
```
or if field is public (depending on which versions do you use)

```
customer.address = SingularPtrField::new(address);
```

**Comment by stepancheg** [comment]
This is rustdoc for `SingularPtrField` [here](https://docs.rs/protobuf/2.8.1/protobuf/struct.SingularPtrField.html#method.some)

**Comment by sjama** [comment]
Thanks. I used `customer.address = SingularPtrField::some(address);`

**Comment by stepancheg** [comment]
... also, you can do

```
customer.address = Some(address).into();
```

**Comment by sjama** [comment]
Ok, I switched to  `customer.address = Some(address).into();`
