### ISSUE TITLE
FYI - Created new rust-protobuf example

### ISSUE THREAD

**Issue by jgarzik** [stepancheg/rust-protobuf#452]
This seemed like the best rust+protobuf project, but being a rust novice, I felt the rust-protobuf crate lacked some good paste-and-go examples working with various rust data types + protobufs using your `rust-protobuf` crate, so whipped this up: https://github.com/jgarzik/rust-protobuf-example

(no action needed - just fyi - review & criticism welcome - thanks for working on rust-protobuf)

**Comment by stepancheg** [comment]
Looks good.

Do you want to submit a PR into `stepancheg/rust-protobuf/protobuf-examples`?
