### ISSUE TITLE
2.9 was a semver-major breakage

### ISSUE THREAD

**Issue by kornelski** [stepancheg/rust-protobuf#453]
protobuf 2.9 release has broken prometheus 0.7.

Could you yank it and re-release it as 3.0?

**Comment by tomaka** [comment]
It has also broken libp2p: https://github.com/libp2p/rust-libp2p/issues/1259

**Comment by stepancheg** [comment]
> It has also broken libp2p: libp2p/rust-libp2p#1259

`.proto` files need to be regenerated.

**Comment by stepancheg** [comment]
With `prometheus` the issue is the same: `.proto` files need to be regenerated.

Are you sure that generated files must be backwards compatible? Because it makes changes in protobuf almost impossible.

**Comment by Ekleog** [comment]
What about saying “from now on `.proto` files need to be generated from `build.rs`” and release what currently is 2.9 as 3.0 with this additional caveat?

**Comment by stepancheg** [comment]
Yanked the version.

**Comment by stepancheg** [comment]
How about releasing version 2.9 with making all generated files emit a warning about code need to be regenerated? (Copy all functions to new names, and make old names deprecated)

And release 2.10 with new features in a couple of weeks?

**Comment by tomaka** [comment]
What would be wrong with releasing 3.0 instead?

**Comment by stepancheg** [comment]
@tomaka don't have enough large features implemented to release 3.0.

**Comment by kornelski** [comment]
That's not what semver means. It doesn't increment on features, it increments on any incompatibilities.

**Comment by dayfine** [comment]
When will this be re-released? I actually want to use 2.9

**Comment by fbernier** [comment]
@stepancheg If you plan on having other releases before 3.0, could we add back the rest of the non-breaking stuff that was in 2.9.0 such as json printing?

**Comment by stepancheg** [comment]
Reflection changes won't be ported to version 2, because of multiple backwards compatibility issues.

Now I'm preparing to release rust-protobuf version 3.

This is the master task: https://github.com/stepancheg/rust-protobuf/issues/518

The new release is a good place to fix various API issues, so feedback is highly appreciated.
