### ISSUE TITLE
Implement pack_from/unpack_to for google.protobuf.Any

### ISSUE THREAD

**Issue by michael-kernel-sanders** [stepancheg/rust-protobuf#455]
The standard protobuf implementation provides methods to pack and unpack Any values.  These methods automatically set and check the type_url field.

https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#any

**Comment by stepancheg** [comment]
Sounds right. Patch welcome.

Should be relatively easy for builtin types, however, implementing type registry would require some design.

**Comment by stepancheg** [comment]
e91bf7eb20abe68a7b29264b864e2cecbbb3f769

**Comment by stepancheg** [comment]
Published in version 2.13.0.
