### ISSUE TITLE
Operations removed from RuntimeTypeDynamic

### ISSUE THREAD

**Issue by shadowng** [stepancheg/rust-protobuf#456]
Hi,

Could you please let me know how to get EnumDescriptor and MessageDescriptor since they are removed? (latest master branch)

https://github.com/stepancheg/rust-protobuf/commit/fb0de59dc027b9c3b845dfc4838bb922ebf0a7a5

Thanks so much,
C

**Comment by shadowng** [comment]
Any idea on this item?  Thank you.

**Comment by stepancheg** [comment]
In current master API is very different and should be good enough to obtain anything.
