### ISSUE TITLE
using a grpcio::Channel twice

### ISSUE THREAD

**Issue by donpdonp** [stepancheg/rust-protobuf#458]
I'm new to rust so maybe I'm overlooking something simple. When a channel is used to create a Client for a protobuf object with rpc calls, that channel is consumed/moved. The new() function doesnt want to take a pointer to a channel. Is there another way to use that same channel in another Client?

```
let chan_builder = ChannelBuilder::new(env);
chan_builder.secure_connect(ip_address, channel_cred)
let nc = NodeClient::new(ch);
let sc = StatClient::new(ch); <- error ch was moved
```

**Comment by stepancheg** [comment]
I this is the question for grpcio crate, not for rust-protobuf?

**Comment by donpdonp** [comment]
Oh you are right, thank you.
