### ISSUE TITLE
Recursive proto to rust?

### ISSUE THREAD

**Issue by Jasperav** [stepancheg/rust-protobuf#464]
I have a directory which contains other directories which contain .proto files. In the end, I want to have generated .rs files from that proto files in 1 folder. In the examples, I see I need to manually add all the protobuf files, this isn't really what I want, because that is too much handwork.

Is it possible to just say: this is a directory, find and generate all rs files and put them into the output directory?

**Comment by stepancheg** [comment]
If you are using `build.rs` you write like three lines of code to find `.proto` files and supply then to code generator.

If you are using shell scripts to invoke code generator, something like `find` can be used for the automation.

I think built-in globbing does not fit in protobuf codegen API.
