### ISSUE TITLE
bytes 0.5 support

### ISSUE THREAD

**Issue by sunng87** [stepancheg/rust-protobuf#465]
With release of tokio 0.2 and bytes 0.5, the old api for getting `&[u8]` from `BufMut` is removed. It would be nice for rust-protobuf to catch up with latest bytes api.

**Comment by stepancheg** [comment]
Upgraded bytes to 0.5 in master 58ba9b615ea33a7f9f0a8394701160c87472b0b1

**Comment by stepancheg** [comment]
Published version 2.10.0.
