### ISSUE TITLE
The protobuf version checking is too strict

### ISSUE THREAD

**Issue by Tim-Zhang** [stepancheg/rust-protobuf#466]
What's you consideration about the limitation [generated files compatible only with the same version of runtime](https://github.com/stepancheg/rust-protobuf/commit/2ab4d50c27c4dd7803b64ce1a43e2c134532c7a6)?

People are used to import protobuf by writing `protobuf = "2.8.0"` in cargo.toml, and rust would use a version between 2.8.0 and 3.0.0, so the incompatible errors may occurred frequently. 

It's inconvenient to regenerate codes for the minor/patch version updates, and the codes generated by protobuf-codegen 2.8.1 should be compatible with protobuf 2.8.0 if we follow the rust convention.

**Comment by stepancheg** [comment]
It's hard to:
* make API used in generated code backwards compatible
* it's hard to check that changes do not break generated code

Version 2.9 was the version where strict version checking was introduced.

However, a lot of projects broke, so I had to yank that version.

Maybe we should revert this restriction. It is not clear now.

But anyway, the best way to use rust-protobuf is to generate `.rs` files from `.proto` files from `build.rs`.

**Comment by Tim-Zhang** [comment]
I think we should revert the restriction and if there is any compatible problems in future versions just increase the major version.

**Comment by stepancheg** [comment]
OK, I did not intend to put version check in 2.10 (this was actually the reason why 2.9 was yanked). Going to revert it now.

**Comment by stepancheg** [comment]
Published 2.10.1
