### ISSUE TITLE
Use one definition for Unexpected EOF error

### ISSUE THREAD

**Issue by FedericoPonzi** [stepancheg/rust-protobuf#468]
From [here](https://github.com/stepancheg/rust-protobuf/blob/master/protobuf/src/buf_read_iter.rs#L306):
```
                buf_read.read_exact(buf)?;
            }
            _ => {
                return Err(ProtobufError::WireError(WireError::UnexpectedEof));
```
Thes issue here is that inside [read_exact](https://doc.rust-lang.org/src/std/io/impls.rs.html#230):
```
return Err(Error::new(ErrorKind::UnexpectedEof,
                                  "failed to fill whole buffer"));
```
So I'm wondering if it makes sense to have two duplicate errors. My issue is that at some unexpected point in time the stream I'm reading from might get closed. Thus I need to write some ugly nested match to catches these two.

Another way to do this, would be to change the [`From<io::Error> for ProtobufError`](https://github.com/stepancheg/rust-protobuf/blob/master/protobuf/src/error.rs#L81) to match the UnexpectedEOF, and return a ProtobufError::UnexpectedEof instead of IoError.

**Comment by FedericoPonzi** [comment]
Also, according to [this](https://github.com/stepancheg/rust-protobuf/blob/master/protobuf/src/error.rs#L50) Eof is not really about a malformed input IMO

**Comment by stepancheg** [comment]
Closing due to old age, sorry I did not respond.

Please reopen if the issue still exists.
