### ISSUE TITLE
Inconsistency between `protoc` and build.rs

### ISSUE THREAD

**Issue by DazWilkin** [stepancheg/rust-protobuf#479]
I've tried this across your various (excellent) crates and the behavior appears consistent (among the crates) but inconsistent with my expectation and `protoc` on the command-line.

Repro:

An arbitrary protobuf taken from grpc.io: `protos/greeter.proto`:
```protobuf
syntax = "proto3";


service Greeter {
    rpc SayHello (HelloRequest) returns (HelloReply) {}
}
message HelloRequest {
    string name = 1;
}
  
message HelloReply {
    string message = 1;
}
```

Can be compiled by:

```bash
protoc \
--proto_path=./protos \
--rust_out=./src/protos \
greeter.proto
```

**NB** Because  the include path includes `./protos`, I need not respecify this when providing the proto

Attempting to mirror this using `build.rs`:

```rust
protoc_rust::run(protoc_rust::Args {
    out_dir: "src/protos",
    includes: &["protos"],
    input: &["greeter.proto"],
    customize: protobuf_codegen_pure::Customize {
        ..Default::default()
    },
})
.expect("protoc");
```
Fails:
```
cargo build
   Compiling X v0.1.0 (...)
error: failed to run custom build command for `X v0.1.0 (...)`

Caused by:
  process didn't exit successfully: `/.../build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'protoc: Custom { kind: Other, error: "file \"greeter.proto\" is not found in includes [\"protos\"]" }', build.rs:19:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Which is incorrect. `greeter.proto` is indeed in `protos`

If I explicitly reference the include path, it works:

```rust
protoc_rust::run(protoc_rust::Args {
    out_dir: "src/protos",
    includes: &["protos"],
    input: &["protos/greeter.proto"],
    customize: protobuf_codegen_pure::Customize {
        ..Default::default()
    },
})
.expect("protoc");
```
But then, why include the include path? Well, it turns out, I don't need to. This also works:

```
protoc_rust::run(protoc_rust::Args {
    out_dir: "src/protos",
    includes: &[],
    input: &["protos/greeter.proto"],
    customize: Customize {
        ..Default::default()
    },
})
.expect("protoc");
```

The reason this becomes an issue (besides the inconsistency with `protoc`) is that I'm trying to generate a crate that is a gRPC client for a 3rd-party (Golang) project. I would like to `include` that project's protos but I must explicitly path to each of the project's protos.

Additionally, the 3rd-party project imports e.g. `google/api/annotations.proto` and I've been unable to include these definitions on the path in a way that will build:

```protobuf
syntax = "proto3";

import "google/api/annotations.proto";

service Greeter {
    rpc SayHello (HelloRequest) returns (HelloReply) {}
}
message HelloRequest {
    string name = 1;
}
  
message HelloReply {
    string message = 1;
}
```
I've a working copy of the import and can compile with `protoc` but not using `build.rs`:

```rust
protoc_rust::run(protoc_rust::Args {
    out_dir: "src/protos",
    includes: &["/.../github.com/grpc-ecosystem/grpc-gateway@v1.9.4/third_party/googleapis"],
    input: &["protos/greeter.proto"],
    customize: protoc_rust::Customize {
        ..Default::default()
    },
})
.expect("protoc");
```
Whereas:

```bash
protoc \
--proto_path=./protos \
--proto_path=/.../github.com/grpc-ecosystem/grpc-gateway@v1.9.4/third_party/googleapis \
--rust_out=./src/protos \
greeter.proto
greeter.proto:3:1: warning: Import google/api/annotations.proto is unused.
```
The warning is correct but a `src/protos/greeter.rs` is generated as expected.

Also:

```rust
protobuf_codegen_pure::run(protobuf_codegen_pure::Args {
    out_dir: "./src/protos",
    includes: &["protos"],
    input: &["greeter.proto"],
    customize: protobuf_codegen_pure::Customize {
        ..Default::default()
    },
})
.expect("protoc");
```
and:

```rust
protoc_rust_grpc::run(protoc_rust_grpc::Args {
    out_dir: "src/protos",
    includes: &["protos"],
    input: &["greeter.proto"],
    rust_protobuf: true,
    ..Default::default()
})
.expect("protoc");
```

**Comment by stepancheg** [comment]
Inconsistencies would be good to fix.

For starters, we need to understand what's exact `protoc` behaviour.

**Comment by DazWilkin** [comment]
I'd like to caveat what follows: I'm a rust noob and value your feedback.

If any of this is RTFM, please tell me; all feedback is appreciated and welcome:

I'm reasonably familiar with protobufs and gRPC and have used both mostly with Golang.

IIRC `protoc` itself mentions that combining abs|rel paths and wildcards is challenging but...

For example `github.com/google/googleapis`

```
googleapis
├── ...
├── google
│   ├── ...
│   ├── api
│   │   ├── annotations.proto
│   │   └── ...
```

I am able to reference `googleapis` in `proto_path` and then no longer need to specify which `proto_path`:

```bash
protoc \
--proto_path=googleapis \
--rust_out=src/google/api \
google/api/annotations.proto
```

1. Once in the path, I need not duplicate `googleapis/google/api/annotations.proto`
1. The `proto_path` may be `${PWD}/googleapis`, `./googleapis` or `googleapis`
1. Curiously (!) I can wildcard if I do include the `proto_path` anchor but then I must use relative `proto_path`. I think this is an edge-case that we ignore: 

```
protoc \
--proto_path=googleapis \
--rust_out=src/google/api \
googleapis/google/api/*.proto`
```

The only (!?) configuration that works with e.g. `protoc_rust_grpc` is to duplicate the reference to the `proto_path` on the input. Wildcards aren't supported (which I think is understandable|OK).

```rust
protoc_rust_grpc::run(protoc_rust_grpc::Args {
    out_dir: "src/google/api",
    includes: &["googleapis"],
    input: &[
        "googleapis/google/api/annotations.proto",
        ...,
    ],
    rust_protobuf: true,
    ..Default::default()
})

**Comment by stepancheg** [comment]
API changed significantly in rust-protobuf v3. Closing due to old age. Please reopen if the issue still exists.
