### ISSUE TITLE
Consider moving downloaded protoc binaries into a separate crate

### ISSUE THREAD

**Issue by stepancheg** [stepancheg/rust-protobuf#481]
I'm worried that `protoc` crate size is 37M uncompressed, which might be inconvenient to some users.

One option to solve this issue is to put binaries into a separate crate `protoc-binaries`.

`protoc` crate won't depend on `protoc-binaries`, but when invoking `protoc` crate user would have to explicitly reference `protoc-binaries` crate. Like this:

```
protoc_rust::Args::new()
 .protoc_binary(protoc_binaries::binary())
 .other_args()
 .run() 
```

Some inconvenience to users, and very good flexibility.

In particular, this design allows having alternative crate, for example, `protoc-binaries-download` which would download `protoc` binaries at run time, and the same crate will also need to be used explicitly:

```
protoc_rust::Args::new()
 .protoc_binary(protoc_binaries_download::binary())
 .other_args()
 .run() 
```

Any thoughts? @BusyJay?

**Comment by BusyJay** [comment]
LGTM, just `protoc-vendored` seems better than `protoc-binaries-download`.

**Comment by stepancheg** [comment]
I picked `protoc-bin-vendored` crate name. Going to publish soon unless someone objects.

**Comment by stepancheg** [comment]
`protoc-bin-vendored` released.
