### ISSUE TITLE
Extension fields in Proto2

### ISSUE THREAD

**Issue by Igosuki** [stepancheg/rust-protobuf#483]
Hi, I read the codebase in order to debug why extensions fields were not taken into account in messages. 
As I see it, in the protobuf codegen parser, extension fields are just skipped. (cf https://github.com/stepancheg/rust-protobuf/blob/master/protobuf-codegen-pure/src/parser.rs#L790)
Are there plans to actually add the possibility to handle these or should I just roll my own patch ?

**Comment by Igosuki** [comment]
I am talking about something like this : 
```
message TestOptimizedForSize {
  optional int32 i = 1;
  optional ForeignMessage msg = 19;

  extensions 1000 to max;
}
```

**Comment by Igosuki** [comment]
This produces the following files : https://gist.github.com/Igosuki/27e18369fec5a05d4019ac5d321e1779 but I don't understand how to combine the two to read a message including the potential extensions

**Comment by stepancheg** [comment]
This is an example of using extensions: https://github.com/stepancheg/rust-protobuf/blob/90fd27e6d79084afd1d584c28feeb6a6fc92e529/protobuf-codegen/src/customize.rs#L160

Does that help?

**Comment by stepancheg** [comment]
Extensions are "external" to messages, because extensions can be defined in a different proto file and a different compilation unit and even in a different Rust crate.

**Comment by Igosuki** [comment]
Thank you for taking the time ! I get it now, I was a bit unfamiliar with proto extensions so sorry for spamming an issue.
I got confused because I was trying to deserialize json, and using ignore unknown fields just skips the fields.
