### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by jknovi** [stepancheg/rust-protobuf#485]
After updating rust, when running clippy I'm getting that allow(clippy) is deprecated from my proto generated files. I've not been able to found where to chage it to clippy::all.

I re-generate the proto code on every build.

Thanks for the help!

**Comment by stepancheg** [comment]
Latest protobuf generates `clippy::all`.

Can you please show what version of protobuf do you use, and what command do you use to regenerate protos?

**Comment by jknovi** [comment]
Sorry, should have added more context. We have a fork of 2.9 (we need json support) with some patches, one is already in master and thus we've been planning to migrate to 3.0 and contribute the other patches, but haven't prioritized it.
I was hopping if there was some arg that I can pass to the generation to use the other. This is how we generate them in our build.rs:
```
    protoc_rust::run(protoc_rust::Args {                                                            
        out_dir: "src/proto",                                                                       
        includes: &proto_includes,                                                                  
        input: &normalized_inputs,                                                                  
        customize: Default::default(),                                                              
    })?;  
```

But tbh, I think we can just change in our fork the line that generates it and change it to `clippy::all ` instead, but kinda want to keep the patches to the minimum.

**Comment by jknovi** [comment]
Ok, sorry for maybe been a little hand waivy with this one. I think I figure out. the problem is that we are using protoc-rust-grpc-0.7 that we also have forked because of reasons. I will post the issue there (or submit a pull request) as the issue is on that other crate.

Sorry, for the inconvenience.
