### ISSUE TITLE
protobuf-codegen-pure docs contradict Cargo book

### ISSUE THREAD

**Issue by elshize** [stepancheg/rust-protobuf#486]
As mentioned in #324, build scripts are not supposed to write to `src` directory (https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script), yet this is what the documentation suggests. Once #324 is resolved, I suggest that the documentation should be changed.

**Comment by stepancheg** [comment]
A lot changed since then, especially in rust-protobuf version 3. Please reopen if the issue is still relevant.
