### ISSUE TITLE
just lost, where is SerializeToString?

### ISSUE THREAD

**Issue by pipehappy1** [stepancheg/rust-protobuf#487]
Just a list lost here. What is the function in rust-protobuf which is equivalent to SerializeToString in protobuf in Python?

**Comment by stepancheg** [comment]
There are operations in this module: https://docs.rs/protobuf/2.14.0/protobuf/text_format/index.html

Also, default debug formatter prints text format `format!("{:?}", message)`, but this is kind of deprecated because it does not conform to Rust conventions.

**Comment by pipehappy1** [comment]
Thank you!
