### ISSUE TITLE
Well Known Types - Timestamp - Consider changing serde implementation

### ISSUE THREAD

**Issue by oribs1** [stepancheg/rust-protobuf#488]
Currently Timestamp under the well known types implement the default serde behaviour.

This results with bad behaviour when translating protobuf to JSON, as the spec requires the format to be RFC 3339. It also doesn't align with other timestamp formats such as chrono::DateTime, which also formats the timestamp according to RFC 3339 when used with serde

**Comment by stepancheg** [comment]
It's not possible to implement proper JSON serialization using serde.

For example, JSON serialization specification requires parser to accept both foo_bar and fooBar keys in JSON for field foo_par.

rust-protobuf in master implements proper JSON parser and serialization (without serde).

rust-protobuf 2 only implement serialization, parsing is harder to implement without breaking backwards compatibility. It's not my very long TODO list though.

**Comment by Plecra** [comment]
Just so you know, there's nothing stopping you from achieving that with serde: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=255c65348d7639277084b92fea94d1e9) - The derive macros scratch the surface of the serde protocol. 

Also, is it really necessary? [The only 'spec' I could find](https://developers.google.com/protocol-buffers/docs/proto3#json_options) considers it optional.

That said, I'd rather the library not contain a hand-rolled JSON implementation. The `serde-json` crate is well vetted and tested, and I already know this one has bugs.

**Comment by oribs1** [comment]
> Just so you know, there's nothing stopping you from achieving that with serde: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=255c65348d7639277084b92fea94d1e9) - The derive macros scratch the surface of the serde protocol.
> 
> That said, I'd rather the library not contain a hand-rolled JSON implementation. The `serde-json` crate is well vetted and tested, and I already know this one has bugs.

This was my intention, I think it should be a part of this crate when generating serde definition for `protobuf::well_known_types::Timestamp`. What was stopping me from doing it, is the face that the Timestamp is a well known type, and part of this crate. And I can't (easily) implement an external trait for an external type. 

Anyway diving into the topic, I'm not sure the spec can be implemented with serde. I was too optimistic as my own use case requires only a small portion of the support. Seeing this is the situation, I don't think it worth breaking backward compatibility for people using serde for other purposes, so closing this issue.
