### ISSUE TITLE
Dynamic Message

### ISSUE THREAD

**Issue by cawfeecoder** [stepancheg/rust-protobuf#498]
- [x] Basic implementation done
- [x] Map fields are not implemented
- [x] Unknown fields are not preserved
- [ ] More tests

**Comment by stepancheg** [comment]
This is on my very long todo list.

If you want to contribute, start with sending some design or sketch, because it might be not trivial to implement without breaking backward and forward compatibility.

**Comment by stepancheg** [comment]
Dynamic messages are half-implemented in master. They won't be ported to version 2, instead, version 3 will be released.

**Comment by stepancheg** [comment]
Example how to use dynamic messages: https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-examples/dynamic

**Comment by stepancheg** [comment]
* many tests now run dynamic messages to
* codegen relies on dynamic messages

So closing the issue.
