### ISSUE TITLE
Remove `RepeatedField`

### ISSUE THREAD

**Issue by Ekleog** [stepancheg/rust-protobuf#503]
The documentation of `RepeatedField` claims that it is a
> Wrapper around vector to avoid deallocations on clear.

However, the documentation of `Vec::clear` states that
> Note that this method has no effect on the allocated capacity of the vector.

Which means that `Vec::clear` already does not deallocate.

As such, I think it'd make sense to just remove `RepeatedField` altogether, for version 3.

Related issue: https://github.com/stepancheg/rust-protobuf/issues/84

**Comment by stepancheg** [comment]
`Vec::clear` does not decallocate, but it invokes destructors of all fields, causing deallocation of vecs in nested messages.

`RepeatedField` preserves allocation of nested messages.

This gives a little speedup when reusing existing messages to read in loop, like this:

```
let mut m = MyMessage::new();
loop {
  m.clear();
  m.merge_from(is);
}
```

Maybe it is overengineering and not really needed, but it would be hard to remove `RepeatedField` without breaking backwards compatibility.

**Comment by Ekleog** [comment]
Hmm just to make sure I'm understanding correctly, do you mean that `merge_from` should be able to reuse the space freed from `clear()`? I could find no function in [here](https://docs.rs/protobuf/2.10.1/protobuf/struct.RepeatedField.html) that looks like it'd allow doing that.

I totally agree without it being hard to remove `RepeatedField` without breaking backwards compatibility, but maybe this issue could be kept around until a 3.0 gets out, at which point it could be removed indeed :)

**Comment by stepancheg** [comment]
> merge_from should be able to reuse the space freed from clear()?

Basically, this operation is done without allocations:

```
let mut message: MyMessage = Message::new();
loop {
  message.clear();
  message.merge_from(...)?;
  message.check_initialized()?;
  do_something_with_message(&message);
}
```

That said, this feature is used very infrequently, and `RepeatedField` and `SingularField` is removed in master, and `RepeatedPtrField` no longer preserved the allocated memory.

This changes won't be backported to version 3 (because of backwards compatibility), instead, version 3 will be released soon.

**Comment by Ekleog** [comment]
Great, thank you!

**Comment by stepancheg** [comment]
Maybe rust-protobuf 3 need an option to generate `RepeatedField` while keeping `Vec` by default.
