### ISSUE TITLE
Reading and Writing to Protobuf binary files (Question)

### ISSUE THREAD

**Issue by stuartweir** [stepancheg/rust-protobuf#509]
I'm not quite sure how to actually use the generated code in order to read and write data from Protobuf binary files (as a data storage format).

My proto file:
```
syntax = "proto3";

message Metric {
    string str_one = 1;
    int32 metric_val = 2;
}

message Data {
    string sha1 = 1;
    repeated Metric metrics = 2;
    double big_num = 3;
}

message DataSet {
    repeated Query records = 1;
}
```

As an example, here's some code trying to write to a `Vec<u8>`, which will then be written to an s3 object:
```rust
        let mut protobuf_out = Vec::<u8>::new();
        let mut out = CodedOutputStream::vec(&mut protobuf_out);
        // self.protobuf_records is a DataSet::new()
        self.protobuf_records.compute_size();
        let result = self.protobuf_records.write_to_with_cached_sizes(&mut out);
        let flush = out.flush();
        // handle result and flush Result Enums
```

This seems to be writing to a file just fine, but when I try to validate the data locally using `protoc`, I get an invalid control character error.

Protoc Validation:
`protoc --proto_path=/path/to/protos --decode=DataSet downloaded_s3_protobuf_data.bin`

Error:
`downloaded_s3_protobuf_data.bin:61693:18: Invalid control characters encountered in text.`

What am I doing wrong here? My guess so far is that I've been writing to a CodedOutputStream incorrectly, but I'd like a bit more guidance as I cannot seem to understand it just from the docs.

If it's easier, I can also chat on Discord.

Thank you for the help in advance!

- Stu

**Comment by stepancheg** [comment]
Closing due to old age. Sorry I didn't answer in time.
