### ISSUE TITLE
Support Field Presence (proto3)

### ISSUE THREAD

**Issue by theduke** [stepancheg/rust-protobuf#513]
Field presence is a new experimental feature that adds support for optional fields.

TLDR: it works in a somewhat hacky way by representing an optional field with a oneOf with only one variant.

https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md#satisfying-the-experimental-check

**Comment by stepancheg** [comment]
Implemented in versionv3.0.0-alpha.9.

**Comment by theduke** [comment]
Awesome, thanks!
