### ISSUE TITLE
Implement std::error::Error trait for protobuf::json::parse::ParseError

### ISSUE THREAD

**Issue by marctrem** [stepancheg/rust-protobuf#514]
Hi,

Would it be reasonable to add the `std::error::Error` trait to the `protobuf::json::parse::ParseError` struct?
This would simplify returning results containing boxed errors.

Thank you for the amazing work!

**Comment by stepancheg** [comment]
Should be fixed in 044dadbc2762600a248626b64ad6cde690ae43b6. Thanks!
