### ISSUE TITLE
serde_derive_cfg doesn't seem to work

### ISSUE THREAD

**Issue by ondrowan** [stepancheg/rust-protobuf#516]
It seems it's present in `rust-protobuf/protobuf-codegen/src/serde.rs` in `master`, but not in version 2.16. It's possible to set it in `Customize` struct, but it's not used anywhere.

**Comment by stepancheg** [comment]
This option was implemented for protobuf itself.

Anyway, it is too late to add this feature to rust-protobuf=2, and rust-protobuf=3 remove serde support, and relies on callbacks provided by users, and users can apply any annotations to generated code.

Also, rust-protobuf 3 has native json support.
