### ISSUE TITLE
Change generated code for version 3 release

### ISSUE THREAD

**Issue by stepancheg** [stepancheg/rust-protobuf#521]
- [x] Remove `get_` prefix from functions [as API guide suggests](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter)
- [x] Make all fields public
- [ ] All singular fields should have getters (including singular proto3 fields)
- [ ] Only oneof fields should have `set_xxx` and `has_xxx` methods

**Comment by chanced** [comment]
First off, thank you for your work on this project. It is by no means a small undertaking! 

Would you mind exposing/generating all of the compiler related protobuf files? A lot of enums are not currently available, such as `Name`, `IdempotencyLevel`, `NamePart`, `JsType` and so on.

I'm working on a port of protoc-gen-star to rust [here](https://github.com/chanced/catalyze) and it'd be really helpful if they were all available on this crate. I initially started with prost but it doesn't support unknown fields which I'll need for extension parsing.

I could generate them myself but it looks like you've modified the output somewhat? I could be wrong there.

Thanks again!

**Comment by stepancheg** [comment]
These types are present in rust-protobuf v3 (which is not release yet).

In rust-protobuf v2 probably code just need to be regenerated, but releasing v3 is my priority now.

**Comment by chanced** [comment]
@stepancheg ugh, I'm sorry! I did a search across the repo and couldn't find them. Thank you!
