### ISSUE TITLE
How to read multiple messages from a single file or bytearray

### ISSUE THREAD

**Issue by BananaEarwig** [stepancheg/rust-protobuf#522]
It seems I am able to read a single message from a file, but as soon as there is more than 1 I get a wireerror(unexpectedwiretype(WireTypeFixed32)) error, looking at the code, it seems there is a !eof loop around field types for each message. Presumably when there are multiple messages these are also being decoded?

**Comment by stepancheg** [comment]
Protobuf messages are not internally length-delimited. Each message is always until the end of file.

The usual solution is to write them length-delimited. E. g. prepend each message with length, and read length before reading a message. `CodedInputStream` and `CodedOutputStream` provide utilities for that pattern.

This pattern is described in Google protobuf documentation: https://developers.google.com/protocol-buffers/docs/techniques#streaming
