### ISSUE TITLE
Code generation with serde(default)

### ISSUE THREAD

**Issue by Freydal** [stepancheg/rust-protobuf#524]
It may be a moot point in context of https://github.com/stepancheg/rust-protobuf/issues/519, but support for optional fields in JSON input would be useful.

I'm not sure if there is a good clean workaround so I opted to just fork and hack the option in quickly.

**Comment by stepancheg** [comment]
Can you please explain, what exactly are you proposing?

**Comment by Freydal** [comment]
Sorry for the confusion.  

If you attempt to deserialize json for a proto struct that has 3 fields and the json only has 2 of them present, for example, you will fail in error due to the missing field.  I feel it is beneficial to allow for the presence of serde(default) to configure serde_json to use default values for potentially missing items in the json during deserialization. The solution may not be require all fields to be present despite the protobuf definition. 

Due to #519 I thought in the long time another solution to this issue may be warranted due to native json support.  In the short time I hacked the option in to get me moving in [this](https://github.com/Freydal/rust-protobuf/commit/99e0e22f582c5b013c19d256d995555e0ce5ae86) fork commit.

**Comment by stepancheg** [comment]
I see, thanks for the explanation. Well, I know only a little about serde. Your patch looks right, but I'd avoid risking breaking backwards compat unless there are good reasons to. Please let me know if this is needed in rust-protobuf v2. Otherwise better just drop serde support in v3.

**Comment by stepancheg** [comment]
rust-protobuf version 2 is now is maintenance mode.

rust-protobuf version 3:
* remove serde support
* instead users can supply custom per type, per field annotations
* has native JSON support
