### ISSUE TITLE
file x must reside in include path

### ISSUE THREAD

**Issue by lucaszanella** [stepancheg/rust-protobuf#527]
program:

 ```
   let current_dir = env::current_dir().unwrap();
    let parent = current_dir.as_path().parent().unwrap();

    protobuf_codegen_pure::run(protobuf_codegen_pure::Args {
        out_dir: "src/protos",
        input: &["openvpn.proto"],
        includes: &[parent.to_str().unwrap()],
        customize: protobuf_codegen_pure::Customize {
            ..Default::default()
        },
    })
```

Error:

```
error: failed to run custom build command for `proto_rust v0.1.0 (/home/dev/orwell/liborwell_rust/src/liborwellprofile/proto_rust)`

Caused by:
  process didn't exit successfully: `/home/dev/orwell/liborwell_rust/src/liborwellprofile/proto_rust/target/debug/build/proto_rust-7c3f1010b5baa7c3/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'protoc: Custom { kind: Other, error: "file \"openvpn.proto\" must reside in include path [\"/home/dev/orwell/liborwell_rust/src/liborwellprofile\"]" }', build.rs:26:6
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Contents of the folder:

```
ls /home/dev/orwell/liborwell_rust/src/liborwellprofile | grep openvpn.proto
openvpn.proto
```

**Comment by stepancheg** [comment]
`includes` should point to `src/liborwellprofile`. Where does it point to?

**Comment by lucaszanella** [comment]
@stepancheg it points to `/home/dev/orwell/liborwell_rust/src/liborwellprofile` as it says in the output: `"openvpn.proto\" must reside in include path [\"/home/dev/orwell/liborwell_rust/src/liborwellprofile\"]`

**Comment by stepancheg** [comment]
Should be something like:

```
   protobuf_codegen_pure::run(protobuf_codegen_pure::Args {
       out_dir: "src/protos",
       input: &["./openvpn.proto"],
       includes: &["."],
       customize: protobuf_codegen_pure::Customize {
           ..Default::default()
       },
   })
```

Both includes and output paths should both relative or both absolute.

**Comment by stepancheg** [comment]
codegen diagnostic could be better though.

**Comment by lucaszanella** [comment]
Worked for me with

```
    protobuf_codegen_pure::run(protobuf_codegen_pure::Args {
        out_dir: "src/protos",
        input: &["../openvpn.proto"],
        includes: &["../"],
        customize: protobuf_codegen_pure::Customize {
            ..Default::default()
        },
    })
    .expect("protoc");
```
So let's say `../` is `/home/dev/orwell/liborwell_rust/src/liborwellprofile`. The `openvpn.proto` file is inside `/home/dev/orwell/liborwell_rust/src/liborwellprofile`. It does not make sense to pass `../openvpn.proto`, should be `./openvpn.proto`, because it's inside the include folder.

**Comment by stepancheg** [comment]
Can't you pass `./openvpn.proto` and `include = `.`?

Note `protobuf_codegen_pure` tries to be compatible with `protoc` command line interface (`includes` option mimics `-I` flag). When behavior is incompatible, we need to fix in codegen.

**Comment by lucaszanella** [comment]
I can't pass `.` as include, rust code is on `/home/dev/orwell/liborwell_rust/src/liborwellprofile/proto_rust/build.rs` and .proto files are in `/home/dev/orwell/liborwell_rust/src/liborwellprofile` so I need to pass `../ = /home/dev/orwell/liborwell_rust/src/liborwellprofile/` but then the file relative to this include path should be `openvpn.proto`, not `../openvpn.proto = /home/dev/orwell/liborwell_rust/src/openvpn.proto` but anyways I don't mind leaving like this

**Comment by stepancheg** [comment]
No, both include path and filename should be either absolute or relative to the current directory. It does not seem 100% reasonable, but that's how `protoc` works.
