### ISSUE TITLE
Import google.protobuf.Timestamp.proto

### ISSUE THREAD

**Issue by yshahin** [stepancheg/rust-protobuf#529]
What is the best way to import this type in my proto?
Just adding the import it fails with file not found.

Should I include a directory? or do I have to clone the google protobuf repo to get it?

**Comment by yshahin** [comment]
Just found this https://github.com/stepancheg/rust-protobuf/blob/9e2c75c5514658ef1036a2e42d13f44eb41ddb14/protobuf-codegen-pure/src/lib.rs

// TODO: these include don't work when publishing to crates
const RUSTPROTO_PROTO: &str = include_str!("../../proto/rustproto.proto");
const ANY_PROTO: &str = include_str!("../../proto/google/protobuf/any.proto");
const API_PROTO: &str = include_str!("../../proto/google/protobuf/api.proto");
const DESCRIPTOR_PROTO: &str = include_str!("../../proto/google/protobuf/descriptor.proto");
const DURATION_PROTO: &str = include_str!("../../proto/google/protobuf/duration.proto");
const EMPTY_PROTO: &str = include_str!("../../proto/google/protobuf/empty.proto");
const FIELD_MASK_PROTO: &str = include_str!("../../proto/google/protobuf/field_mask.proto");
const SOURCE_CONTEXT_PROTO: &str = include_str!("../../proto/google/protobuf/source_context.proto");
const STRUCT_PROTO: &str = include_str!("../../proto/google/protobuf/struct.proto");
const TIMESTAMP_PROTO: &str = include_str!("../../proto/google/protobuf/timestamp.proto");
const TYPE_PROTO: &str = include_str!("../../proto/google/protobuf/type.proto");
const WRAPPERS_PROTO: &str = include_str!("../../proto/google/protobuf/wrappers.proto");

Any idea how to solve this when using crate. Workaround is fine too.

**Comment by stepancheg** [comment]
Yes, passing a path to a directory with protobuf `.proto` files is a possible workaround.

Proper solution is yet to be implemented, and at the moment, it is not clear what it should be.

There are basically three ways to invoke codegen:
* using system `protoc` binary. It has `.proto` files bundled
* using `protoc` binary from `protoc-bin-vendored` crate. This crate has only binary, and doesn't have any `.proto` files bundled google `.proto` files resolving won't work
* using pure codegen

Even with pure codegen will (and should) have bundled google `.proto` files, it is not clear what to do with option 2 (`protoc-bin-vendored` crate). Well, maybe `protoc-bin-vendored` crate should also bundle `.proto` files. Or maybe the crate which launches codegen with bundled protos should have `.proto` bundled, and unpack them somewhere before invoking vendored protoc.

But generally, yes, there's a inconsistency between using system `protoc` and pure codegen, and it need to be fixed somehow.

**Comment by stepancheg** [comment]
OK, bundled protoc now includes `.proto` files (2a67ef99e6dc1791dbc3633761879a9e49c8f780).

It's time to fix pure codegen I think.

**Comment by stepancheg** [comment]
Fixed in master, now need to port it to the stable branch.

**Comment by stepancheg** [comment]
OK, I don't know if it was broken or not, have I fixed it or not, but in the latest version of rust-protobuf there's an example ([link](https://github.com/stepancheg/rust-protobuf/blob/v2.22.0/protobuf-examples/src/protos/example.proto#L21)) which uses google's proto files, that example is compiled with both pure rust and protoc-based codegens.

**Comment by spartucus** [comment]
https://github.com/stepancheg/rust-protobuf/blob/9e2c75c5514658ef1036a2e42d13f44eb41ddb14/protobuf-codegen-pure/src/lib.rs#L264-L276 Are these the only external sources that support import? What if a proto which is from https://buf.build, do i have to download all the related protos in local include path?
