### ISSUE TITLE
Json Serialization is not working properly

### ISSUE THREAD

**Issue by luo4lu** [stepancheg/rust-protobuf#535]
this error log: the trait `Serialize` is not implemented for `TranscationInput`
Use the generated file RS file, which contains the TranscationInput structure.
Call after creating a new object.The code generation process already exists #[cfg_attr(Serde, Extract (Serialize, Deserialize))]

**Comment by stepancheg** [comment]
rust-protobuf 2 is in maintenance mode

rust-protobuf 3:
* does not have serde support, instead it allows user to annotate types and fields with custom annotations
* has native JSON support
