### ISSUE TITLE
Upgrade to bytes v1.0.0

### ISSUE THREAD

**Issue by giarc3** [stepancheg/rust-protobuf#536]
With crates like `tokio` and `reqwest` going to bytes v1.0.0, it would really be helpful if rust-protobuf upgraded to match them. Is this something you would consider? I don't currently see any obvious pitfalls in the upgrade, and it would be really beneficial to me. 
Let me know if you'd like me to open a PR for it.
Thanks

**Comment by stepancheg** [comment]
Yes, that would be the right thing to do.

If you could submit PR to master, I'll backport it to stable branch and release it.

**Comment by giarc3** [comment]
Great, thank you very much! I opened a PR https://github.com/stepancheg/rust-protobuf/pull/537
The upgrade didn't seem to require any additional code changes, so let me know if there's more I need to do.

**Comment by stepancheg** [comment]
2.20.0 released with bytes 1.0.
