### ISSUE TITLE
Version 2.19 breaks compatibility with previous 2.x releases.

### ISSUE THREAD

**Issue by coltfred** [stepancheg/rust-protobuf#539]
2.19 upgraded bytes from 0.5 to 0.6 which is not a compatible change.

https://github.com/tokio-rs/bytes/blob/master/CHANGELOG.md shows that the api changes from 0.5.x to 0.6.x.

I wasn't sure you were aware of this issue, but it appears that you're trying to maintain compatibility so I thought I'd let you know.

I'm not sure what the right thing to do is. Maybe to yank 2.19 and push up a 2.20 with the dependency reverted?

**Comment by stepancheg** [comment]
I don't really have a good solution here. We cannot live for years with outdated version of bytes crate even if technically it is a breaking change: people requested this change, and they need newer bytes for other dependencies.

Even worse, upgrade of bytes to 1.0 is [coming in 2.20](https://github.com/stepancheg/rust-protobuf/pull/538).

**Comment by coltfred** [comment]
That PR is unmerged and doesn't have to be part of a 2.20 release. I assumed that it would be part of a 3.x version.

**Comment by stepancheg** [comment]
3.0 won't happen soon, and that's not the first time bytes crate was updated, in version 2.10 bytes crate was upgraded from 0.4 to 0.5.

Why that upgrade is an issue?

Maybe there's some solution to make rust-protobuf compatible with all versions of bytes crate. It will be maintenance burden, but if it is really needed, it can be done.
* first a feature can be implemented, like bytes_0_5 for dependency on bytes 0.5
* if build.rs could somehow read a version of bytes crate, that would be perfect, no feature would be needed, but I don't know how to achieve that

**Comment by coltfred** [comment]
I was just trying to help point out that the versions inside of 2.x aren't compatible. I wasn't using this crate when the 2.10 release broke compatibility. 

It seems to me that having more major version bumps would be much less work than either of the other solutions you proposed. Maybe there is an even better solution, but I haven't seen it.

We could just ignore the problem and now that bytes is 1.x just use it with compatibility going forward. This forces people who care about the bytes compatibility into using version ranges of rust-protobuf.

My intention with this issue was not to point fingers and if I came across accusatory in any way, accept my apologies. I appreciate your work on this crate immensely.

**Comment by stepancheg** [comment]
No worries! I'll release 2.20 with bytes 1.0 and hope backward compatibility with bytes crate won't be no longer an issue.

**Comment by stepancheg** [comment]
2.20.0 released with bytes 1.0. Sorry for inconvenience!
