### ISSUE TITLE
support generating codes for service?

### ISSUE THREAD

**Issue by brianjcj** [stepancheg/rust-protobuf#543]
support generating codes for service?

**Comment by stepancheg** [comment]
Why would they be used?

Generic service definitions are not useful for grpc. grpc or grpcio crates have own generators of services.

**Comment by bendb-instacart** [comment]
These are useful for RPC systems that _aren't_ gRPC, like Twirp.  I'm sure you're well aware but the usual support for this is quite limited - in Java, protoc will just generate an interface, for example.  I think having rust-protobuf just generating a simple trait would be quite helpful.
