### ISSUE TITLE
Custom type support

### ISSUE THREAD

**Issue by wangjia184** [stepancheg/rust-protobuf#552]
Can I have custom type instead of bytes so that I can implement my own serializer/deserilizer of this field?

I have the following pb file from scala.  In scala it uses an extension to present the field as `BitSet`
```
message Receive {
    bytes locallyFree = 1 [(scalapb.field).type = "scala.collection.immutable.BitSet"];
}
```

I can write my `BitSet` struct in rust and expose serializer/deserializer traits,  is there a way to inject my struct into the generated code ?

**Comment by stepancheg** [comment]
There's no way to do that now, but I'm open do considering designing and implementing this extension.

**Comment by wangjia184** [comment]
thanks, finally I solved it with prost.
