### ISSUE TITLE
Cannot parse Protobuf Any with Serde

### ISSUE THREAD

**Issue by zamazan4ik** [stepancheg/rust-protobuf#559]
Hi!

I've found strange behaviour in the library. I am trying to parse Protobuf Any with Serde from the text like this:
```
let p: SomeProtoType = serde_json::from_str(message_text.as_str()).unwrap();
```

As far as I understand, the library expects the field `type_url`, but the provided text has `@type`.

So can I parse it in the right way? Thanks in advance!

**Comment by ZaMaZaN4iK** [comment]
An example of the received message:
```
{
      "innerMessage": {
        "@type": "type.googleapis.com/com.amazon.whitewater.auxproxy.pbuffer.ActivateGameSession",
        "gameSession": {
          "gameSessionId": "game_session",
          "fleetId": "fleet",
          "maxPlayers": 2,
          "ipAddress": "127.0.0.1",
          "port": 14000,
          "dnsName": "localhost"
        }
      }
    }
```

**Comment by ZaMaZaN4iK** [comment]
According to the documentation, that's possible to have different serialized formats for Protobuf `Any`: https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Any

**Comment by dimitar-petrov** [comment]
I am also interested. Did you manage to solve it.

**Comment by stepancheg** [comment]
Explicit serde support removed from rust-protobuf 3 (and no new features to be added to rust-protobuf 2).

Consider adding native JSON support in rust-protobuf 3.

Although it probably JSON doesn't play well with `Any`. Please create another issue about `Any` and JSON if it is still relevant.
