### ISSUE TITLE
Are fields named 'type' supported?

### ISSUE THREAD

**Issue by fourlightyears** [stepancheg/rust-protobuf#560]
I had a situation where I needed to have a field named 'type' in a protobuf message. The following modified example (based off the original in the repository) will demonstrate this:

```protobuf
syntax = "proto3";

import "google/protobuf/timestamp.proto";

message GetRequest {
  string name = 1;
  int32 age = 2;
  repeated string features = 3;
}

message GetResponse {
  enum Status {
    OK = 0;
    ERR = 1;
    NOT_FOUND = 2;
  }
  Status status = 1;
  string address = 2;
  string city = 3;
  int32 zipcode = 4;
  google.protobuf.Timestamp ts = 5;
  int32 type = 6;
}
```

I changed the example main.rs like so:

```rust
    // Encode example response
    let mut out_resp = GetResponse::new();
    out_resp.status = Status::OK.into();
    out_resp.address = "1243 main street".to_string();
    out_resp.city = "anytown".to_string();
    out_resp.zipcode = 54321;
    out_resp.r#type = 54321;
```

When building I get the following error:

   Compiling protobuf-examples v0.0.0 ~/github/rust-protobuf/protobuf-examples)
error[E0609]: no field `r#type` on type `generated_with_native::example::GetResponse`
  --> protobuf-examples/src/main.rs:37:14
   |
37 |     out_resp.r#type = 54321;
   |              ^^^^^^ unknown field
   |
   = note: available fields are: `status`, `address`, `city`, `zipcode`, `ts` ... and 3 others

It appears that the 'type' filed is not recognized at all. 

I'm wondering if the code generation deliberately excludes the 'type' field?

It's obviously a rust keyword, but can't it (or anything else that happens to be a rust keyword) be supported by using r#type in the generated code?

Tested using the current version on repo: f549ac2

**Comment by stepancheg** [comment]
I'm sorry for late reply. Fields names are escaped with `field_` prefix. Should be `out_resp.field_type`.
