### ISSUE TITLE
RepeatedField should implement std::iter::Extend

### ISSUE THREAD

**Issue by qwandor** [stepancheg/rust-protobuf#561]
As of 2.24.1, there doesn't seem to be an easy way to append multiple elements to a `RepeatedField` which already contains some elements. The simplest way to support this would be for it to implement `std::iter::Extend`, like `Vec` does.

**Comment by stepancheg** [comment]
Pushed to 2.25 branch (1611f9ddf9ec5ea7e5230bae84ae4857e34618e4).

Did not push to master since there's no `RepeatedField` in the next version of rust-protobuf.

**Comment by stepancheg** [comment]
Published 2.25.0.
