### ISSUE TITLE
Codegen option to make oneof enums `#[non_exhaustive]`

### ISSUE THREAD

**Issue by Spferical** [stepancheg/rust-protobuf#566]
Adding a field to a `oneof` in a protobuf is a breaking change for the generated protobuf code because user code may match on all enum variants. It would be nice to be able to specify a codegen option to add `#[non_exhaustive]` to oneof enums to allow adding oneof fields without potentially breaking user code.

The use case for this is crates that expose generated protobuf structs and would like to add fields to them without a major version bump.

Side question: IMO it would be most intuitive if adding fields to protobufs is always a non-breaking change for the generated code, but there are a few other cases that also break -- adding fields to protobufs may [add a private struct field when all current fields are public](https://doc.rust-lang.org/cargo/reference/semver.html#major-adding-a-private-struct-field-when-all-current-fields-are-public) or [add a public field when no private field exists](https://doc.rust-lang.org/cargo/reference/semver.html#major-adding-a-public-field-when-no-private-field-exists). I think adding an extra hidden dummy field to all generated protobuf structs would fix this. Do other people agree that it would be useful to guarantee that adding fields to protobufs won't be a breaking change to the generated protobuf code? If so, I can make a separate issue for this.

**Comment by stepancheg** [comment]
You are correct, oneof are meant to be non-exhaustive. But people might expect it to be exhaustive because they maintain proto and rs code side by side.

I added this marker unconditionally to rust-protobuf 3 920df7860ebb3e8900317639c9735554de79df3d

Although it probably should be configurable.

It is unlikely this will be backported to stable branch.

**Comment by ahovgaard** [comment]
@stepancheg Is there any update on the idea of making this configurable? That would be useful to us.
