### ISSUE TITLE
Can we get a 3.0 alpha release?

### ISSUE THREAD

**Issue by mwlon** [stepancheg/rust-protobuf#575]
I have a library I'm building that requires `protobuf::json`, so it depends on master branch of this repo. However, I can't publish the library unless it uses a crates.io version instead. I noticed you were looking at releasing a 3.0 alpha a while ago (https://users.rust-lang.org/t/how-to-release-alpha-version/55569), but I don't see any available.

Could you please release a 3.0 alpha soon? If not, my backup option is to fork and make new crates like `protobuf-alpha`, which is obviously less desirable. I've verified that all the current functionality in master works for my purposes.

**Comment by stepancheg** [comment]
Sure, I'll try to do it this weekend.

Thank you for the feedback!
