### ISSUE TITLE
may `protobuf_codegen_pure::model` and `protobuf_codegen_pure::parser` be pub?

### ISSUE THREAD

**Issue by shanicky** [stepancheg/rust-protobuf#576]
Hi, stepancheg!

We recently came across a simple requirement when using the `rust-protobuf` library, we want to dynamically parse the protobuf file at runtime and generate the corresponding `Descriptors`, we searched for a while and currently use `protobuf_codegen_pure::parse_and_typecheck`, which works fine, but we went deeper into the code and saw `protobuf_codegen_pure::model` and `protobuf_codegen_pure::parser`, but they are both private, it feels more convenient to use this directly, we are curious about these two can be made public?

Many thanks!

**Comment by stepancheg** [comment]
@cjubb39 @benesch have a look at 39ca3b5ecc48ebed56035362f5c2740d7449cd4d. Would it be sufficient to solve your problem? This allows to fetch dependencies, but does not expose parser internals.

If this is good enough, please let me know, if it need to be backported to v2 branch or released as v3 alpha version from the master branch.

**Comment by stepancheg** [comment]
@shanicky I have added a function `parse_and_typecheck_custom` which accepts a callback to read file contents.

https://github.com/stepancheg/rust-protobuf/blob/2265d17c6a7a53275291e6bf6d5ac8bc5f59ca6b/protobuf-codegen-pure/src/parse_and_typecheck.rs#L317-L347

Have a look please.

Note that:
* this function is marked as doc-hidden, so it is not considered public API, and I'm not yet ready to guarantee it won't change
* this is master branch, version 3, which won't be released soon. I can publish another alpha version of v3 branch, but if it is needed in stable version of rust-protobuf (v2), more work is needed

**Comment by cjubb39** [comment]
Thanks for the quick fix @stepancheg!  This should be sufficient for our use case.  We'd appreciate a backport to v2 if it's not too much trouble!

**Comment by shanicky** [comment]
> @shanicky I have added a function `parse_and_typecheck_custom` which accepts a callback to read file contents.
> 
> https://github.com/stepancheg/rust-protobuf/blob/2265d17c6a7a53275291e6bf6d5ac8bc5f59ca6b/protobuf-codegen-pure/src/parse_and_typecheck.rs#L317-L347
> 
> Have a look please.
> 
> Note that:
> 
> * this function is marked as doc-hidden, so it is not considered public API, and I'm not yet ready to guarantee it won't change
> * this is master branch, version 3, which won't be released soon. I can publish another alpha version of v3 branch, but if it is needed in stable version of rust-protobuf (v2), more work is needed

Thank you very much! This will be very useful for us!

**Comment by hxsf** [comment]
In 3.0.0-alpha.8
- `trait ProtoPathResolver` is pub(crate)
https://github.com/stepancheg/rust-protobuf/blob/513b3151601ca28003dccbfbdae3c81b012c2711/protobuf-parse/src/pure/mod.rs#L3-L10
-`fs_resolver` is not pub
https://github.com/stepancheg/rust-protobuf/blob/513b3151601ca28003dccbfbdae3c81b012c2711/protobuf-parse/src/pure/parse_and_typecheck.rs#L210

How can i create a `impl ProtoPathResolver` ?
