### ISSUE TITLE
typescript/deno usage

### ISSUE THREAD

**Issue by unicomp21** [stepancheg/rust-protobuf#577]
any chance we could add an option for the wasm-bindgen annotation?  so we can consume from deno/typescript?

**Comment by stepancheg** [comment]
Can you please explain what this issue is about? I don't understand it.

**Comment by unicomp21** [comment]
The idea would be to use protocol buffers, where the codegen is done in rust, from deno/typescript.

**Comment by stepancheg** [comment]
OK, I got it. You probably need to have custom annotations per field.

It won't be implemented in rust-protobuf version 2. In rust-protobuf version 3 (currently alpha), there's [`CustomizeCallback`](https://github.com/stepancheg/rust-protobuf/blob/75841b32a5e0a5f0b2be54f0d87ef76361614d6c/protobuf-codegen/src/customize/mod.rs#L28) to change generated code.

Also consider using JSON encoding of protobuf.
