### ISSUE TITLE
Can not find the protobuf-codegen-pure dependency

### ISSUE THREAD

**Issue by fy2462** [stepancheg/rust-protobuf#578]
Hi guys:

I have upgraded the protobuf version to `3.0.0-alpha.2`, But I got the error as follows:

`    Updating git repository `https://github.com/stepancheg/rust-protobuf`
error: no matching package named `protobuf-codegen-pure` found
location searched: https://github.com/stepancheg/rust-protobuf`

I have set the version in my `cargo,toml`
`[build-dependencies]
protobuf-codegen-pure = { version = "3.0.0-alpha.2", git = "https://github.com/stepancheg/rust-protobuf" }`

How to fix that, thanks.

**Comment by stepancheg** [comment]
In latest rust-protobuf, both codegens live in `protobuf-codegen` crate.
