### ISSUE TITLE
Invalid Rust code generated with `FieldDescriptorProto.Type` extension

### ISSUE THREAD

**Issue by jgallagher** [stepancheg/rust-protobuf#579]
Hi! I'm far from a protobuf expert, but in using this crate with some work `.proto` files I ran into a codegen bug. This is a stripped-down reproducer using protoc-rust v2.25.2:

```proto
syntax = "proto2";

package bug.repro;

import "google/protobuf/descriptor.proto";

extend google.protobuf.EnumValueOptions {
    optional google.protobuf.FieldDescriptorProto.Type foo = 50000;
}

enum Demo {
    Fizz = 1 [(foo) = TYPE_UINT64];
}
```

The generated code includes this bit for the extension:

```rust
/// Extension fields
pub mod exts {

    pub const foo: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumValueOptions, ::protobuf::types::ProtobufTypeEnum<::protobuf::descriptor::FieldDescriptorProto.Type>> = ::protobuf::ext::ExtFieldOptional { field_number: 50000, phantom: ::std::marker::PhantomData };
}
```

which doesn't compile because `FieldDescriptorProto.Type` should be `FieldDescriptorProto_Type`:

```
error: expected one of `!`, `(`, `+`, `,`, `::`, `:`, `<`, `=`, or `>`, found `.`
  --> src/BugReproducer.rs:77:176
   |
77 | ...Enum<::protobuf::descriptor::FieldDescriptorProto.Type>> = ::protobuf::ext::ExtFieldOptional { field_number: 50000, phantom: ::std::ma...
   |                                                     ^ expected one of 9 possible tokens

error: aborting due to previous error

error: could not compile `protoc-rust-bug-repro`
```

A standalone repo with this reproducer in full is https://github.com/jgallagher/protoc-rust-bug-repro.

**Comment by stepancheg** [comment]
FWIW it does not reproduces in master, 05297ed3bde6a84f097666fdc6d78882117bd6f2. But it does reproduces in stable branch.

**Comment by thibault-ml** [comment]
@stepancheg Thank you for the update! Does that mean that when the stable branch gets updated, it'll likely have the fix?

**Comment by stepancheg** [comment]
> Does that mean that when the stable branch gets updated, it'll likely have the fix?

rust-protobuf version 3 will be released in about a month.

It basically the same code, but with API and generated code cleanup. It is somewhat backwards-incompatible.

(You can help by the way providing feedback here https://github.com/stepancheg/rust-protobuf/issues/518 or raise any issues before it's too late.)

It is possible to do the independent fix in v2 branch, but my current focus is getting version 3 ready.

> Out of curiosity, was the issue addressed specifically, or was it fixed by chance?

By chance. In rust-protobuf 3 nested objects like `FieldDescriptorProto.Type` get into own mod.

* in v2: `enum FieldDescriptorProto_Type { ... }`
* in v3: `mod field_descriptor_proto { enum Type { ... } }`

**Comment by BeyondToBe** [comment]
> > Does that mean that when the stable branch gets updated, it'll likely have the fix?
> 
> rust-protobuf version 3 will be released in about a month.
> 
> It basically the same code, but with API and generated code cleanup. It is somewhat backwards-incompatible.
> 
> (You can help by the way providing feedback here #518 or raise any issues before it's too late.)
> 
> It is possible to do the independent fix in v2 branch, but my current focus is getting version 3 ready.
> 
> > Out of curiosity, was the issue addressed specifically, or was it fixed by chance?
> 
> By chance. In rust-protobuf 3 nested objects like `FieldDescriptorProto.Type` get into own mod.
> 
> * in v2: `enum FieldDescriptorProto_Type { ... }`
> * in v3: `mod field_descriptor_proto { enum Type { ... } }`

@stepancheg thanks for your great job! Can we expect rust-protobuf version 3 will be released in this month?

**Comment by stepancheg** [comment]
Version 3 is released.
