### ISSUE TITLE
When is version 3.0.0 stable?

### ISSUE THREAD

**Issue by keienWang** [stepancheg/rust-protobuf#583]

**Comment by Ask102** [comment]
I think it's been done very quickly, looking forward to protobuf::json

**Comment by stepancheg** [comment]
Quite a lot of work is needed to make it stable (mostly polishing). And I don't work on it actively now.

So it won't happen soon. Sorry.

**Comment by keienWang** [comment]
That's a shame!

**Comment by stepancheg** [comment]
Tracking issue for version 3 https://github.com/stepancheg/rust-protobuf/issues/518

Also see https://github.com/stepancheg/rust-protobuf/blob/master/doc/past-present-future.md
