### ISSUE TITLE
Codegen uses Option even with "required" with proto2

### ISSUE THREAD

**Issue by safinaskar** [stepancheg/rust-protobuf#584]
I use master branch (commit aa516f28f26f964c0b5580bf74928d97489418f7).
I use this input file:
```protobuf
message LsMsg {
    required string name = 1;
    required int32 size = 2;
}
```
I (intentionally) use proto2.
I use `protobuf_codegen::Customize { expose_fields: Some(true), ..Default::default() })`.
I use pure codegen (not protoc).
I get this output:
```rust
pub struct LsMsg {
    // message fields
    pub name: ::std::option::Option<::std::string::String>,
    pub size: ::std::option::Option<i32>,
```
I. e. fields are still Options, despite they are marked as required. I don't want Option here

**Comment by stepancheg** [comment]
* `required` fields are not often used even with `proto2`
* partial messages are sometimes helpful even with required field
* generally this is not how other implementations do it (e.g. Java or C++)
* it requires significant amount of work to make it possible (a lot of code generator need to be patched for example; and all of it need to be maintained)
* that's not what people expect, and even if this feature is implemented, it should be hidden behind the flag

I'm closing the issue, please reopen if disagree, and if you are willing to contribute the implementation.
