### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Fiono11** [stepancheg/rust-protobuf#587]
I get this error when I run `cargo build`:

error: failed to run custom build command for `protobuf-examples v0.0.0 (/home/fiono/rust-protobuf/protobuf-examples)`

Caused by:
  process didn't exit successfully: `/home/fiono/rust-protobuf/target/debug/build/protobuf-examples-7474ebb7ebeae36a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'protoc binary not found: cannot find binary path', protoc/src/lib.rs:298:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed

**Comment by edisonljh** [comment]
I have the same error too.

**Comment by Fiono11** [comment]
I had an issue with the `protobuf` installation and reinstalled using snap (Linux).

**Comment by stepancheg** [comment]
```
protoc binary not found: cannot find binary path
```

When non-pure codegen is used, `protoc` binary is required. Documentation is updated to make it more clear now.
