### ISSUE TITLE
how can i parse caffe.prototxt file

### ISSUE THREAD

**Issue by corleonechensiyu** [stepancheg/rust-protobuf#590]
i use this code 
`let mut file = std::fs::File::open("lenet.prototxt").unwrap();`
`let param = NetParameter::parse_from_reader(&mut file);`
`println!("{:?}",param);`

return this error **Err(WireError(IncorrectTag(110)))**
version
protobuf ="2.25.2"
[lenet.zip](https://github.com/stepancheg/rust-protobuf/files/7770315/lenet.zip)
[caffe.zip](https://github.com/stepancheg/rust-protobuf/files/7770313/caffe.zip)

**Comment by corleonechensiyu** [comment]
please

**Comment by stepancheg** [comment]
To do that you need to use [`text_format`](https://docs.rs/protobuf/3.0.0-alpha.5/protobuf/text_format/fn.parse_from_str.html).

`text_format` is available only in rust-protobuf version 3 (which is alpha now).

```
NetParameter::parse_from_reader
```

parses binary.
