### ISSUE TITLE
Replacement for parse_length_delimited_from_reader

### ISSUE THREAD

**Issue by spacekookie** [stepancheg/rust-protobuf#593]
I'm still using the `2.x` version of the crate where `protobuf::parse_length_delimited_from_reader` is deprecated but also doesn't seem to work.

Writing three types to a buffer resulting in this data layout: `[19, 26, 4, 110, 97, 109, 101, 26, 3, 97, 103, 101, 34, 2, 0, 1, 34, 2, 1, 0, 2, 24, 12, 11, 18, 3, 98, 111, 98, 18, 4, 0, 0, 0, 64]` but then fails to parse (via `protobuf::parse_length_delimited_from_reader()`) because of this error: `Result::unwrap()` on an `Err` value: `Encoding(WireError(UnexpectedEof))`

Any advice?

**Comment by stepancheg** [comment]
```
let input = CodedInputStream::new(reader);
input.read_message()
```

should work.

**Comment by stepancheg** [comment]
Also, don't be confused about reading length-limited vs raw messages.
