### ISSUE TITLE
Broken links in protobuf-codegen README

### ISSUE THREAD

**Issue by 4nte** [stepancheg/rust-protobuf#594]
Links for protoc-codegen-pure and protoc-rust are broken.
Source: https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-codegen

https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-codegen-pure

https://github.com/stepancheg/rust-protobuf/tree/master/protoc-rust

**Comment by stepancheg** [comment]
Should be fixed now.
