### ISSUE TITLE
Is possible to read a repeat field one by one?

### ISSUE THREAD

**Issue by darsvador** [stepancheg/rust-protobuf#598]
````proto
message BigSizeList {
  repeated SmallSize entry = 1;
}
````
I have a binary protobuf file of BigSizeList which consumes large memory after total deserialized. I only need a small part of its repeatfield. Is possible to read a repeat field one by one so that I can filter them manually?

**Comment by stepancheg** [comment]
Only manually.

Like this (pseudocode):

```
let is = CodedInputStream::new(...);
while !is.eof()? {
  let (field, wf) = is.read_tag_unpack()?;
  assert!(field == 1);
  assert!(wf == LengthDelimited);
  let entry = is.read_message()?;
}
```

Generally protobuf is not meant to be used for partial reading.

Another option is to create an alternative small message:

```
message BigSizeListSubset {
  repeated SmallSizeSubset entry = 1;
}

message SmallSizeSubset {
  only fields you need
}
```

Unused fields will go into `UnknownFields`, which might be a little better, not sure. There's no option currently to discard unknown fields.

One more option is to use `with-bytes`, so at least strings would be shared with input (if input is array).

**Comment by darsvador** [comment]
Thank you very much for your wonderful advice.
