### ISSUE TITLE
support: dynamic message parsing

### ISSUE THREAD

**Issue by marlon-sousa** [stepancheg/rust-protobuf#608]
Hello,

I have been investigating a way of providing a GRPC wiremock like functionality.

This would help greatly on integration tests which need to provide a mockable end point for code under test to call.

Let me explain the general idea and then ask you how to use this crate to help me achieve part of this goal.

I got inspired by grpcurl (https://github.com/fullstorydev/grpcurl). This piece of code does the following:

1. Gets a proto file and a json as input.
2. parses dynamically the proto file and builds all messages layout on memory.
3. Gets the input json and uses its content to create the apropriate message.
4. Sends the message through GRPC.
5. gets the response message.
6. Converts the response message to JSON.
7. Outputs the response in json format.

Notice that all processing is dynamic, whithout code generation ...

This very same strategy could be used to provide a wiremock like crate, but using grpc instead. In this case, the grpc wiremock crate would instantiate a http 2 server and read all known message layouts from proto files. Upon each request, it would deserialize the message and convert it to json, and submit the now converted json to the matching system. If a response for the specific message is provided (in json), this would be parsed and coded back as the expected response, which then would be sent back to the calling code. Again, all this needs to happen dinamically, without code generation.

As GRPC is a vast and *** for me *** confusing topic, I would like to know if there are examples on how to:

1. Read bytes from a stream.
2. Obtain the message.
3. Read it and parse it in json.
4. Read from a json and encode it into a given message.

By reading the general usage of v3 I think this is possible, but I would prefer some one more experienced looking at this and pointing me out the way, if this is ever possible.

**Comment by stepancheg** [comment]
First, there are several grpc implementations in rust, and they are not part of rust-protobuf.
* tonic
* grpc-rs
* my (and incomplete) grpc-rust

dynamic messages in rust-protobuf require version 3, which is currently alpha, to be released in several weeks

> Read bytes from a stream

I assume you are talking about dynamic messages.

https://docs.rs/protobuf/3.0.0-alpha.6/protobuf/reflect/struct.MessageDescriptor.html#method.parse_from_bytes

Dynamic message descriptor can be instantiated with `FileDescriptor::new_dynamic`.

API to work *dynamically* with generated messages and with dynamic messages is the same: `MessageDescriptor` and `MessageDyn`.

> Read it and parse it in json

https://docs.rs/protobuf/3.0.0-alpha.6/protobuf/json/fn.parse_dynamic_from_str.html

There are no specific examples for your exact use case, but there's an example of using dynamic messages (to read and write to bytes):
https://github.com/stepancheg/rust-protobuf/blob/master/protobuf-examples/dynamic/src/main.rs

Your use case is valid and can be solved with rust-protobuf (apart from grpc part).

Hope that helps, feel free to ping me if you have more questions. It is likely possible that something you need is implemented, but not exposed as public API.

**Comment by stepancheg** [comment]
Closing the issue, please reopen if something else is needed.

**Comment by marlon-sousa** [comment]
Hello,

Thanks for your help. I keep investigating the way to do the mocking system.

I see that at https://github.com/stepancheg/rust-protobuf/blob/master/protobuf-examples/dynamic/src/main.rs there is a line

```
let mut file_descriptor_protos = protobuf_parse::Parser::new()
```

When I tried to use it in my application I realized that protobuf_parse could not be resolved. The use clauses at the top of the example apparently didn't import it either.


I suspect that this has to do with the sub crate protobuf-parse, but am not sure at the moment. I could probably import this using the path feature from cargo and pointing at a directory with this path in place, but I need to know if this is going to be exported in the main crate or not, or if I should be looking for something else.

Marlon

**Comment by stepancheg** [comment]
> sub crate protobuf-parse

It is a separate crate, which need to be depended upon explicitly, [like this](https://github.com/stepancheg/rust-protobuf/blob/665f2e1f737ca24efb38a9e1fc891d438e239402/protobuf-examples/dynamic/Cargo.toml#L10).

> if this is going to be exported in the main crate or not

No it won't be reexported from protobuf crate. The dependency is reverse: `protobuf-parse` depends on `protobuf`, not vice versa.

**Comment by marlon-sousa** [comment]
Hmm ... it makes sense. However, once the v3 is released, how would one use the protobuf-parse? I mean the path trick won't work ... or the protobuf-parse is going to be released as an authonomous crate in crates.io?

Crates versus git repositories is still something that confuses me sometines.

**Comment by stepancheg** [comment]
> protobuf-parse is going to be released as an authonomous crate in crates.io?

[It is already on crates.io](https://crates.io/crates/protobuf-parse). It is just not released as stable yet.

> Crates versus git repositories is still something that confuses me sometimes.

No, rust-protobuf and it's three crates — protobuf, protobuf-parse and protobuf-codegen are meant to be only used via crates, not via git.

The example references in-repo path for convenience of development. Perhaps I should add a comment there explaining it.
