### ISSUE TITLE
customize_callback not generated for EnumOrUnknown

### ISSUE THREAD

**Issue by wrazik** [stepancheg/rust-protobuf#609]
Hi! 
Thank you for great library. 

I was trying to use rust-protobuf with these proto files: https://github.com/wirepas/backend-apis/blob/master/gateway_to_backend/protocol_buffers_files/wp_global.proto#L25

It generates something like this:
```rust
    res: ::std::option::Option<::protobuf::EnumOrUnknown<super::error::ErrorCode>>,
```
I've also added serde serialization/deserialization from the examples, full build.rs looks like this:
```rust
fn main() {
    struct GenSerde;

    impl CustomizeCallback for GenSerde {
        fn message(&self, _message: &MessageDescriptor) -> Customize {
            Customize::default().before("#[derive(::serde::Serialize, ::serde::Deserialize)]")
        }

        fn special_field(&self, _message: &MessageDescriptor, _field: &str) -> Customize {
            Customize::default().before("#[serde(skip)]")
        }
    }

    Codegen::new()
        .protoc()
        .cargo_out_dir("wirepass")
        .inputs(&[
            "./backend-apis/gateway_to_backend/protocol_buffers_files/error.proto",
            "./backend-apis/gateway_to_backend/protocol_buffers_files/wp_global.proto",
            "./backend-apis/gateway_to_backend/protocol_buffers_files/data_message.proto",
        ])
        .include("./backend-apis/gateway_to_backend/protocol_buffers_files")
        .customize_callback(GenSerde)
        .run_from_script();
}
```
It fails to compile because of lack of "Serialize" for EnumOrUnknown:

```bash
253  |     res: ::std::option::Option<::protobuf::EnumOrUnknown<super::error::ErrorCode>>,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Serialize` is not implemented for `EnumOrUnknown<ErrorCode>`

 ```
     
Looks like customize_callback is not added to EnumOrUnknown.

**Comment by stepancheg** [comment]
[`serialize_with`](https://serde.rs/field-attrs.html#serialize_with) need to be added to enum fields, and it should point to the serializer in your project.

`EnumOrUnknown` is a type inside rust-protobuf library so it cannot be annotated with serde because rust-protobuf (no longer) depends on serde.

What's your use case for serde with rust-protobuf?

**Comment by stepancheg** [comment]
Added an example with enum in 621d18dcdbd9c6de0f932352c16aa186e3493bcf.

**Comment by wrazik** [comment]
Thank you for usefull example.
Real-life use-case: I have IoT device that sends protobuf messages to mqtt, however HomeAssistant (IoT platform) understands jsons only. I'm writing translator between these two. 

I've just noticed that version 3 of the rust-protobuf contains print_to_json, which I think will be enough for me :) 

As it solves my  problem I'm closing the Issue. Thanks!
