### ISSUE TITLE
rustfmt is not skipped for generated mod.rs

### ISSUE THREAD

**Issue by hanabi1224** [stepancheg/rust-protobuf#621]
After upgrading to v3, the imports in generated mod.rs are no longer in alphabetic order, thus `cargo fmt -- --check` command fails. Should it also include `#![cfg_attr(rustfmt, rustfmt::skip)]`? Thanks.

**Comment by stepancheg** [comment]
Unfortunately, adding `#![cfg_attr(rustfmt, rustfmt::skip)]` will make it impossible to include generated file in source

```
include!(concat!(env!("OUT_DIR"), "/p/mod.rs"));
```

There are two options here:
* sort imports in generated file (PR welcome)
* specify rustfmt [option](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#format_generated_files) to skip files marked as `@generated`

**Comment by stepancheg** [comment]
Reopening until merged to stable branch.

**Comment by stepancheg** [comment]
Done.
