### ISSUE TITLE
Optional fields not supported in proto3 syntax

### ISSUE THREAD

**Issue by jesseduffield** [stepancheg/rust-protobuf#625]
If I try to generate code with protoc-gen-rust i.e. with the command: `protoc --rust_out=out test.proto` I get the following error:

> test.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-rust hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--rust_out:

Here's my `test.proto` file:
```proto
syntax = "proto3";

message Test {
  optional string value = 1;
}
```

Without the `optional` keyword the command does not raise an error. Likewise, if I change the syntax to proto2, the command does not raise an error.

I installed `protoc-gen-rust` via `cargo install protobuf-codegen` (version v3.0.2 was installed).

OS version:
```sh
uname -a
Linux 78ae9044ec23 5.10.104-linuxkit #1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64 Linux
```

Looking through the docs, it seems that optional fields should be supported, so I'm not sure if I'm doing something wrong or not. My goal is to end up with an Option<T> in the generated rust code.

Thanks :)

**Comment by stepancheg** [comment]
Interesting. Optional fields work, but when using `protobuf-codegen` crate, and I didn't test with `protoc` crate.

If you need to run `protoc` manually, this need to be implemented (in rust-protobuf): https://github.com/protocolbuffers/protobuf/blob/main/docs/implementing_proto3_presence.md#signaling-that-your-code-generator-supports-proto3-optional

**Comment by jesseduffield** [comment]
Thanks for the quick response. When you say it needs to be implemented: are you referring to actually implementing support for proto3 optional fields, or do you just mean telling protoc that we already do have support?

**Comment by stepancheg** [comment]
> are you referring to actually implementing support for proto3 optional fields, or do you just mean telling protoc that we already do have support?

The latter, only need to signal to `protoc`.

proto3 optional is implemented [here](https://github.com/stepancheg/rust-protobuf/blob/master/test-crates/protobuf-codegen-protoc-test/src/v3/test_optional_pb.proto).

**Comment by jesseduffield** [comment]
I believe https://github.com/stepancheg/rust-protobuf/pull/626 will do the trick

**Comment by stepancheg** [comment]
3.0.3
