### ISSUE TITLE
Clear a field through reflection

### ISSUE THREAD

**Issue by appaquet** [stepancheg/rust-protobuf#627]
There doesn't seem to be a way to clear the value of a singular field through reflection (via the `FieldDescriptor`). Map and repeated fields can be cleared using their respective `clear()` methods on `ReflectRepeatedMut` and `ReflectMapMut`, but there doesn't seem to be a way to do it on singular fields. I would have expected `set_singular_field` to accept an optional value, or simpler, expose a `clear_field` on the `FieldDescriptor`.

I looked at the code to implement such method, but it seems to be more complex than anticipated when dealing with generated messages. `SingularFieldAccessor` would either need to accept an optional value on `set_field` or expose a `clear_field` method, but it seems to imply modifying the code generation at first sight (generated code that make use of `make_message_field_accessor` doesn't seem to be clearable? I guess this is for non-optional fields with protobuf v2?) 

Thanks!

**Comment by stepancheg** [comment]
I think you are right, `SingularFieldAccessor` needs `clear` operation.

I think no changes in generated code needed, but I'm not sure. But anyway, at the moment, generated code is not guaranteed to be stable across revisions, so changing generated code should be fine.

> generated code that make use of make_message_field_accessor doesn't seem to be clearable

That is one definitely clearable. It provides access to `&mut MessageField` so everything can be done with it. Not sure about the others though.

**Comment by appaquet** [comment]
@stepancheg I had this branch that works on my side for my use case: https://github.com/stepancheg/rust-protobuf/compare/master...appaquet:feat/reflect-clear-field?expand=1

Let me know if it's PR worthy or if you had another implementation in mind.

**Comment by stepancheg** [comment]
@appaquet looks good, if there's also a test.
