### ISSUE TITLE
How can I use tonic and this crate to make a gRPC call with dynamic message?

### ISSUE THREAD

**Issue by TENX-S** [stepancheg/rust-protobuf#638]
Hi,
I'm trying to make a tool like [bloomRPC](https://github.com/bloomrpc/bloomrpc). And I prefer to implement the core API with rust.
But I'm stuck at the most important part, as the title says :(. Could I ask some guidance on this? Thanks in advance :)

Here's my [attempt](https://github.com/TENX-S/attempt).
Start the server first, then the client go with the following output:

```
request: {"name": "World"}
reply: {"message": "Hello World!"}
Err(
    Status {
        code: Internal,
        message: "protocol error: received message with invalid compression flag: 10 (valid flags are 0 and 1) while receiving response with status: 200 OK",
        source: None,
    },
)
```

This error is confusing. I use Wireshark to get the packet and the compression flag is not corrupted:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40336192/176586707-eb274b20-e657-4cc1-ba1f-e0d7cafd7fc8.png">

**Comment by dfrankland** [comment]
Not sure if you got your attempt working. I have a similar use case and was able to get an example together:
https://github.com/dfrankland/tonic-no-codegen-example
