### ISSUE TITLE
URL for protoc is a 404

### ISSUE THREAD

**Issue by CountOmega** [stepancheg/rust-protobuf#640]
I am in the process of packaging the protoc crate for debian. The [link](https://github.com/stepancheg/rust-protobuf/tree/master/protoc/) for the crate results in a 404 and I can't seem to find the source anywhere. Is it just generated somewhere? Please consider fixing this as the source needs to be accurate for the packaging process

**Comment by stepancheg** [comment]
`protoc` crate does not exist in version 3.

This is it in branch 2: https://github.com/stepancheg/rust-protobuf/tree/v2.27/protoc

**Comment by CountOmega** [comment]
Ah thank you. That should fix my issue.
