### ISSUE TITLE
protobuf_parse write out schema

### ISSUE THREAD

**Issue by wackazong** [stepancheg/rust-protobuf#666]
I am using your parser to parse some `.proto` files, extracting options and modifying the build process for `tonic_build`. It works beautifully, many thanks for your excellent work. 

One requirement I would have is to parse the schema files, modify some parts (adding the `json_name` option to every field) and then write them to files again in order to be processed by `tonic_build`. I have not found a way to do that. Do you know if I overlooked something?

**Comment by xfbs** [comment]
Hey @wackazong — I am looking to do the exact same thing. My idea was to pull out the parser and give it the ability to do that.

**Comment by wackazong** [comment]
Great. I have no immediate need anymore, therefore I did not go down that road. Would be great to keep your work within this package I guess, in order to avoid having to keep the packages in sync.
