### ISSUE TITLE
Protoc Codegen Output

### ISSUE THREAD

**Issue by HiceS** [stepancheg/rust-protobuf#677]
Hey all so I originally used protobuf-codegen rust plugin with protoc to generate the output for a 3D file format that you can find here : [https://github.com/HiceS/mirabuf](https://github.com/HiceS/mirabuf)

I was originally running: `protoc --rust_out ./libs/rust *.proto` and it generated everything correctly.

Now I get the following error while trying to generate with that command 

```The Rust codegen is highly experimental. Future versions will break existing code. Use at your own risk. You can opt-in by passing 'experimental-codegen=enabled' to '--rust_out'.```

doing this gives me a error to specify the kernel as either cpp or upb,

So now I use the following command with the flag enabled 
`protoc --rust_out=experimental-codegen=enabled,kernel=cpp:./libs/rust/src/ *.proto`

The problem is that now the code output is mostly C code with a little rust to do loading which does not port to WASM where I am currently using it effectively. 

Here is an example of the original generated file that is still used : 

[https://gist.github.com/HiceS/dc57fc3bcf2a30ec52abec44450cbc39](https://gist.github.com/HiceS/dc57fc3bcf2a30ec52abec44450cbc39)

Is there anything I am missing or doing incorrectly to get the current file generation ? 

Also the built-in build.rs strategy does not work at all for me because it fails to discover all of the files in that directory for input. Ideally I would like to auto-publish a cargo package from my mirabuf repo as a github action.

**Comment by HiceS** [comment]
I have updated my protoc version to `libprotoc 23.3`

**Comment by torsina** [comment]
Did this fix your issue ? @HiceS 

I'm still trying to make a basic example from a `build.rs` and take all the proto files in one dir and make the rust equivalent in another, but I've seen like half a dozen repo tonight pretending to do this and never understood how these massive projects were supposed to be libraries to use

**Comment by HiceS** [comment]
I have used some packages in the past but I ended up pre-generating them and publishing them to a crate directly to use. I believe I ended up using protobuf-rs however.

**Comment by stepancheg** [comment]
`protoc --rust_out` without plugin is default Google protobuf codegen, which is meant to be used with Google's protobuf.

It is unrelated to rust-protobuf.

**Comment by jesseXu** [comment]
Correct me if I am wrong, follow the documentation there, it will lead to this result. Even if I specify the --plugin param to use rust-protobuf get same result.
