### ISSUE TITLE
Best way to deserialize an extension?

### ISSUE THREAD

**Issue by chanced** [stepancheg/rust-protobuf#708]
Hey, first off, thanks for the library! Ya'll have done awesome work with it.

I'm porting protoc-gen-star and need to be able to extract extensions but I'm a bit unclear how to go about it. From what I can tell, using reflection seems to be the best way forward but I just wanted to double check.

Thank you for your time.

**Comment by chanced** [comment]
Would you be open to exposing `field_number` and `field_type` on `ExtFieldOptional` and `ExtFieldRepeated`?

**Comment by stepancheg** [comment]
Hey.

This project is barely maintained now.

Sorry if I don't always reply.

By extensions you mean proto2 extensions which are deprecated in proto3? Why would you want them?

**Comment by chanced** [comment]
Hey,

No worries whatsoever!

All but options are unsupported in proto3. Strangely enough, that just pertains to the definitions. As such, projects such as [protoc-gen-validate](https://github.com/bufbuild/protoc-gen-validate) define the extension in proto2 and then you can utilize them in proto3 files.

As to why I need them, I'm working on lib ([source](https://github.com/chanced/catalyze/tree/initial-version)) similar to [protoc-gen-star](https://github.com/lyft/protoc-gen-star). As of right now, I completely destruct the `FileDescriptor`s but that leaves me in a state where I can not deserialize extensions.

I was also hoping to fully encapsulate the protobuf crate. I guess I can clone the descriptors and retain them, but then users will be locked in.

**Comment by stepancheg** [comment]
OK, I must say, I do not understand what you are trying to achieve.

Starting with "protoc-gen-star" — github page have a wall of text with no clear explanation what does it do.

Can you please describe it a flow in simple terms like:

- I have a proto file, which is generated to rust file
- or I have proto file, which I parse using parser API and work with using reflective API
- I do custom code generation
- or I process existing messages using protobuf-rust generated code

> Would you be open to exposing `field_number` and `field_type` on `ExtFieldOptional` and `ExtFieldRepeated`?

I would like to understand first, what's the use case. Because if you have generated code already, then you can just use `::get` function to fetch the message from `UnknownFields`. So why need for these fields?

**Comment by chanced** [comment]
Sure, absolutely.

> I do custom code generation

this, basically, but it could also be used for analysis, I suppose.

The initial plan is to offer a lib that makes building protoc plugins easier. I am going to accept either an `impl Read` that contains a `CodeGeneratorRequest` or a`FileDescriptorSet` and a list of targets. Users can then pass in generators, basically a 1-method trait which accepts an `Ast` as a directed graph and return a list of artifacts to generate (file name + content + a few opts).

Generators and post processors (1-method trait which can modify all artifacts) run, `CodeGeneratorResponse` is written out to an `impl Write`.

> Because if you have generated code already, then you can just use ::get function to fetch the message from UnknownFields. So why need for these fields?

I can definitely get the values - the problem is aligning them with user-supplied target types.

Each of the nodes in my graph needs a method which can attempt to deserialize a subset of unknown fields into a generic type. If I only have `UnknownFields`, I can not determine which fields are needed from the `ExtFieldOptional` and co. I would need the entire descriptor for that.

**Comment by chanced** [comment]
The source for `ExtFieldOptional::get`:
https://github.com/stepancheg/rust-protobuf/blob/0d2dbd8b273dd66f1e82559559729147e0da6761/protobuf/src/ext.rs#L54-L63

I was essentially hoping to be able to do the above.

**Comment by chanced** [comment]
> I would need the entire descriptor for that.
I was wrong about this, I'd just need the respective `*Options`. That makes retention a lot easier.

I'd still love to be able to access those fields tho. It'd enable me to craft a trait that I may later be able to implement for say, prost + prost reflect, I guess. I dunno. But if this crate is maintenance mode, having that option would be nice.

**Comment by stepancheg** [comment]
@chanced can you e-mail me to stepan.koltsov@gmail.com please?
