### ISSUE TITLE
CodedOutputStream panics on broken pipe

### ISSUE THREAD

**Issue by amyipdev** [stepancheg/rust-protobuf#714]
When a CodedOutputStream flushes into a broken pipe, instead of returning up an error through the function stack, it panics. This takes down my application instead of providing for a graceful failure.

Where `sock` is a `UnixStream`, and `resp` is a protobuf message, the panic happens upon execution of the following line:
```rs
resp.write_to(&mut protobuf::CodedOutputStream::new(sock))?;
```

Error:
```
thread 'main' panicked at /home/amy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/protobuf-3.3.0/src/coded_output_stream/mod.rs:1014:40:
failed to flush: Error(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
```
(will provide full stack trace upon request)

OS: Fedora 39
Rust-Protobuf version: 3.3.0

**Comment by amyipdev** [comment]
This is causing me many different types of issues - for instance, when my client applications bail out, they close the pipe before the server wants/can know, causing a panic instead of a handle-able error.

Will this be patched? I can submit a PR if needed - but I might have to fork this if this will not be fixed.

**Comment by stepancheg** [comment]
Closing as fixed.
