### ISSUE TITLE
Negative protobuf field numbers cause task to panic

### ISSUE THREAD

**Issue by dflemstr** [stepancheg/rust-protobuf#74]
**Steps to reproduce**:

`foo.proto`:
```protobuf
message Bar {
  optional string name = 1;
}
```

`main.rs`:
```rust
extern crate protobuf;
use protobuf::core::parse_from_bytes;

mod foo;
use foo::Bar;

fn main() {
  let bar: Bar = parse_from_bytes(&[1, 2, 3]).ok().unwrap();
  println!("{:?}", bar);
}
```

**Expected**:
  - `parse_from_bytes` returns a `Result` with an `Err(ProtobufError::WireError(...))`

**Actual**:
  - The task panics:

    ```
    thread '<main>' panicked at 'field number must be positive', /home/dflemstr/.cargo/git/checkouts/rust-protobuf-ed1e2bca5258dbce/master/src/lib/stream.rs:86
An unknown error occurred
    ```

**Comment by stepancheg** [comment]
It seems to be a correct error message. First byte (`1`) is decoded to field number `0` and wire type `1`. `0` is not valid field number.

**Comment by stepancheg** [comment]
Also, please note, that rust-protobuf itself does not cause panic. It is client code that panics when rust-protobuf reports error.

**Comment by dflemstr** [comment]
I'm 100% sure that it is the protobuf code that panics. It uses `assert!` which causes the panic.

I have to write this code to work around the issue:



    try!(s.recv(&mut msg, 0));
    unsafe {
        // This is the most annoying thing ever; the protobuf library
        // crashes on bad input.  We need to actually catch this error
        // using super unsafe code

        // If the try block doesn't set anything, this is the default
        let mut parsed = Option::None;

        // Isolate the execution
        let r = try(|| {
            parsed = Option::Some(
                protobuf::parse_from_bytes::<Request>(msg.as_slice())
                    .map_err(|e| Error::Protobuf(e)))
        });

        match r {
            Err(e) => {
                let m = e.downcast::<&str>().map(|b|*b)
                    .ok().unwrap_or("Unknown error").to_string();
                parsed = Option::Some(
                    Err(Error::Protobuf(ProtobufError::WireError(m))))
            },
            _ => {}
        }

        parsed.unwrap()
    }

**Comment by dflemstr** [comment]
I can contribute a fix for this as soon as the issue is acknowledged!

**Comment by stepancheg** [comment]
Sorry, you are right, it is protobuf who causes panic. I was confused by your code example which calls `unwrap` (which also could cause panic).

I'll fix that.

**Comment by dflemstr** [comment]
Thanks for the quick fix! :+1:
