### ISSUE TITLE
What's the point of RepeatedField?

### ISSUE THREAD

**Issue by edre** [stepancheg/rust-protobuf#84]
Some repeated types are implemented with Vec, and some are implemented with RepeatedField. RepeatedField seems to be just using a Vec as a growable capacity, but Vec already does this internally. Is there a plan to replace all remaining RepeatedField with Vec at some point?

**Comment by stepancheg** [comment]
The idea behind `RepeatedField` is to reuse allocated memory for nested structures.

Suppose you have:

```
message A {
    repeated B b = 1;
}

message B {
    optional string s = 1;
}
```

If you parse `A` in loop, like this:

```
let mut a = A::new();
loop {
    a.clear();
    stream.merge_message(&mut a).unwrap();
    // process a
}
```

In that case after couple of iterations malloc won't be used, becase `.clear()` does not release memory back to malloc.

If you are using `Vec`, memory for `B::s` will be allocated and released on each iteration.

Google protobuf C++ uses this trick.

So there is no plan to replace `RepeatedField` with `Vec` by default, but if there's demand, it is possible to implement protobuf option to generate `Vec`.
