### ISSUE TITLE
Messages encoded with a numeric field set are only partially encoded

### ISSUE THREAD

**Issue by borntyping** [stepancheg/rust-protobuf#85]
When I encode a message with a numeric field set it is only partially encoded, and an identical stream of bytes are written that encoding a message without that field set writes. This happens for `sint64`, `int64`, `float` and `double` fields.

It does not seem to happen when *only* a numeric field is sent, though I haven't attempted to decode such a message.

I've reproduced the issue in this gist:
https://gist.github.com/borntyping/ae4b2436b668ebc8e774

```
{str: "hello world"} -> [104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100]
{num_int64: 64 str: "hello world"} -> [104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100]
```

**Comment by stepancheg** [comment]
It's very strange, I'll look into it soon.

**Comment by stepancheg** [comment]
There's a bug in your `FakeWriter` implementation:

```
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.vec = buf.to_vec(); // <--- HERE
        Ok(buf.len())
    }
```

It just overwrite contents of the buffer instead of appending to it.

Note, that `rust-protobuf` has shortcuts to write to vector, e. g.

```
a.write_to_vec(v); // append message to vector
a.write_to_stream(stream); // no need to explicitly create CodedOutputStream
a.write_to_bytes(); // just return Vec<u8>
```

**Comment by borntyping** [comment]
Thanks - I'll try and recreate it using those methods, though I saw the same behaviour writing to a `TCPStream`.
