### ISSUE TITLE
Doesn't compile with rust 1.0.0-nightly (build 2015-03-27)

### ISSUE THREAD

**Issue by phifty** [stepancheg/rust-protobuf#88]
Hi,

'cargo build' cannot compile the master branch.

/.cargo/git/checkouts/rust-protobuf-ed1e2bca5258dbce/master/src/lib/codegen.rs:106:27: 106:44 error: box pattern syntax is experimental
/.cargo/git/checkouts/rust-protobuf-ed1e2bca5258dbce/master/src/lib/codegen.rs:106             RustType::Ref(box RustType::Str)         => "\"\"".to_string(),

Hope that helps ;-)
Cheers,
Philipp

**Comment by stepancheg** [comment]
It works with nightly now.
