### ISSUE TITLE
Doesn't compile with 1.0.0 beta.

### ISSUE THREAD

**Issue by parbo** [stepancheg/rust-protobuf#94]
src/lib/protobuf.rs:2:1: 2:33 error: unstable feature
src/lib/protobuf.rs:2 #![feature(box_patterns, alloc)]
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/lib/protobuf.rs:5:1: 5:25 error: unstable feature
src/lib/protobuf.rs:5 #![feature(collections)]
                      ^~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/lib/protobuf.rs:6:1: 6:21 error: unstable feature
src/lib/protobuf.rs:6 #![feature(convert)]
                      ^~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/lib/protobuf.rs:7:1: 7:18 error: unstable feature
src/lib/protobuf.rs:7 #![feature(core)]
                      ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/lib/protobuf.rs:8:1: 8:22 error: unstable feature
src/lib/protobuf.rs:8 #![feature(str_char)]
                      ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to 5 previous errors
Could not compile `protobuf`.

**Comment by phifty** [comment]
+1

**Comment by stepancheg** [comment]
Tried to fix to work with beta, and couldn't. But at least it works with nightly, thanks to #95.

**Comment by paulosuzart** [comment]
+1
